
//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGo.cpp
// Header definition of class TCAEUTLGo
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TCAEUTLGo_H
#define TCAEUTLGo_H

#include "TCAUTLComponentMacro.h"
#include "CATMathVector.h"
#include "CATMathPlane.h"
#include "CATPathElement.h"
#include "CATLISTV_CATBaseUnknown.h" 
#include "CATUnicodeString.h"
#include "CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATListOfDouble.h"
#include "CATDocument.h"
#include "CATDialog.h" 
#include "CATListOfCATCells.h"
#include "CATLISTV_CATMathPoint.h"
#include "CATLISTV_CATMathVector.h"
#include "CATLISTV_CATMathPlane.h" 

//-----------------------------------------------------------------------

TCA_UTL_COMPONENT_H(UTLSingleTon)

class TCAEUTLGo : public CATBaseUnknown

{
  CATDeclareClass;

private:

  CATUnicodeString m_Uuid;
  CATUnicodeString m_ParentUuid;
  CATUnicodeString m_JLine;

  CATListValCATBaseUnknown_var m_Members;
  CATListValCATBaseUnknown_var m_InputMembers;
  CATListValCATBaseUnknown_var m_OutputMembers;
  CATListValCATBaseUnknown_var m_InOutMembers;

public:

  // Standard constructors and destructors
  // -------------------------------------
  TCAEUTLGo();
  virtual ~TCAEUTLGo();


public:

  // uuid
  virtual CATUnicodeString getUuid(void);
  virtual CATUnicodeString getParentUuid(void);
  virtual void setParentUuid(const CATUnicodeString& i_rUuid);

  // manages JLine
  virtual void addJLine(const CATUnicodeString& i_rToAdd);
  virtual void getJLine(CATUnicodeString& o_rJLine);

  // run
  virtual HRESULT run(void);


  // dump
  virtual void dump(void);


  // members
  virtual CATBaseUnknown_var getMemberByName(const CATUnicodeString& i_rName);

  virtual HRESULT getMembers(CATListValCATBaseUnknown_var& o_rListValue);

  virtual HRESULT copyMembersFrom(CATBaseUnknown_var i_spUTLGoFrom);


  virtual HRESULT getMembersRef(CATListValCATBaseUnknown_var& o_rListValue);


  // set value from
  virtual HRESULT setValueFrom(const CATUnicodeString& i_rName, CATBaseUnknown_var i_spUTLGoFrom);


  // Dlg
  virtual HRESULT setDlg(const CATUnicodeString& i_rName, CATDialog* i_pValue);

  virtual CATDialog* getDlg(const CATUnicodeString& i_rName);


  // CATBaseUnknown 
  virtual HRESULT setUnknown(const CATUnicodeString& i_rName, CATBaseUnknown_var i_spValue);

  virtual CATBaseUnknown_var getUnknown(const CATUnicodeString& i_rName);


  virtual CATBaseUnknown_var getValue(const CATUnicodeString& i_rName);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, CATBaseUnknown_var i_spValue);


  // int
  virtual HRESULT getValue(const CATUnicodeString& i_rName, int& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const int& i_rValue);


  // unsigned int 
  virtual HRESULT getValue(const CATUnicodeString& i_rName, unsigned int& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const unsigned int& i_rValue);


  // CATBoolean
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATBoolean& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATBoolean& i_rValue);


  // CATString
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATString& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATString& i_rValue);


  // CATUnicodeString
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATUnicodeString& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATUnicodeString& i_rValue);


  // CATLISTP(CATCell)
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATLISTP(CATCell)& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATLISTP(CATCell)& i_rValue);


  virtual HRESULT getInput(CATLISTP(CATCell)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATLISTP(CATCell)& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATLISTP(CATCell)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATLISTP(CATCell)& i_rValue, const int& i_rIdx = 1);


  // CATMathVector
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATMathVector& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATMathVector& i_rValue);


  virtual HRESULT getInput(CATMathVector& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATMathVector& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATMathVector& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATMathVector& i_rValue, const int& i_rIdx = 1);


  // CATMathPoint
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATMathPoint& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATMathPoint& i_rValue);


  virtual HRESULT getInput(CATMathPoint& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATMathPoint& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATMathPoint& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATMathPoint& i_rValue, const int& i_rIdx = 1);


  // CATLISTV(CATMathPoint)
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATLISTV(CATMathPoint)& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATLISTV(CATMathPoint)& i_rValue);


  virtual HRESULT getInput(CATLISTV(CATMathPoint)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATLISTV(CATMathPoint)& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATLISTV(CATMathPoint)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATLISTV(CATMathPoint)& i_rValue, const int& i_rIdx = 1);


  // CATLISTV(CATMathVector)
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATLISTV(CATMathVector)& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATLISTV(CATMathVector)& i_rValue);


  virtual HRESULT getInput(CATLISTV(CATMathVector)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATLISTV(CATMathVector)& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATLISTV(CATMathVector)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATLISTV(CATMathVector)& i_rValue, const int& i_rIdx = 1);


  // CATLISTV(CATMathPlane)
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATLISTV(CATMathPlane)& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATLISTV(CATMathPlane)& i_rValue);


  virtual HRESULT getInput(CATLISTV(CATMathPlane)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATLISTV(CATMathPlane)& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATLISTV(CATMathPlane)& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATLISTV(CATMathPlane)& i_rValue, const int& i_rIdx = 1);


  // CATListOfCATUnicodeString
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATListOfCATUnicodeString& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATListOfCATUnicodeString& i_rValue);


  virtual HRESULT getInput(CATListOfCATUnicodeString& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATListOfCATUnicodeString& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATListOfCATUnicodeString& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATListOfCATUnicodeString& i_rValue, const int& i_rIdx = 1);


  // CATListValCATBaseUnknown_var
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATListValCATBaseUnknown_var& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATListValCATBaseUnknown_var& i_rValue);


  // CATListOfDouble
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATListOfDouble& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATListOfDouble& i_rValue);


  virtual HRESULT getInput(CATListOfDouble& io_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATListOfDouble& io_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATListOfDouble& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATListOfDouble& i_rValue, const int& i_rIdx = 1);


  virtual CATListOfDouble& getInOut(const int& i_rIdx = 1);


  // CATListOfInt
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATListOfInt& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATListOfInt& i_rValue);


  virtual HRESULT getInput(CATListOfInt& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATListOfInt& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATListOfInt& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATListOfInt& i_rValue, const int& i_rIdx = 1);


  // unsigned long
  virtual HRESULT getValue(const CATUnicodeString& i_rName, unsigned long& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const unsigned long& i_rValue);


  // CATBaseUnknown_var Input 
  virtual HRESULT setInput(CATBaseUnknown_var i_spValue, const int& i_rIdx = 1);

  virtual CATBaseUnknown_var getInput(const int& i_rIdx = 1);


  // int Input
  virtual HRESULT getInput(int& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const int& i_rValue, const int& i_rIdx = 1);


  // unsigned int Input
  virtual HRESULT getInput(unsigned int& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const unsigned int& i_rValue, const int& i_rIdx = 1);


  // CATBoolean Input
  virtual HRESULT getInput(CATBoolean& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATBoolean& i_rValue, const int& i_rIdx = 1);


  // CATString Input
  virtual HRESULT getInput(CATString& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATString& i_rValue, const int& i_rIdx = 1);


  // CATUnicodeString Input
  virtual HRESULT getInput(CATUnicodeString& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATUnicodeString& i_rValue, const int& i_rIdx = 1);


  // CATListValCATBaseUnknown_var Input
  virtual HRESULT getInput(CATListValCATBaseUnknown_var& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATListValCATBaseUnknown_var& i_rValue, const int& i_rIdx = 1);


  // unsigned long Input
  virtual HRESULT getInput(unsigned long& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const unsigned long& i_rValue, const int& i_rIdx = 1);


  // CATBaseUnknown_var Output 
  virtual HRESULT setOutput(CATBaseUnknown_var i_spValue, const int& i_rIdx = 1);

  virtual CATBaseUnknown_var getOutput(const int& i_rIdx = 1);


  // int Output
  virtual HRESULT getOutput(int& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const int& i_rValue, const int& i_rIdx = 1);


  // unsigned int Output
  virtual HRESULT getOutput(unsigned int& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const unsigned int& i_rValue, const int& i_rIdx = 1);


  // CATBoolean Output
  virtual HRESULT getOutput(CATBoolean& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATBoolean& i_rValue, const int& i_rIdx = 1);


  // CATString Output
  virtual HRESULT getOutput(CATString& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATString& i_rValue, const int& i_rIdx = 1);


  // CATUnicodeString Output
  virtual HRESULT getOutput(CATUnicodeString& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATUnicodeString& i_rValue, const int& i_rIdx = 1);


  // CATListValCATBaseUnknown_var Output
  virtual HRESULT getOutput(CATListValCATBaseUnknown_var& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATListValCATBaseUnknown_var& i_rValue, const int& i_rIdx = 1);


  // unsigned long Output
  virtual HRESULT getOutput(unsigned long& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const unsigned long& i_rValue, const int& i_rIdx = 1);


  //  double 
  virtual HRESULT getValue(const CATUnicodeString& i_rName, double& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const double& i_rValue);


  virtual HRESULT getInput(double& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const double& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(double& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const double& i_rValue, const int& i_rIdx = 1);


  //  IID 
  virtual HRESULT getValue(const CATUnicodeString& i_rName, IID& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const IID& i_rValue);


  virtual HRESULT getInput(IID& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const IID& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(IID& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const IID& i_rValue, const int& i_rIdx = 1);


  // CATDocument*
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATDocument*& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, CATDocument*& i_rValue);


  virtual HRESULT getInput(CATDocument*& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(CATDocument*& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATDocument*& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(CATDocument*& i_rValue, const int& i_rIdx = 1);


  // CATPathElement 
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATPathElement& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATPathElement& i_rValue);


  virtual HRESULT getInput(CATPathElement& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATPathElement& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATPathElement& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATPathElement& i_rValue, const int& i_rIdx = 1);


  // CATMathPlane 
  virtual HRESULT getValue(const CATUnicodeString& i_rName, CATMathPlane& o_rValue);

  virtual HRESULT setValue(const CATUnicodeString& i_rName, const CATMathPlane& i_rValue);


  virtual HRESULT getInput(CATMathPlane& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setInput(const CATMathPlane& i_rValue, const int& i_rIdx = 1);


  virtual HRESULT getOutput(CATMathPlane& o_rValue, const int& i_rIdx = 1);

  virtual HRESULT setOutput(const CATMathPlane& i_rValue, const int& i_rIdx = 1);


private:
  // Copy constructor and equal operator
  // -----------------------------------
  TCAEUTLGo(TCAEUTLGo&);
  TCAEUTLGo& operator=(TCAEUTLGo&);

  // member operations
  CATBaseUnknown_var addMember(const CATUnicodeString& i_rName);

  void needs(const CATUnicodeString& i_rType, const CATUnicodeString& i_rName);

  CATBaseUnknown_var getInputMember(const int& i_rIdx);
  CATBaseUnknown_var getOutputMember(const int& i_rIdx);
  CATBaseUnknown_var getInOutMember(const int& i_rIdx);

  HRESULT resetOutputs(void);

  void traceInputs(void);
  void traceOutputs(void);
};

//-----------------------------------------------------------------------

#endif

