// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoRenameObjects.h
// Provide implementation to interface
//    TCAIUTLDoIt

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	UTLGoRenameObjects
//EXTENSIONTYPE:	DataExtension

//    TIE: TCAIUTLDoIt

//End CAA2 Wizard Generation Report
//
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLGoRenameObjects_H
#define TCAEUTLGoRenameObjects_H

#include "TCAXmlUtils.h"
#include "TCAIUTLGo.h"
#include "CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATUnicodeString.h"
#include "TCAUTLComponentMacro.h"
#include "fstream.h" 
#include "CATISpecAttrAccess.h"
#include "CATISpecAttrKey.h"
#include "CATIVisProperties.h"
#include "CATIGeometricalElement.h"

TCA_UTL_COMPONENT_H(UTLGoRenameObjects)
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TCAIUTLDoIt
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLGoRenameObjects : public CATBaseUnknown

{
  CATDeclareClass;

private:

  TCAIUTLGo_var m_spThis;
  TCAIUTLGo_var m_spSingleTon;
  CATListValCATBaseUnknown_var m_Objects;

  CATString m_ImagePath;

public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
  TCAEUTLGoRenameObjects();
  virtual ~TCAEUTLGoRenameObjects();

  /**
  * Implements a function from an interface.
  * @href TCAIUTLDoIt#doIt
  */
  virtual HRESULT doIt(void);
  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);


private:

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TCAEUTLGoRenameObjects(TCAEUTLGoRenameObjects&);
  TCAEUTLGoRenameObjects& operator=(TCAEUTLGoRenameObjects&);

  int listFromCont(CATIContainer_var i_spClientCont, CATListValCATBaseUnknown_var& o_rList);
  void initObjects(void);

  void renameObject(CATISpecObject_var i_spObj);

  void printViewer(void);

  void callAI(void);

  void setColorRGB(CATIGeometricalElement_var i_spGeomElm,
                   const unsigned int& i_R,
                   const unsigned int& i_G,
                   const unsigned int& i_B);


  void refreshVisu(CATBaseUnknown_var i_spUnknown);
};

//-----------------------------------------------------------------------

#endif
