
//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGoGSMPoint.cpp
// Header definition of class TCAEUTLGoGSMPoint
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TCAEUTLGoGSMPoint_H
#define TCAEUTLGoGSMPoint_H

#include "TCAUTLComponentMacro.h" 
#include "CATUnicodeString.h"

TCA_UTL_COMPONENT_H(UTLGoGSMPoint)

//-----------------------------------------------------------------------

class TCAEUTLGoGSMPoint : public CATBaseUnknown

{
  CATDeclareClass;

public:

  // Standard constructors and destructors
  // -------------------------------------
  TCAEUTLGoGSMPoint();
  virtual ~TCAEUTLGoGSMPoint();

  virtual HRESULT doIt(void);

  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);

private:

  // Copy constructor and equal operator
  // -----------------------------------
  TCAEUTLGoGSMPoint(TCAEUTLGoGSMPoint&);
  TCAEUTLGoGSMPoint& operator=(TCAEUTLGoGSMPoint&);
};

//-----------------------------------------------------------------------

#endif

