// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoAskAI.h
// Provide implementation to interface
//    TCAIUTLDoIt

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	UTLGoAskAI
//EXTENSIONTYPE:	DataExtension

//    TIE: TCAIUTLDoIt

//End CAA2 Wizard Generation Report
//
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLGoAskAI_H
#define TCAEUTLGoAskAI_H

#include "TCAXmlUtils.h"
#include "TCAIUTLGo.h"
#include "CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATUnicodeString.h"
#include "TCAUTLComponentMacro.h"
#include "fstream.h" 
#include "CATISpecAttrAccess.h"
#include "CATISpecAttrKey.h"
#include <Python.h>

TCA_UTL_COMPONENT_H(UTLGoAskAI)
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TCAIUTLDoIt
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLGoAskAI : public CATBaseUnknown

{
  CATDeclareClass;

private:

  TCAIUTLGo_var m_spThis;
  TCAIUTLGo_var m_spSingleTon;
  CATISpecObject_var m_spSpecPbject;

  CATUnicodeString m_PYModuleName;
  CATUnicodeString m_PYFunctionName;


public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
  TCAEUTLGoAskAI();
  virtual ~TCAEUTLGoAskAI();

  /**
  * Implements a function from an interface.
  * @href TCAIUTLDoIt#doIt
  */
  virtual HRESULT doIt(void);
  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);


private:

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TCAEUTLGoAskAI(TCAEUTLGoAskAI&);
  TCAEUTLGoAskAI& operator=(TCAEUTLGoAskAI&);

  void getPYArgument(const int i_rIdx, PyObject*& o_rPYArg);

};

//-----------------------------------------------------------------------

#endif
