// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module TCAVTATestSrcCode
#======================================================================
#  2023.09.19 Creation: Code generated by the 3DS wizard
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP ApplicationFrame CATAfrUUID  \
DI0PANV2 CATApplicationFrame 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATObjectModelerBase CATObjectSpecsModeler DI0PANV2 CATProductStructure1 KnowledgeItf CATMecModInterfaces CATGMGeometricInterfaces \
CATGMModelInterfaces CATMecModInterfaces CATMechanicalModeler CATDraftingInterfaces TCADRTXmlMD

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
