// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// TCAEUTLListDocsAddin.cpp
// Provide implementation to interface
//    CATIAfrGeneralWksAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Dec 2012  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "TCAEUTLListDocsAddin.h"
#include "CATCreateWorkshop.h"
#include <Python.h>

#if defined( _MSC_VER ) && ( _MSC_VER >= 1500 ) // 1500 = VS2008
extern "C" int _forceCRTManifestRTM = 0;
extern "C" int _forceCRTManifestCUR = 0;
#endif

CATImplementClass(TCAEUTLListDocsAddin,
                  DataExtension,
                  CATBaseUnknown,
                  TCAUTLListDocsAddin);

MacDeclareHeader(TCAUTLListDocsHeader)

#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(TCAEUTLListDocsAddin);

//-----------------------------------------------------------------------------
// TCAEUTLListDocsAddin : constructor
//-----------------------------------------------------------------------------
TCAEUTLListDocsAddin::TCAEUTLListDocsAddin()
{
  Py_Initialize();
}

//-----------------------------------------------------------------------------
// TCAEUTLListDocsAddin : destructor
//-----------------------------------------------------------------------------
TCAEUTLListDocsAddin::~TCAEUTLListDocsAddin()
{
  // Py_Finalize();
}

//-----------------------------------------------------------------------------
// CreateCommands
//-----------------------------------------------------------------------------
void TCAEUTLListDocsAddin::CreateCommands(void)
{
  new TCAUTLListDocsHeader("l", "TCAUTLListDocsMD",
                           "TCAUTLListAttrCmd", (void*)NULL, CATFrmAvailable);

  new TCAUTLListDocsHeader("j", "TCAUTLListDocsMD",
                           "TCAUTLListDocsCmd", (void*)NULL, CATFrmAvailable);

  new TCAUTLListDocsHeader("TCAUTLMacro",
                           "TCAUTLListDocsMD",
                           "TCAUTLTestCmd", (void*)NULL, CATFrmAvailable);

  new TCAUTLListDocsHeader("CATGPT",
                           "TCAUTLListDocsMD",
                           "TCAUTLGPTCmd", (void*)NULL, CATFrmAvailable);

  new TCAUTLListDocsHeader("TCAUTLRenameObj",
                           "TCAUTLListDocsMD",
                           "TCAUTLRenameObjCmd", (void*)NULL, CATFrmAvailable);

  new TCAUTLListDocsHeader("fi",
                           "TCAUTLListDocsMD",
                           "TCAUTLSaveFaceImagesCmd", (void*)NULL, CATFrmAvailable);



  return;
} // CreateCommands

//-----------------------------------------------------------------------------
// CreateToolbars
//-----------------------------------------------------------------------------
CATCmdContainer* TCAEUTLListDocsAddin::CreateToolbars(void)
{
  // MTA Init Toolbar
  NewAccess(CATCmdContainer, pGPTToolbar, GPT);
  {
    AddToolbarView(pGPTToolbar, 1, Top /*UnDock*/);

    //  MTA Filter Command 
    NewAccess(CATCmdStarter, pCATGPT, CATGPTCommand);
    SetAccessCommand(pCATGPT, "CATGPT");
    SetAccessChild(pGPTToolbar, pCATGPT);

  } // MTA Init Toolbar
  return pGPTToolbar;
} // CreateToolbars