// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// TCAUTLListDocsCmd.cpp
// The command: TCAUTLListDocsCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2012  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "TCAUTLListDocsCmd.h"
#include "CATCreateExternalObject.h"
#include "iostream.h"
#include "CATDocument.h"
#include "CATDocumentsInSession.h"
#include "CATSessionServices.h"
#include "CATIDocId.h"
#include "CATListOfCATUnicodeString.h"
#include "CATFrmEditor.h"
#include "CATCSO.h"
#include "CATIAlias.h"
#include "CATISpecAttrKey.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATISpecAttrAccess.h" 
#include "CATCommandHeader.h" 

CATCreateClass(TCAUTLListDocsCmd);

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TCAUTLListDocsCmd::TCAUTLListDocsCmd() :
  CATCommand(NULL, "TCAUTLListDocsCmd")
{
  RequestStatusChange(CATCommandMsgRequestExclusiveMode);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TCAUTLListDocsCmd::~TCAUTLListDocsCmd()
{}


//-------------------------------------------------------------------------
// Activate
//-------------------------------------------------------------------------
CATStatusChangeRC TCAUTLListDocsCmd::Activate(CATCommand* iFromClient, CATNotification* iEvtDat)
{
  // this->listAttr();
  // this->listDocs();

  this->listCommands();

  this->RequestDelayedDestruction();
  return ( CATStatusChangeRCCompleted );
} // Activate

//-------------------------------------------------------------------------
// listCommands
//-------------------------------------------------------------------------
void TCAUTLListDocsCmd::listCommands(void)
{
  CATListOfCATUnicodeString allAliases;
  int hdrCnt = CATCommandHeader::GetHeaderCount();
  cerr << hdrCnt << endl;
  int nb = 0;
  for( int h = 1; h <= hdrCnt; h++ )
  {
    CATCommandHeader* pHdr = CATCommandHeader::GetHeaderFromList(h);
    if( pHdr )
    {
      CATUnicodeString alias = pHdr->GetAlias();
      if( allAliases.Locate(alias) )
      {
        continue;
      }
      allAliases.Append(alias); 

      cerr << ++nb << "\t" << alias << endl;
      cerr << "\t\t" << pHdr->GetDefaultTitle() << endl;
      cerr << "\t\t" << pHdr->GetTitle() << endl;
      cerr << "\t\t" << pHdr->GetShortHelp() << endl;
      cerr << "\t\t" << pHdr->GetDialogLongHelp() << endl;
      cerr << "\t\t" << pHdr->GetHelp() << endl;
      cerr << "\t\t" << pHdr->GetContextualHelp() << endl;
      cerr << "\t\t" << pHdr->GetCategory2() << endl;
    }
  }
  return;
} // listCommands

//-------------------------------------------------------------------------
// listDocs
//-------------------------------------------------------------------------
void TCAUTLListDocsCmd::listDocs(void)
{
  cerr << "Loaded documents" << endl << endl;
  CATListValCATUnicodeString docsList;

  CATListOfCATUnicodeString allowTypes;
  allowTypes.Append("CATPart");
  allowTypes.Append("CATProduct");
  allowTypes.Append("CATDrawing");

  const CATLISTP(CATDocument)* pDocs = ::ListDocuments();
  if( pDocs )
  {
    for( int d = 1; d <= pDocs->Size(); d++ )
    {
      CATDocument* pDoc = ( *pDocs )[d];
      if( !pDoc )
      {
        continue;
      }

      CATUnicodeString docType("unknown type");

      CATIDocId* pDocID = NULL;
      pDoc->GetDocId(&pDocID);
      if( pDocID )
      {
        pDocID->GetType(docType);
      }

      if( !allowTypes.Locate(docType) )
      {
        continue;
      }

      int typeIdx = docsList.Locate(docType);
      if( typeIdx == 0 )
      {
        docsList.Append("\n");
        docsList.Append(docType);
        docsList.Append("--------------------");
        typeIdx = docsList.Locate(docType);
      }

      CATUnicodeString docName = pDoc->DisplayName();
      CATUnicodeString storeName = pDoc->StorageName();

      docsList.InsertAfter(typeIdx + 1, docName);

      this->listAttr(pDoc);
    }
  }


  cerr << endl << " *** " << endl;
  return;
} // listDocs

//-------------------------------------------------------------------------
// listAttr
//-------------------------------------------------------------------------
void TCAUTLListDocsCmd::listAttr(CATDocument* i_pDoc)
{
  if( !i_pDoc )
  {
    return;
  }
  CATIDocId* pDocID = NULL;
  i_pDoc->GetDocId(&pDocID);
  if( !pDocID )
  {
    return;
  }
  CATIDocEnvironment* piDocEnv = NULL;
  pDocID->GetDocEnvironment(&piDocEnv);
  if( !piDocEnv )
  {
    return;
  }

  CATUnicodeString docIdent;
  pDocID->GetIdentifier(docIdent);
  cerr << docIdent << endl;

  return;
} // listAttr

//-------------------------------------------------------------------------
// listAttr
//-------------------------------------------------------------------------
void TCAUTLListDocsCmd::listAttr(void)
{
  cerr << "*** start TCAUTLListDocsCmd::listAttr *** " << endl << endl;

  CATISpecObject_var spSelected = this->getSelectedElement();
  this->printSpec(spSelected);
  this->printAttr(spSelected);


  cerr << endl << "*** end TCAUTLListDocsCmd::listAttr *** " << endl;
  return;
} // listAttr

//-------------------------------------------------------------------------
// getSelectedElement
//-------------------------------------------------------------------------
CATISpecObject_var TCAUTLListDocsCmd::getSelectedElement(void)
{
  CATISpecObject_var spSelected = NULL_var;
  CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
  if( pFrmEditor )
  {
    CATCSO* pCSO = pFrmEditor->GetCSO();
    if( pCSO )
    {
      pCSO->InitElementList();
      CATPathElement* pPathElement = NULL;
      while( pPathElement = (CATPathElement*)pCSO->NextElement() )
      {
        spSelected = pPathElement->FindElement(IID_CATISpecObject);
        if( !!spSelected )
          break;
      }
    }
  }
  return spSelected;
} // getSelectedElement

//-------------------------------------------------------------------------
// printSpec
//-------------------------------------------------------------------------
void TCAUTLListDocsCmd::printSpec(CATISpecObject_var i_spSpec, CATUnicodeString i_Prefix)
{
  if( i_spSpec == NULL_var )
    return;

  cerr << endl << i_Prefix << "Feature type: " << i_spSpec->GetImpl()->IsA() << endl;

  CATIAlias_var spAlias = i_spSpec;
  if( !!spAlias )
    cerr << i_Prefix << "Feature name: " << spAlias->GetAlias() << endl << endl;

  return;
} // printSpec


//-------------------------------------------------------------------------
// printAttr
//-------------------------------------------------------------------------
void TCAUTLListDocsCmd::printAttr(CATISpecObject_var i_spSpec)
{
  CATISpecAttrAccess_var spSpecAttrAcc = i_spSpec;
  if( spSpecAttrAcc == NULL_var )
    return;

  CATListValCATISpecAttrKey_var attrKeys;
  HRESULT hr = spSpecAttrAcc->ListAttrKeys(attrKeys);
  for( int i = 1; i <= attrKeys.Size(); i++ )
  {
    cerr << endl;
    CATISpecAttrKey_var spAttrKey = attrKeys[i];
    if( spAttrKey == NULL_var )
      continue;

    CATISpecAttrKey* piAttrKey = NULL;
    spAttrKey->QueryInterface(IID_CATISpecAttrKey, (void**)&piAttrKey);
    if( piAttrKey )
    {
      CATUnicodeString attrName = piAttrKey->GetName();
      CATAttrKind attrKind = piAttrKey->GetType();
      CATAttrKind attrKindList = piAttrKey->GetListType();

      cerr << "Attr:\t" << attrName << endl;

      if( attrKind == tk_string )
      {
        cerr << "Type:\ttk_string" << endl;
        cerr << "Value:\t" << spSpecAttrAcc->GetString(piAttrKey) << endl;
      }
      else if( attrKind == tk_specobject )
      {
        cerr << "Type:\ttk_specobject" << endl;
        CATISpecObject* piSpec = spSpecAttrAcc->GetSpecObject(piAttrKey);
        if( piSpec )
        {
          this->printSpec(piSpec, "  ");
          piSpec->Release();
          piSpec = NULL;
        }
      }
      else if( attrKindList == tk_specobject )
      {
        cerr << "Type:\tlist of tk_specobject" << endl;
        int size = spSpecAttrAcc->GetListSize(piAttrKey);
        for( int s = 1; s <= size; s++ )
        {
          CATISpecObject* piSpec = spSpecAttrAcc->GetSpecObject(piAttrKey, s);
          if( piSpec )
          {
            this->printSpec(piSpec, "  ");
            piSpec->Release();
            piSpec = NULL;
          }
        }
      }
      else if( attrKind == tk_component )
      {
        cerr << "Type:\ttk_component" << endl;
        CATISpecObject* piSpec = spSpecAttrAcc->GetSpecObject(piAttrKey);
        if( piSpec )
        {
          this->printSpec(piSpec, "  ");
          piSpec->Release();
          piSpec = NULL;
        }
      }
      else if( attrKindList == tk_component )
      {
        cerr << "Type:\tlist of tk_component" << endl;
        int size = spSpecAttrAcc->GetListSize(piAttrKey);
        for( int s = 1; s <= size; s++ )
        {
          CATISpecObject* piSpec = spSpecAttrAcc->GetSpecObject(piAttrKey, s);
          if( piSpec )
          {
            this->printSpec(piSpec, "  ");
            piSpec->Release();
            piSpec = NULL;
          }
        }
      }
      else if( attrKind == tk_external )
      {

      }
      else if( attrKindList == tk_external )
      {

      }

      piAttrKey->Release();
      piAttrKey = NULL;
    }
  }

  return;
} // printAttr