# COPYRIGHT Dassault Systemes 2012
#======================================================================
# Imakefile for module TCAUTLListDocsMD.m
#======================================================================
#
#  Dec 2012  Creation: Code generated by the CAA wizard  wdyck
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP ApplicationFrame CATAfrUUID  \
DI0PANV2 CATApplicationFrame  CATAutoItf
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATObjectModelerBase CATObjectSpecsModeler DI0PANV2 CATProductStructure1 KnowledgeItf CATMecModInterfaces CATGMGeometricInterfaces \
CATGMModelInterfaces CATMecModInterfaces CATMechanicalModeler CATDraftingInterfaces TCADRTXmlMD TCAUTLDoItMD CATInteractiveInterfaces \
									TCAUTLItfCPP TCAUTLItf TCAUTLInterfacesUUID CATDialogEngine CATVisualization CATMathematics BODYNOPE \
                  


# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#

OS = Windows_NT 
LOCAL_CCFLAGS = -I"C:\Users\wady01\AppData\Local\anaconda3\include"
LOCAL_LDFLAGS = /LIBPATH:"C:\Users\wady01\AppData\Local\anaconda3\libs" \