//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGoGSMPoint.cpp
// Header definition of class TCAEUTLGoGSMPoint
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#include "TCAEUTLGoGSMPoint.h"
#include "CATPoint.h"
#include "CATIAlias.h"

TCA_UTL_COMPONENT_CPP(UTLGoGSMPoint)

CATImplementClass(TCAEUTLGoGSMPoint,
                  DataExtension,
                  CATBaseUnknown,
                  GSMPoint_xyz);


#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoGSMPoint);

//-----------------------------------------------------------------------------
// TCAEUTLGoGSMPoint : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoGSMPoint::TCAEUTLGoGSMPoint() :CATBaseUnknown()
{}

//-----------------------------------------------------------------------------
// TCAEUTLGoGSMPoint : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoGSMPoint::~TCAEUTLGoGSMPoint()
{}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMPoint::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "";

  CATUnicodeString alias;
  CATIAlias_var spAlias = this;
  if( !!spAlias )
  {
    alias = spAlias->GetAlias();
  }

  double x, y, z;
  CATPoint_var spPoint = this;
  if( !!spPoint )
  {
    spPoint->GetCoord(x, y, z);
  }
  CATUnicodeString xStr, yStr, zStr;
  xStr.BuildFromNum(x);
  yStr.BuildFromNum(y);
  zStr.BuildFromNum(z);
  xStr.ReplaceAll(",", ".");
  yStr.ReplaceAll(",", ".");
  zStr.ReplaceAll(",", ".");

  CATUnicodeString coordinates = xStr + ", " + yStr + ", " + zStr; 

  CATUnicodeString function = "3D-Point";

  o_rInfo = "{\"id\": \"" + alias + "\",\"embedding\": [" + coordinates + "], \"metadata\" : { \"name\": \"" + alias + "\",\"function\" : \"" + function + "\"}}";

  return S_OK;
} // getInfo


//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMPoint::doIt(void)
{
  HRESULT hr = E_FAIL;
  cerr << "NOT IMPLEMENTED: " << __FUNCTION__ << endl;
  return hr;
} // doIt




