//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGoItem.cpp
// Header definition of class TCAEUTLGoItem
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#include "TCAEUTLGoItem.h"

TCA_UTL_COMPONENT_CPP(UTLGoItem)

CATImplementClass(TCAEUTLGoItem,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGoItem);


#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoItem);

//-----------------------------------------------------------------------------
// TCAEUTLGoItem : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoItem::TCAEUTLGoItem() :CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// TCAEUTLGoItem : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoItem::~TCAEUTLGoItem()
{}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoItem::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Represents a single JSON object";
  return S_OK;
} // getInfo


//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoItem::doIt(void)
{
  HRESULT hr = E_FAIL;
  cerr << "NOT IMPLEMENTED: " << __FUNCTION__ << endl;
  return hr;
} // doIt




