// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoAssignContours.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGoAssignContours.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATScriptUtilities.h"
#include "CATAutoConversions.h"
#include "CATAfrCommandHeaderServices.h"
#include <stdlib.h>
#include "CATLine.h"

TCA_UTL_COMPONENT_CPP(UTLGoAssignContours)

CATImplementClass(TCAEUTLGoAssignContours,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGoAssignContours);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoAssignContours);

//-----------------------------------------------------------------------------
// TCAEUTLGoAssignContours : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoAssignContours::TCAEUTLGoAssignContours()
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
}

//-----------------------------------------------------------------------------
// TCAEUTLGoAssignContours : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoAssignContours::~TCAEUTLGoAssignContours()
{}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoAssignContours::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Assigns the holes of two parts according to the best-match principle, based on their positions and geometries. ";
  o_rInfo.Append("Matches the holes of two parts using a best-fit approach based on their positions and geometrical features. ");
  o_rInfo.Append("Associates the holes of two components according to the best-match criterion, considering their spatial positions and geometries. ");
  o_rInfo.Append("Verknuepft die Bohrungen zweier Teile mittels eines Best-Fit-Ansatzes auf Grundlage ihrer Lage und Geometrie. ");
  o_rInfo.Append("Weist die Bohrungen zweier Komponenten nach dem Best-Match-Kriterium unter Beruecksichtigung ihrer Positionen und geometrischen Eigenschaften einander zu. ");
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoAssignContours::doIt(void)
{
  HRESULT hr = E_FAIL;
  if( m_spThis == NULL_var || m_spSingleTon == NULL_var )
  {
    return E_FAIL;
  }

  CATListOfCATUnicodeString labels;
  TCAIUTLGo_var spGoAskAI = UTL_INST(UTLGoAskAI);
  if( !!spGoAskAI )
  {
    CATUnicodeString pyModule("TCAImgCompare");
    CATUnicodeString pyFunction("get_best_matches");
    CATUnicodeString pyImgRefDir("C:\\tmp\\heck\\old");
    CATUnicodeString pyImgTrgDir("C:\\tmp\\heck\\new");

    int argIdx = 1;
    spGoAskAI->setInput(pyModule, argIdx++);
    spGoAskAI->setInput(pyFunction, argIdx++);

    spGoAskAI->setInput(2, 1);
    spGoAskAI->setInput(pyImgRefDir, argIdx++);
    spGoAskAI->setInput(pyImgTrgDir, argIdx++);

    if( SUCCEEDED(spGoAskAI->run()) )
    {
      CATUnicodeString outputStr;
      spGoAskAI->getOutput(outputStr);
      cerr << outputStr << endl;

      CATToken token(outputStr);
      CATUnicodeString sep(";|");
      CATUnicodeString tok = token.GetNextToken(sep);
      while( tok != "" )
      {
        labels.Append(tok);
        tok = token.GetNextToken(sep);
      }
    }
  }
  CATListOfCATUnicodeString listAliases;
  CATListValCATBaseUnknown_var listLines;
  TCAUTLGetAllGSMLines(listLines);
  for( int b = 1; b <= listLines.Size(); b++ )
  {
    listAliases.Append(TCAUTLGetAlias(listLines[b]));
  }

  for( int a = 1; a < labels.Size(); a += 2 )
  {
    CATISpecObject_var spSpec1;
    CATISpecObject_var spSpec2;
    int idx1 = listAliases.Locate(labels[a]);
    int idx2 = listAliases.Locate(labels[a + 1]);
    if( idx1 > 0 && idx2 > 0 && idx1 <= listLines.Size() && idx2 <= listLines.Size() )
    {
      spSpec1 = listLines[idx1];
      spSpec2 = listLines[idx2];
    }

    CATLine_var spLine1 = spSpec1;
    CATLine_var spLine2 = spSpec2;
    if( !!spLine1 && !!spLine2 )
    {
      CATMathDirection dir1, dir2;
      spLine1->GetDirection(dir1);
      spLine2->GetDirection(dir2);
      double angle = dir1.GetAngleTo(dir2);
      if( angle > CATPIBY4 )
      {
        continue;
      }
    }

    if( !!spSpec1 && !!spSpec2 )
    {
      CATMathPoint p1 = TCAUTLGetCenterPoint(spSpec1);
      CATMathPoint p2 = TCAUTLGetCenterPoint(spSpec2);
      TCAUTLAddLineRep(p1, p2);
    }
  }

  return hr;
} // doIt

