// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLDoItMember.cpp
// Provide implementation to interface
//    TCAIUTLDoItMember
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  May 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "TCAEUTLDoItMember.h"



TCA_UTL_COMPONENT_CPP(UTLDoItMember)

CATImplementClass(TCAEUTLDoItMember,
                  DataExtension,
                  CATBaseUnknown,
                  UTLDoItMember);

#include "TIE_TCAIUTLDoItMember.h"
TIE_TCAIUTLDoItMember(TCAEUTLDoItMember);

//-----------------------------------------------------------------------------
// TCAEUTLDoItMember : constructor
//-----------------------------------------------------------------------------
TCAEUTLDoItMember::TCAEUTLDoItMember() : m_spUnknown(NULL_var)
, m_pDlg(NULL)
, m_pDocument(NULL)
{
  m_Name_set = FALSE;
  m_Int_set = FALSE;
  m_Double_set = FALSE;
  m_UnsignedInt_set = FALSE;
  m_Boolean_set = FALSE;
  m_CatStr_set = FALSE;
  m_UnicodeStr_set = FALSE;
  m_ListOfUnicodeString_set = FALSE;
  m_ListOfCATCell_set = FALSE;
  m_CATMathPoint_set = FALSE;
  m_CATMathVector_set = FALSE;
  m_ListOfCATMathPoint_set = FALSE;
  m_ListOfCATMathVector_set = FALSE;
  m_ListOfCATMathPlane_set = FALSE;
  m_ListOfCATString_set = FALSE;
  m_ListOfDouble_set = FALSE;
  m_ListOfDoubleIO_set = FALSE;
  m_ListOfInt_set = FALSE;
  m_pDlg_set = FALSE;
  m_spUnknown_set = FALSE;
  m_ListUnknown_set = FALSE;
  m_UnsignedLong_set = FALSE;
  m_IID_set = FALSE;
  m_CATPathElement_set = FALSE;
  m_CATMathPlane_set = FALSE;
  m_PWPParam_set = FALSE;
  m_PWPProcessSettings_set = FALSE;
  m_pDocument_set = FALSE;

  m_Int = 0;
  m_Double = 0.0;
  m_UnsignedInt = 0;
  m_UnsignedLong = 0;
  m_Boolean = FALSE;
}

//-----------------------------------------------------------------------------
// TCAEUTLDoItMember : destructor
//-----------------------------------------------------------------------------
TCAEUTLDoItMember::~TCAEUTLDoItMember()
{
  m_pDlg = NULL;
  m_pDocument = NULL;
  m_spUnknown = NULL_var;
}

//-----------------------------------------------------------------------------
// setName
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::setName(const CATUnicodeString& i_rName)
{
  HRESULT hr = E_FAIL;
  m_Name = i_rName;
  if( m_Name != "" )
  {
    m_Name_set = TRUE;
    hr = S_OK;
  }
  return hr;
} // setName

//-----------------------------------------------------------------------------
// getName
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getName(CATUnicodeString& o_rName)
{
  HRESULT hr = E_FAIL;
  o_rName = m_Name;
  if( o_rName != "" )
  {
    hr = S_OK;
  }
  return hr;
} // getName

//-----------------------------------------------------------------------------
// dump
//-----------------------------------------------------------------------------
void TCAEUTLDoItMember::dump(void)
{
  // int
  if( m_Int_set )
  {
    cerr << m_Name << ":\t" << m_Int << endl;
  }

  // double
  if( m_Double_set )
  {
    cerr << m_Name << ":\t" << m_Double << endl;
  }

  // unsigned int
  if( m_UnsignedInt_set )
  {
    cerr << m_Name << ":\t" << m_UnsignedInt << endl;
  }

  // CATBoolean 
  if( m_Boolean_set )
  {
    CATUnicodeString boolValue = m_Boolean ? "TRUE" : "FALSE";
    cerr << m_Name << ":\t" << boolValue << endl;
  }

  // CATUnicodeString   
  if( m_UnicodeStr_set )
  {
    cerr << m_Name << ":\tCATUnicodeString length " << m_UnicodeStr.GetLengthInChar() << endl;
  }

  if( m_CATMathPlane_set )
  {
    m_CATMathPlane.Dump();
  }

  return;
} // dump

//-----------------------------------------------------------------------------
// trace
//-----------------------------------------------------------------------------
void TCAEUTLDoItMember::trace(void)
{
  return;
} // trace

//-----------------------------------------------------------------------------
// copyValuesFrom
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::copyValuesFrom(CATBaseUnknown_var i_spMemberFrom)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMemberFrom = i_spMemberFrom;
  if( !!spMemberFrom )
  {
    // int
    int valueInt = 0;
    if SUCCEEDED(spMemberFrom->getValue(valueInt))
      this->setValue(valueInt);

    // double
    double valueDbl = 0.0;
    if SUCCEEDED(spMemberFrom->getValue(valueDbl))
      this->setValue(valueDbl);

    // unsigned int
    unsigned int valueUnsignedInt = 0;
    if SUCCEEDED(spMemberFrom->getValue(valueUnsignedInt))
      this->setValue(valueUnsignedInt);

    // CATBoolean
    CATBoolean catBoolean = FALSE;
    if SUCCEEDED(spMemberFrom->getValue(catBoolean))
      this->setValue(catBoolean);

    // CATUnicodeString
    CATUnicodeString unicodeString;
    if SUCCEEDED(spMemberFrom->getValue(unicodeString))
      this->setValue(unicodeString);

    // CATUString
    CATString catString;
    if SUCCEEDED(spMemberFrom->getValue(catString))
      this->setValue(catString);

    // CATBaseUnknown
    CATBaseUnknown_var spUnknown = spMemberFrom->getUnknown();
    this->setUnknown(spUnknown);

    // CATListValCATBaseUnknown_var 
    CATListValCATBaseUnknown_var listUnknown;
    if SUCCEEDED(spMemberFrom->getValue(listUnknown))
      this->setValue(listUnknown);

    // CATDialog*
    CATDialog* pDlg = spMemberFrom->getDlg();
    this->setDlg(pDlg);

    // unsigned long
    unsigned long unsignedLong = 0;
    if SUCCEEDED(spMemberFrom->getValue(unsignedLong))
      this->setValue(unsignedLong);

    // CATLISTP(CATCell)
    CATLISTP(CATCell) listCATCell;
    if SUCCEEDED(spMemberFrom->getValue(listCATCell))
      this->setValue(listCATCell);

    // CATMathVector
    CATMathVector mathVector;
    if SUCCEEDED(spMemberFrom->getValue(mathVector))
      this->setValue(mathVector);

    // CATMathPoint
    CATMathPoint mathPoint;
    if SUCCEEDED(spMemberFrom->getValue(mathPoint))
      this->setValue(mathPoint);

    // CATLISTV(CATMathPoint)
    CATLISTV(CATMathPoint) listCATMathPoint;
    if SUCCEEDED(spMemberFrom->getValue(listCATMathPoint))
      this->setValue(listCATMathPoint);

    // CATLISTV(CATMathVector)
    CATLISTV(CATMathVector) listCATMathVector;
    if SUCCEEDED(spMemberFrom->getValue(listCATMathVector))
      this->setValue(listCATMathVector);

    // CATLISTV(CATMathPlane)
    CATLISTV(CATMathPlane) listCATMathPlane;
    if SUCCEEDED(spMemberFrom->getValue(listCATMathPlane))
      this->setValue(listCATMathPlane);

    // CATListOfCATUnicodeString
    CATListOfCATUnicodeString listCATUnicodeString;
    if SUCCEEDED(spMemberFrom->getValue(listCATUnicodeString))
      this->setValue(listCATUnicodeString);

    // CATListOfDouble
    CATListOfDouble listOfDouble;
    if SUCCEEDED(spMemberFrom->getValue(listOfDouble))
      this->setValue(listOfDouble);

    // CATListOfInt
    CATListOfInt listOfInt;
    if SUCCEEDED(spMemberFrom->getValue(listOfInt))
      this->setValue(listOfInt);

    // IID
    IID valueIID;
    if SUCCEEDED(spMemberFrom->getValue(valueIID))
      this->setValue(valueIID);

    // CATPathElement
    CATPathElement  pathElement;
    if SUCCEEDED(spMemberFrom->getValue(pathElement))
      this->setValue(pathElement);

    // CATMathPlane
    CATMathPlane  mathPlane;
    if SUCCEEDED(spMemberFrom->getValue(mathPlane))
      this->setValue(mathPlane);

    // CATDocument
    CATDocument* pDocument = NULL;
    if SUCCEEDED(spMemberFrom->getValue(pDocument))
      this->setValue(pDocument);

    hr = S_OK;
  }
  return hr;
} // copyValuesFrom

//-----------------------------------------------------------------------------
// setDlg
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::setDlg(CATDialog* i_pValue)
{
  m_pDlg = i_pValue;
  return S_OK;
} // setDlg

//-----------------------------------------------------------------------------
// getDlg
//-----------------------------------------------------------------------------
CATDialog* TCAEUTLDoItMember::getDlg(void)
{
  return m_pDlg;
} // getDlg

//-----------------------------------------------------------------------------
// CATBaseUnknown_var
//-----------------------------------------------------------------------------
CATBaseUnknown_var TCAEUTLDoItMember::getUnknown(void)
{
  return m_spUnknown;
}
HRESULT TCAEUTLDoItMember::setUnknown(CATBaseUnknown_var i_spValue)
{
  m_spUnknown = i_spValue;
  m_spUnknown_set = TRUE;
  return S_OK;
} // CATBaseUnknown_var 

//-----------------------------------------------------------------------------
// int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(int& o_rValue)
{
  o_rValue = m_Int;
  return m_Int_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const int& i_rValue)
{
  m_Int = i_rValue;
  m_Int_set = TRUE;
  return S_OK;
} // int  

//-----------------------------------------------------------------------------
// const int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(unsigned int& o_rValue)
{
  o_rValue = m_UnsignedInt;
  return m_UnsignedInt_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const unsigned int& i_rValue)
{
  m_UnsignedInt = i_rValue;
  m_UnsignedInt_set = TRUE;
  return S_OK;
} // int  

//-----------------------------------------------------------------------------
// CATBoolean
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATBoolean& o_rValue)
{
  o_rValue = m_Boolean;
  return m_Boolean_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATBoolean& i_rValue)
{
  m_Boolean = i_rValue;
  m_Boolean_set = TRUE;
  return S_OK;
} // CATBoolean

//-----------------------------------------------------------------------------
// CATString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATString& o_rValue)
{
  o_rValue = m_CatStr;
  return m_CatStr_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATString& i_rValue)
{
  m_CatStr = i_rValue;
  m_CatStr_set = TRUE;
  return S_OK;
} // CATString 

//-----------------------------------------------------------------------------
// CATUnicodeString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATUnicodeString& o_rValue)
{
  o_rValue = m_UnicodeStr;
  return m_UnicodeStr_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATUnicodeString& i_rValue)
{
  m_UnicodeStr = i_rValue;
  m_UnicodeStr_set = TRUE;
  return S_OK;
} // CATUnicodeString 

//-----------------------------------------------------------------------------
// CATListValCATBaseUnknown_var
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATListValCATBaseUnknown_var& o_rListValue)
{
  o_rListValue = m_ListUnknown;
  return m_ListUnknown_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATListValCATBaseUnknown_var& i_rListValue)
{
  m_ListUnknown = i_rListValue;
  m_ListUnknown_set = TRUE;
  return S_OK;
} // CATListValCATBaseUnknown_var 

//-----------------------------------------------------------------------------
// unsigned long
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(unsigned long& o_rValue)
{
  o_rValue = m_UnsignedLong;
  return m_UnsignedLong_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const unsigned long& i_rValue)
{
  m_UnsignedLong = i_rValue;
  m_UnsignedLong_set = TRUE;
  return S_OK;
} // unsigned long

//-----------------------------------------------------------------------------
// CATLISTP(CATCell)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATLISTP(CATCell)& o_rValue)
{
  o_rValue = m_ListOfCATCell;
  return m_ListOfCATCell_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATLISTP(CATCell)& i_rValue)
{
  m_ListOfCATCell = i_rValue;
  m_ListOfCATCell_set = TRUE;
  return S_OK;
} //CATLISTP(CATCell) 

//-----------------------------------------------------------------------------
// CATMathVector
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATMathVector& o_rValue)
{
  o_rValue = m_CATMathVector;
  return m_CATMathVector_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATMathVector& i_rValue)
{
  m_CATMathVector = i_rValue;
  m_CATMathVector_set = TRUE;
  return S_OK;
} //CATMathVector 

//-----------------------------------------------------------------------------
// CATMathPoint
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATMathPoint& o_rValue)
{
  o_rValue = m_CATMathPoint;
  return m_CATMathPoint_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATMathPoint& i_rValue)
{
  m_CATMathPoint = i_rValue;
  m_CATMathPoint_set = TRUE;
  return S_OK;
} //CATMathPoint 

//-----------------------------------------------------------------------------
// CATLISTV(CATMathPoint)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATLISTV(CATMathPoint)& o_rValue)
{
  o_rValue = m_ListOfCATMathPoint;
  return m_ListOfCATMathPoint_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATLISTV(CATMathPoint)& i_rValue)
{
  m_ListOfCATMathPoint = i_rValue;
  m_ListOfCATMathPoint_set = TRUE;
  return S_OK;
} //CATLISTV(CATMathPoint) 

//-----------------------------------------------------------------------------
// CATLISTV(CATMathVector)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATLISTV(CATMathVector)& o_rValue)
{
  o_rValue = m_ListOfCATMathVector;
  return m_ListOfCATMathVector_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATLISTV(CATMathVector)& i_rValue)
{
  m_ListOfCATMathVector = i_rValue;
  m_ListOfCATMathVector_set = TRUE;
  return S_OK;
} //CATLISTV(CATMathVector) 

//-----------------------------------------------------------------------------
// CATLISTV(CATMathPlane)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATLISTV(CATMathPlane)& o_rValue)
{
  o_rValue = m_ListOfCATMathPlane;
  return m_ListOfCATMathPlane_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATLISTV(CATMathPlane)& i_rValue)
{
  m_ListOfCATMathPlane = i_rValue;
  m_ListOfCATMathPlane_set = TRUE;
  return S_OK;
} //CATLISTV(CATMathPlane) 

//-----------------------------------------------------------------------------
// CATListOfCATUnicodeString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATListOfCATUnicodeString& o_rValue)
{
  o_rValue = m_ListOfUnicodeString;
  return m_ListOfUnicodeString_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATListOfCATUnicodeString& i_rValue)
{
  m_ListOfUnicodeString = i_rValue;
  m_ListOfUnicodeString_set = TRUE;
  return S_OK;
} //CATListOfCATUnicodeString 

//-----------------------------------------------------------------------------
// CATListOfDouble
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATListOfDouble& o_rValue)
{
  o_rValue = m_ListOfDouble;
  return m_ListOfDouble_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATListOfDouble& i_rValue)
{
  m_ListOfDouble = i_rValue;
  m_ListOfDouble_set = TRUE;
  return S_OK;
} //CATListOfDouble 

//-----------------------------------------------------------------------------
// CATListOfDouble
//----------------------------------------------------------------------------- 
CATListOfDouble& TCAEUTLDoItMember::getIOValue(void)
{
  return m_ListOfDoubleIO;
}

//-----------------------------------------------------------------------------
// CATListOfInt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATListOfInt& o_rValue)
{
  o_rValue = m_ListOfInt;
  return m_ListOfInt_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATListOfInt& i_rValue)
{
  m_ListOfInt = i_rValue;
  m_ListOfInt_set = TRUE;
  return S_OK;
} //CATListOfInt 

//-----------------------------------------------------------------------------
// IID
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(IID& o_rValue)
{
  o_rValue = m_IID;
  return m_IID_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const IID& i_rValue)
{
  m_IID = i_rValue;
  m_IID_set = TRUE;
  return S_OK;
} //IID

//-----------------------------------------------------------------------------
// CATPathElement
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATPathElement& o_rValue)
{
  o_rValue = m_CATPathElement;
  return m_CATPathElement_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATPathElement& i_rValue)
{
  m_CATPathElement = i_rValue;
  m_CATPathElement_set = TRUE;
  return S_OK;
} //CATPathElement

//-----------------------------------------------------------------------------
// CATMathPlane
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATMathPlane& o_rValue)
{
  o_rValue = m_CATMathPlane;
  return m_CATMathPlane_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const CATMathPlane& i_rValue)
{
  m_CATMathPlane = i_rValue;
  m_CATMathPlane_set = TRUE;
  return S_OK;
} //CATMathPlane

//-----------------------------------------------------------------------------
// CATDocument*
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(CATDocument*& o_rpValue)
{
  o_rpValue = m_pDocument;
  return m_pDocument_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(CATDocument*& i_rpValue)
{
  m_pDocument = i_rpValue;
  m_pDocument_set = TRUE;
  return S_OK;
} //CATDocument* 

//-----------------------------------------------------------------------------
// double
//-----------------------------------------------------------------------------
HRESULT TCAEUTLDoItMember::getValue(double& o_rValue)
{
  o_rValue = m_Double;
  return m_Double_set ? S_OK : E_FAIL;
}
HRESULT TCAEUTLDoItMember::setValue(const double& i_rValue)
{
  if( i_rValue != i_rValue )
  {
    cerr << __FUNCTION__ << " ERROR: \t" << i_rValue << endl;
  }
  m_Double = i_rValue;
  m_Double_set = TRUE;
  return S_OK;
} //double

