// COPYRIGHT Dassault Systemes 2013
//===================================================================
//
// TCAUTLListAttrDlg.h
// The dialog : TCAUTLListAttrDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jan 2013  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAUTLListAttrDlg_H
#define TCAUTLListAttrDlg_H

#include "TCAUTLListDocsMD.h"
#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class ExportedByTCAUTLListDocsMD TCAUTLListAttrDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TCAUTLListAttrDlg, CATDlgDialog )

  public:

  TCAUTLListAttrDlg();
  virtual ~TCAUTLListAttrDlg();

  void Build ();


  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
