//===================================================================
// COPYRIGHT  2023.09.19
//===================================================================
// TCAVTATestSrcCode.cpp
// Header definition of class TCAVTATestSrcCode
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023.09.19 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByTCAVTATestSrcCode_H
#define ExportedByTCAVTATestSrcCode_H
#if defined(__TCAVTATestSrcCode)
# define ExportedByTCAVTATestSrcCode   DSYExport
#else // __TCAVTATestSrcCode
# define ExportedByTCAVTATestSrcCode   DSYImport
#endif  // __TCAVTATestSrcCode
#include "DSYExport.h"
#endif //ExportedByTCAVTATestSrcCode_H

