//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAIUTLGo.cpp
// Header definition of class TCAIUTLGo
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "TCAIUTLGo.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_TCAIUTLGo = {0xe6ce94a9,0x69a7,0x4802,{ 0x86,0xaa,0x96,0x0a,0xc5,0x82,0xad,0x1b}};
#endif

CATImplementInterface(TCAIUTLGo, CATBaseUnknown);
CATImplementHandler(TCAIUTLGo, CATBaseUnknown);
