// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module TCADRTXmlMD
#======================================================================
#  2023.03.20 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP ApplicationFrame CATAfrUUID  TCAUTLDoItMD \
TCAUTLItfCPP TCAUTLItf TCAUTLInterfacesUUID DI0PANV2 CATApplicationFrame 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATObjectModelerBase CATObjectSpecsModeler DI0PANV2 CATProductStructure1 KnowledgeItf CATMecModInterfaces CATGMGeometricInterfaces \
CATGMModelInterfaces CATMecModInterfaces CATMechanicalModeler CATDraftingInterfaces CATXMLParserItf WFTOCACD CATVisualization YN000MFL  SELECT

