// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLDoItMember.h
// Provide implementation to interface
//    TCAIUTLDoItMember

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	UTLDoItMember
//EXTENSIONTYPE:	DataExtension

//    TIE: TCAIUTLDoItMember

//End CAA2 Wizard Generation Report
//
//  May 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLDoItMember_H
#define TCAEUTLDoItMember_H

#include "TCAUTLComponentMacro.h" 
#include "TCAXmlUtils.h" 
#include "CATMathVector.h"
#include "CATMathPlane.h"
#include "CATPathElement.h"
#include "CATLISTV_CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATDocument.h" 
#include "CATDialog.h" 
#include "CATListOfDouble.h"
#include "CATUnicodeString.h"
#include "CATListOfCATCells.h"
#include "CATLISTV_CATMathPoint.h"
#include "CATLISTV_CATMathVector.h"
#include "CATLISTV_CATMathPlane.h"

TCA_UTL_COMPONENT_H(UTLDoItMember) 

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TCAIUTLDoItMember
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLDoItMember : public CATBaseUnknown

{
  CATDeclareClass;

private:

  CATBoolean m_Name_set;
  CATBoolean m_Int_set;
  CATBoolean m_Double_set;
  CATBoolean m_UnsignedInt_set;
  CATBoolean m_Boolean_set;
  CATBoolean m_CatStr_set;
  CATBoolean m_UnicodeStr_set;
  CATBoolean m_ListOfUnicodeString_set;
  CATBoolean m_ListOfCATString_set;
  CATBoolean m_ListOfDouble_set;
  CATBoolean m_ListOfDoubleIO_set;
  CATBoolean m_ListOfInt_set;
  CATBoolean m_pDlg_set;
  CATBoolean m_spUnknown_set;
  CATBoolean m_ListUnknown_set;
  CATBoolean m_UnsignedLong_set;
  CATBoolean m_IID_set;
  CATBoolean m_PWPParam_set;
  CATBoolean m_PWPProcessSettings_set;
  CATBoolean m_pDocument_set;
  CATBoolean m_CATPathElement_set;
  CATBoolean m_CATMathPlane_set;
  CATBoolean m_ListOfCATCell_set;
  CATBoolean m_ListOfCATMathPoint_set;
  CATBoolean m_ListOfCATMathVector_set;
  CATBoolean m_ListOfCATMathPlane_set;
  CATBoolean m_CATMathPoint_set;
  CATBoolean m_CATMathVector_set;

  CATUnicodeString m_FuncName;
  CATListOfInt     m_FuncList;

  CATUnicodeString    m_Name;
  int                 m_Int;
  double              m_Double;
  unsigned int        m_UnsignedInt;
  CATBoolean          m_Boolean;
  CATString           m_CatStr;
  CATUnicodeString    m_UnicodeStr;

  CATListOfCATUnicodeString  m_ListOfUnicodeString;
  CATLISTP(CATCell)          m_ListOfCATCell;
  CATLISTV(CATMathPoint)     m_ListOfCATMathPoint;
  CATLISTV(CATMathVector)    m_ListOfCATMathVector;
  CATLISTV(CATMathPlane)    m_ListOfCATMathPlane;
  CATMathPoint               m_CATMathPoint;
  CATMathVector              m_CATMathVector;

  CATListOfDouble m_ListOfDouble;
  CATListOfDouble m_ListOfDoubleIO;

  CATListOfInt    m_ListOfInt;

  CATDialog* m_pDlg;
  CATBaseUnknown_var  m_spUnknown;
  CATListValCATBaseUnknown_var m_ListUnknown;

  unsigned long m_UnsignedLong;

  IID m_IID;

  CATPathElement m_CATPathElement;

  CATMathPlane m_CATMathPlane;

  CATDocument* m_pDocument;

public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
  TCAEUTLDoItMember ();
  virtual ~TCAEUTLDoItMember ();

  // dump
  virtual void dump(void);

  // copy all values from othe member
  virtual HRESULT copyValuesFrom(CATBaseUnknown_var i_spMemberFrom);

  // name
  virtual HRESULT setName(const CATUnicodeString& i_rName);
  virtual HRESULT getName(CATUnicodeString& o_rName);

  // trace
  virtual void trace(void);

  // Dlg
  virtual HRESULT setDlg(CATDialog* i_pValue);
  virtual CATDialog* getDlg(void);

  // CATBaseUnknown
  virtual HRESULT setUnknown(CATBaseUnknown_var i_spValue);
  virtual CATBaseUnknown_var getUnknown(void);

  // int
  virtual HRESULT setValue(const int& i_rValue);
  virtual HRESULT getValue(int& o_rValue);

  // double
  virtual HRESULT setValue(const double& i_rValue);
  virtual HRESULT getValue(double& o_rValue);

  // unsigned int 
  virtual HRESULT setValue(const unsigned int& i_rValue);
  virtual HRESULT getValue(unsigned int& o_rValue);

  // CATBoolean 
  virtual HRESULT setValue(const CATBoolean& i_rValue);
  virtual HRESULT getValue(CATBoolean& o_rValue);

  // CATString
  virtual HRESULT setValue(const CATString& i_rValue);
  virtual HRESULT getValue(CATString& o_rValue);

  // CATUnicodeString
  virtual HRESULT setValue(const CATUnicodeString& i_rValue);
  virtual HRESULT getValue(CATUnicodeString& o_rValue);

  // CATListValCATBaseUnknown_var 
  virtual HRESULT getValue(CATListValCATBaseUnknown_var& o_rListValue);
  virtual HRESULT setValue(const CATListValCATBaseUnknown_var& i_rListValue);

  // CATLISTP(CATCell) 
  virtual HRESULT getValue(CATLISTP(CATCell)&       o_rListValue);
  virtual HRESULT setValue(const CATLISTP(CATCell)& i_rListValue);

  // CATMathVector 
  virtual HRESULT getValue(CATMathVector&       o_rValue);
  virtual HRESULT setValue(const CATMathVector& i_rValue);

  // CATMathPoint 
  virtual HRESULT getValue(CATMathPoint&       o_rListValue);
  virtual HRESULT setValue(const CATMathPoint& i_rListValue);

  // CATLISTV(CATMathPoint) 
  virtual HRESULT getValue(CATLISTV(CATMathPoint)&       o_rListValue);
  virtual HRESULT setValue(const CATLISTV(CATMathPoint)& i_rListValue);

  // CATLISTV(CATMathVector) 
  virtual HRESULT getValue(CATLISTV(CATMathVector)&       o_rListValue);
  virtual HRESULT setValue(const CATLISTV(CATMathVector)& i_rListValue);

  // CATListOfCATUnicodeString 
  virtual HRESULT getValue(CATListOfCATUnicodeString&       o_rListValue);
  virtual HRESULT setValue(const CATListOfCATUnicodeString& i_rListValue);

  // CATLISTV(CATMathPlane) 
  virtual HRESULT getValue(CATLISTV(CATMathPlane)&       o_rListValue);
  virtual HRESULT setValue(const CATLISTV(CATMathPlane)& i_rListValue);

  // CATListOfDouble 
  virtual HRESULT getValue(CATListOfDouble&       o_rListValue);
  virtual HRESULT setValue(const CATListOfDouble& i_rListValue);

  virtual CATListOfDouble& getIOValue(void); 

  // CATListOfInt 
  virtual HRESULT getValue(CATListOfInt&       o_rListValue);
  virtual HRESULT setValue(const CATListOfInt& i_rListValue);

  // unsigned long
  virtual HRESULT getValue(unsigned long& o_rValue);
  virtual HRESULT setValue(const unsigned long& i_rValue);

  // IID 
  virtual HRESULT getValue(IID& o_rValue);
  virtual HRESULT setValue(const IID& i_rValue);

  // CATPathElement 
  virtual HRESULT getValue(CATPathElement& o_rValue);
  virtual HRESULT setValue(const CATPathElement& i_rValue);

  // CATMathPlane 
  virtual HRESULT getValue(CATMathPlane& o_rValue);
  virtual HRESULT setValue(const CATMathPlane& i_rValue);

  // CATDocument*
  virtual HRESULT getValue(CATDocument*& o_rpValue);
  virtual HRESULT setValue(CATDocument*& i_rpValue);


private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TCAEUTLDoItMember (TCAEUTLDoItMember &);
  TCAEUTLDoItMember& operator=(TCAEUTLDoItMember&);

};

//-----------------------------------------------------------------------

#endif
