// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoMeasureFenderChargingFlap.h
// Provide implementation to interface
//    TCAIUTLDoIt

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	UTLGoMeasureFenderChargingFlap
//EXTENSIONTYPE:	DataExtension

//    TIE: TCAIUTLDoIt

//End CAA2 Wizard Generation Report
//
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLGoMeasureFenderChargingFlap_H
#define TCAEUTLGoMeasureFenderChargingFlap_H

#include "TCAXmlUtils.h"
#include "TCAIUTLGo.h"
#include "CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATUnicodeString.h"
#include "TCAUTLComponentMacro.h"
#include "fstream.h" 
#include "CATISpecAttrAccess.h"
#include "CATISpecAttrKey.h"

TCA_UTL_COMPONENT_H(UTLGoMeasureFenderChargingFlap)
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TCAIUTLDoIt
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLGoMeasureFenderChargingFlap : public CATBaseUnknown

{
  CATDeclareClass;

private:

  TCAIUTLGo_var m_spThis;
  TCAIUTLGo_var m_spSingleTon;
  CATISpecObject_var m_spSpecPbject;

public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
  TCAEUTLGoMeasureFenderChargingFlap();
  virtual ~TCAEUTLGoMeasureFenderChargingFlap();

  /**
  * Implements a function from an interface.
  * @href TCAIUTLDoIt#doIt
  */
  virtual HRESULT doIt(void);
  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);


private:

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TCAEUTLGoMeasureFenderChargingFlap(TCAEUTLGoMeasureFenderChargingFlap&);
  TCAEUTLGoMeasureFenderChargingFlap& operator=(TCAEUTLGoMeasureFenderChargingFlap&);

};

//-----------------------------------------------------------------------

#endif
