
//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGoItem.cpp
// Header definition of class TCAEUTLGoItem
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TCAEUTLGoItem_H
#define TCAEUTLGoItem_H

#include "TCAUTLComponentMacro.h" 
#include "CATUnicodeString.h"

TCA_UTL_COMPONENT_H(UTLGoItem)

//-----------------------------------------------------------------------

class TCAEUTLGoItem : public CATBaseUnknown

{
  CATDeclareClass;

public:

  // Standard constructors and destructors
  // -------------------------------------
  TCAEUTLGoItem();
  virtual ~TCAEUTLGoItem();

  virtual HRESULT doIt(void);

  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);

private:

  // Copy constructor and equal operator
  // -----------------------------------
  TCAEUTLGoItem(TCAEUTLGoItem&);
  TCAEUTLGoItem& operator=(TCAEUTLGoItem&);
};

//-----------------------------------------------------------------------

#endif

