// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoExportJSON.h
// Provide implementation to interface
//    TCAIUTLDoIt

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	UTLGoExportJSON
//EXTENSIONTYPE:	DataExtension

//    TIE: TCAIUTLDoIt

//End CAA2 Wizard Generation Report
//
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLGoExportJSON_H
#define TCAEUTLGoExportJSON_H

#include "TCAXmlUtils.h"
#include "TCAIUTLGo.h"
#include "CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATUnicodeString.h"
#include "TCAUTLComponentMacro.h"
#include "fstream.h" 
#include "CATISpecAttrAccess.h"
#include "CATISpecAttrKey.h"

TCA_UTL_COMPONENT_H(UTLGoExportJSON)
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TCAIUTLDoIt
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLGoExportJSON : public CATBaseUnknown

{
  CATDeclareClass;

private:

  TCAIUTLGo_var m_spRootItem;

  CATUnicodeString m_FuncName;
  CATListOfInt     m_FuncList;

  CATUnicodeString m_RootDocName;
  CATUnicodeString m_RootDocDir;

  CATDocument* m_pRootDoc;
  CATListOfCATUnicodeString m_InstNames;

  CATListOfCATUnicodeString m_ListModels;
  CATListOfCATUnicodeString m_ListSubDir;

  CATListOfCATUnicodeString m_Lines;

  CATUnicodeString  m_FileName;

  CATListValCATBaseUnknown_var m_Items;

public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
  TCAEUTLGoExportJSON();
  virtual ~TCAEUTLGoExportJSON();

  /**
  * Implements a function from an interface.
  * @href TCAIUTLDoIt#doIt
  */
  virtual HRESULT doIt(void);
  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);


private:

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TCAEUTLGoExportJSON(TCAEUTLGoExportJSON&);
  TCAEUTLGoExportJSON& operator=(TCAEUTLGoExportJSON&);

  TCAIUTLGo_var newItem(void);

  void addItem(TCAIUTLGo_var i_spParent, const CATUnicodeString& i_rKey, TCAIUTLGo_var i_spItem);
  void addItems(TCAIUTLGo_var i_spParent, const CATUnicodeString& i_rKey, const CATListValCATBaseUnknown_var& i_rItems);
  void addValue(TCAIUTLGo_var i_spItem, const CATUnicodeString& i_rKey, const CATUnicodeString& i_rValue);

  void addLine(TCAIUTLGo_var i_spItem, const CATUnicodeString& i_rKey, const CATUnicodeString& i_rValue);

  TCAIUTLGo_var getItemOfDocument(CATDocument* i_pDoc);
  TCAIUTLGo_var getItemOfContainer(CATIContainer_var i_spContainer);
  TCAIUTLGo_var getItemOfSpec(CATBaseUnknown_var i_spSpec);
  TCAIUTLGo_var getItemOfAttr(CATISpecAttrAccess_var i_spAttrAccess, CATISpecAttrKey_var i_spAttrKey);

  void getInterfacesItemsOf(CATBaseUnknown_var i_spSpec, CATListValCATBaseUnknown_var& o_rItems);

  void writeJSON(TCAIUTLGo_var i_spItem, const CATUnicodeString& i_rKey = "", int i_Level = 0);

};

//-----------------------------------------------------------------------

#endif
