
//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGoGSMBiDim.cpp
// Header definition of class TCAEUTLGoGSMBiDim
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef TCAEUTLGoGSMBiDim_H
#define TCAEUTLGoGSMBiDim_H

#include "TCAUTLComponentMacro.h" 
#include "CATUnicodeString.h"
#include "CATBody.h"
#include "CATMathPoint.h"
#include "CATISpecObject.h"
#include "CATIDatumFactory.h"
#include "CATGeoFactory.h"
#include "CATFace.h" 
#include "CATSurface.h" 
#include "CATListOfDouble.h" 
#include "CATPoint.h" 
#include "TCAIUTLGo.h" 

TCA_UTL_COMPONENT_H(UTLGoGSMBiDim)

//-----------------------------------------------------------------------

class TCAEUTLGoGSMBiDim : public CATBaseUnknown

{
  CATDeclareClass;

private:

  int m_CountPoints;

  CATGeoFactory_var    m_spGeoFactory;
  CATIDatumFactory_var m_spDatumFactory;

  CATUnicodeString m_Alias;

  TCAIUTLGo_var m_spThis;

public:

  // Standard constructors and destructors
  // -------------------------------------
  TCAEUTLGoGSMBiDim();
  virtual ~TCAEUTLGoGSMBiDim();

  virtual HRESULT doIt(void);

  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);

private:


  void getPointsCloud(CATBody_var i_spBody, CATUnicodeString& o_rCoordinates);

  HRESULT  getDistanceMinTopo(CATGeoFactory_var i_spGeoFactory,
                              CATBody_var i_spCATBody1,
                              CATBody_var i_spCATBody2,
                              double& o_rMinDistance,
                              CATUnicodeString& o_rErrMsg);

  CATBody_var createTopProjection(CATGeoFactory_var i_spGeoFactory,
                                  CATBody_var i_spBodySupport,
                                  CATBody_var i_spBodyToProj,
                                  CATUnicodeString& o_rErrMsg);


  HRESULT getParamFromLengthOnCATCurve(CATCurve_var i_spCurve, CATCrvParam i_startParam, double i_lengthOnCurve, CATCrvParam& o_rCrvParam);

  HRESULT  getLengthOfCATCurve(CATCurve_var i_spCurve, double& o_rLength);

  HRESULT getDistanceOfCATMathPointToSurf(CATGeoFactory_var i_spGeoFactory,
                                          CATBody_var i_spCATBodySur,
                                          CATMathPoint i_mathPt,
                                          CATBoolean i_ifProjectable,
                                          double& o_rDist,
                                          CATUnicodeString& o_rErrMsg);

  HRESULT createGeomProjection(CATGeoFactory_var i_spGeoFactory,
                               CATPoint_var i_spPoint,
                               CATSurface_var i_spSurface,
                               CATSurLimits i_useSurLimits,
                               double& o_distance,
                               CATSurParam& o_surParam,
                               CATUnicodeString& o_rErrMsg);

  CATLONG32 getCellsHighestDimension(CATBody_var i_spBody);

  CATPoint_var getCATPointOfBody(CATBody_var i_spBody);

  CATBody_var createTopPoint(CATGeoFactory_var i_spGeoFactory,
                             CATMathPoint i_mathPoint);

  HRESULT getPointsOnCATCurveWithConstDist(CATCurve_var i_spCurve,
                                           double i_distance,
                                           CATListOfDouble& o_rListXCoord,
                                           CATListOfDouble& o_rListYCoord,
                                           CATListOfDouble& o_rListZCoord);

  HRESULT getPointsOnSurfInUVDirWithConstDist(CATBody_var i_spBodySurf,
                                              double i_distanceU,
                                              double i_distanceV,
                                              CATListOfDouble& o_rListXCoord,
                                              CATListOfDouble& o_rListYCoord,
                                              CATListOfDouble& o_rListZCoord);

  HRESULT getPointsOnFaceInUVDirWithConstDist(CATBody_var i_spBodySurf,
                                              int i_indexDomain,
                                              int i_indexCell,
                                              double i_distanceU,
                                              double i_distanceV,
                                              CATListOfDouble& o_rListXCoord,
                                              CATListOfDouble& o_rListYCoord,
                                              CATListOfDouble& o_rListZCoord);
  void initFactories(void);

  CATISpecObject_var createDatumPoint(const CATMathPoint& i_rPnt1);

  void tessBody(CATBody_var i_spBody, CATUnicodeString& o_rCoordinates);

  // Copy constructor and equal operator
  // -----------------------------------
  TCAEUTLGoGSMBiDim(TCAEUTLGoGSMBiDim&);
  TCAEUTLGoGSMBiDim& operator=(TCAEUTLGoGSMBiDim&);
};

//-----------------------------------------------------------------------

#endif

