// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGo3DPlane.h
// Provide implementation to interface
//    TCAIUTLDoIt

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	UTLGo3DPlane
//EXTENSIONTYPE:	DataExtension

//    TIE: TCAIUTLDoIt

//End CAA2 Wizard Generation Report
//
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLGo3DPlane_H
#define TCAEUTLGo3DPlane_H

#include "TCAXmlUtils.h"
#include "TCAIUTLGo.h"
#include "CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATUnicodeString.h"
#include "TCAUTLComponentMacro.h"
#include "fstream.h" 
#include "CATISpecAttrAccess.h"
#include "CATISpecAttrKey.h"

TCA_UTL_COMPONENT_H(UTLGo3DPlane)
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TCAIUTLDoIt
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLGo3DPlane : public CATBaseUnknown

{
  CATDeclareClass;

private:

  TCAIUTLGo_var m_spThis;
  TCAIUTLGo_var m_spSingleTon;

public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
  TCAEUTLGo3DPlane();
  virtual ~TCAEUTLGo3DPlane();

  /**
  * Implements a function from an interface.
  * @href TCAIUTLDoIt#doIt
  */
  virtual HRESULT doIt(void);
  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);


private:

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TCAEUTLGo3DPlane(TCAEUTLGo3DPlane&);
  TCAEUTLGo3DPlane& operator=(TCAEUTLGo3DPlane&);

};

//-----------------------------------------------------------------------

#endif
