// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGo3DPoint.h
// Provide implementation to interface
//    TCAIUTLDoIt

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	UTLGo3DPoint
//EXTENSIONTYPE:	DataExtension

//    TIE: TCAIUTLDoIt

//End CAA2 Wizard Generation Report
//
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLGo3DPoint_H
#define TCAEUTLGo3DPoint_H

#include "TCAXmlUtils.h"
#include "TCAIUTLGo.h"
#include "CATBaseUnknown.h" 
#include "CATListOfInt.h"
#include "CATUnicodeString.h"
#include "TCAUTLComponentMacro.h"
#include "fstream.h" 
#include "CATISpecAttrAccess.h"
#include "CATISpecAttrKey.h"

TCA_UTL_COMPONENT_H(UTLGo3DPoint)
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TCAIUTLDoIt
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLGo3DPoint : public CATBaseUnknown

{
  CATDeclareClass;

private:

  TCAIUTLGo_var m_spThis;
  TCAIUTLGo_var m_spSingleTon;

public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
  TCAEUTLGo3DPoint();
  virtual ~TCAEUTLGo3DPoint();

  /**
  * Implements a function from an interface.
  * @href TCAIUTLDoIt#doIt
  */
  virtual HRESULT doIt(void);
  virtual HRESULT getInfo(CATUnicodeString& o_rInfo);

  /**
 * Sets an alias to the object.
 * @param iName
 *         alias to associate to the object.
 */
  virtual void SetAlias(const CATUnicodeString& iName);

  /**
 * Returns alias of the object.
 */
  virtual CATUnicodeString GetAlias(void);

  virtual CATListValCATBaseUnknown_var* GetChildren(void);

  virtual CATListValCATUnicodeString* GetIdentificators(void);

private:

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TCAEUTLGo3DPoint(TCAEUTLGo3DPoint&);
  TCAEUTLGo3DPoint& operator=(TCAEUTLGo3DPoint&);

};

//-----------------------------------------------------------------------

#endif
