// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module TCAUTLDoItMD
#======================================================================
#  2025.08.04 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP TCAUTLItfCPP TCAUTLItf TCAUTLInterfacesUUID TCADRTXmlMD CATApplicationFrame \
									CATIAApplicationFrame \
									CATAssemblyInterfaces \
									CATMechanicalModelerUI \
									CATMmuCommands \
									CATDialogEngine \
									CATObjectModelerBase \
									CATObjectSpecsModeler \
									CATVisualization \
									CATProductStructure1  \
									CATInteractiveInterfaces \
									CATMecModInterfaces \
									CATConstraintModeler \
									KnowledgeItf \
									CATConstraintModelerUI \
									CATConstraintModelerItf \
									CATViz DI0PANV2  \
									CATMechanicalModeler \
									CATMathematics \
									CATMeasureGeometryInterfaces \
									CATGMGeometricInterfaces \
									CATGMModelInterfaces \
									CATSketcherUseItf \
									CATAutoItf TessAPI CATGitInterfaces \
									BasicTopology CATCGMGeoMath Y300IINT

# END WIZARD EDITION ZONE

OS = Windows_NT 
LOCAL_CCFLAGS = -I"C:\Users\wady01\AppData\Local\anaconda3\include"
LOCAL_LDFLAGS = /LIBPATH:"C:\Users\wady01\AppData\Local\anaconda3\libs" \