// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module TCAListSpecAttr
#======================================================================
#  2023.03.20 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=LOAD MODULE
  
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP ApplicationFrame CATAfrUUID  \
DI0PANV2 CATApplicationFrame CATInstantCollabDesignItf CATTPSItfCPP CATInteractiveInterfaces 
# END WIZARD EDITION ZONE 

LINK_WITH = $(WIZARD_LINK_MODULES) CATObjectModelerBase CATObjectSpecsModeler DI0PANV2 CATProductStructure1 KnowledgeItf CATMecModInterfaces CATGMGeometricInterfaces \
CATGMModelInterfaces CATMecModInterfaces CATMechanicalModeler CATDraftingInterfaces TCADRTXmlMD DraftingItfCPP CATMathematics TCAUTLDoItMD \
TCAUTLItfCPP TCAUTLItf TCAUTLInterfacesUUID  CATVisualization CATPrint  

# LOCAL_CCFLAGS = -I"C:\Users\wady01\AppData\Local\Programs\Python\Python39\Lib\site-packages\tensorflow\include\external\local_config_python\python_include"
# LOCAL_LDFLAGS = /LIBPATH:"C:\Users\wady01\AppData\Local\Programs\Python\Python39\libs" \

LOCAL_CCFLAGS = -I"C:\Users\wady01\AppData\Local\anaconda3\include"
LOCAL_LDFLAGS = /LIBPATH:"C:\Users\wady01\AppData\Local\anaconda3\libs" \

