// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// TCAUTLListDocsCmd.h
// The command: TCAUTLListDocsCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   COMMAND
//End CAA2 Wizard Generation Report
//
//  Dec 2012  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAUTLListDocsCmd_H
#define TCAUTLListDocsCmd_H

#include "CATCommand.h"
#include "CATISpecObject.h"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of System framework.
 * (consult base class description).
 */
class TCAUTLListDocsCmd : public CATCommand
{
public:

  TCAUTLListDocsCmd();
  virtual ~TCAUTLListDocsCmd();

  /**
   * Overload this method: when your command gains focus
   * <p>
   * Activates a command.
   * @param iFromClient
   *   The command that requests to activate the current one.
   * @param iEvtDat
   *   The notification sent.
   */
  virtual CATStatusChangeRC Activate(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);

private:

  void listDocs(void);
  void listAttr(void);
  void listAttr(CATDocument* i_pDoc);
  void listCommands(void);

  CATISpecObject_var getSelectedElement(void);

  void printSpec(CATISpecObject_var i_spSpec, CATUnicodeString i_Prefix = "");
  void printAttr(CATISpecObject_var i_spSpec);

};

//----------------------------------------------------------------------

#endif
