// COPYRIGHT Dassault Systemes 2013
//===================================================================
//
// TCAUTLListAttrCmd.h
// The dialog : TCAUTLListAttrCmd
// It is a command.
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jan 2013  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAUTLListAttrCmd_H
#define TCAUTLListAttrCmd_H

#include "CATDlgCombo.h"
#include "CATGeoFactory.h"
#include "CATListOfInt.h"
#include "CATDlgFrame.h"
#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATISpecObject.h"
#include "CATLISTV_CATISpecObject.h"
#include "CATUnicodeString.h"
#include "TCAIUTLDoIt.h"
//----------------------------------------------------------------------

/**
* Describe the purpose of your panel here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog framework.
* (consult base class description).
*/
class TCAUTLListAttrCmd : public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource(TCAUTLListAttrCmd, CATDlgDialog)


private:

  CATCallback m_ShowContSpecCallback;


  CATDlgEditor* m_pInterfaceEditor;
  CATDlgMultiList* m_pClassesMultiList;

  CATListValCATUnicodeString m_InterfaceDirectories;
  CATListValCATUnicodeString m_FullPathes;

  CATUnicodeString m_LastTxt;
  CATUnicodeString m_TypeSelected;
  int m_LastFound;

  CATDlgFrame* m_pContListFrame;

  CATListOfInt m_ListLinesNb;
  CATListValCATUnicodeString m_ListHeaders;

  CATListValCATBaseUnknown_var m_ListOfContainerObjects;

  CATBaseUnknown_var m_spContainer;

  int            m_FirstTime;

  CATListValCATISpecObject_var m_ListSpec;

  CATISpecObject_var m_spSpec;

  CATListValCATUnicodeString m_ListOfNames;

  CATDlgMultiList* m_pInterfMultiList;
  CATDlgMultiList* m_pMethodsMultiList;

  CATDlgMultiList* m_pMultiListContainer;

  CATDlgEditor* m_pShowEditor;
  CATDlgEditor* m_pSearchEditor;

  CATDlgCombo* m_pContTypeCombo;

  CATDlgEditor* m_pAnswerEditor;
  CATDlgEditor* m_pQuestionEditor;
  CATDlgCombo* m_pPersonCombo;

  CATUnicodeString m_DocUUID;

  CATListValCATUnicodeString m_DataToStoreInDB;
  CATListValCATUnicodeString m_IdsToStoreInDB;
  CATListValCATUnicodeString m_ParentIdsToStore;

  CATDocument* m_pCurrentDoc;

  CATBoolean m_OpenAI;
  CATBoolean m_IsBuilt;

  CATListOfCATUnicodeString m_CmdNames;
  CATListOfCATUnicodeString m_CmdDescriptions;


public:

  TCAUTLListAttrCmd(CATISpecObject_var i_spSpec = NULL_var);
  virtual ~TCAUTLListAttrCmd();

  void Build();


  /**
  * Overload this method: when your command gains focus
  * <p>
  * Activates a command.
  * @param iFromClient
  *   The command that requests to activate the current one.
  * @param iEvtDat
  *   The notification sent.
  */
  virtual CATStatusChangeRC Activate(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);

  /**
  *  Overload this method: when your command loses focus
  * <p>
  * Deactivates a command.
  * @param iFromClient
  *   The command that takes the current active place.
  * @param iEvtDat
  *   The notification sent.
  */
  virtual CATStatusChangeRC Desactivate(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);

  /**
  *  Overload this method: when your command is canceled
  * <p>
  * Cancels a command.
  * @param iFromClient
  *   The command that takes the current active place.
  * @param iEvtDat
  *   The notification sent.
  */
  virtual CATStatusChangeRC Cancel(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);

  virtual CATStatusChangeRC  AIHelp(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);


  CATUnicodeString getUTF8Str(const CATUnicodeString& i_rStr);


  /**
* This method compares strings.
*/
//int stringCompare( CATUnicodeString* i_pParam1, CATUnicodeString* i_pParam2 );

protected:


private:

  CATISpecObject_var getSelectedElement(void);

  void showContainers(CATDlgFrame* i_pFrame, CATDocument* i_pDoc);

  void onShowClasses(CATCommand*, CATNotification*, CATCommandClientData i_Data);

  void showInterfaces(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showClasses(CATDlgFrame* i_pFrame);

  void showSpecObjectAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showExternalAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec, int i_YGrid = 0);
  void showListExternalAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec, int i_YGrid = 0);

  void showComponentAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showStringAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showIntegerAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showDoubleAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showBooleanAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);

  void showContainer(CATBaseUnknown_var i_spUnk);
  void showGeoFactContainer(CATGeoFactory_var i_spGeoFact);

  void showListStringAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showListIntegerAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showListDoubleAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showListBooleanAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);

  void showListComponentAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);
  void showListSpecObjectAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);

  void showPointingAttr(CATDlgFrame* i_pFrame, CATISpecObject_var i_spSpec);

  void showSpec(CATCommand*, CATNotification*, CATCommandClientData data);
  void readContainer(CATCommand*, CATNotification*, CATCommandClientData data);
  void typeSelected(CATCommand*, CATNotification*, CATCommandClientData data);

  void showAddedProperties(CATDlgFrame* i_pFrame, CATDocument* i_pDoc);

  void ShowButtonSpec(CATCommand*, CATNotification*, CATCommandClientData i_DatalistOfNames);
  void searchInMethod(CATCommand*, CATNotification*, CATCommandClientData i_DatalistOfNames);

  CATBoolean GetSystemVariable(const CATUnicodeString& iSystemVariable, CATUnicodeString& oVarValue);

  void ShowMultiListSpec(CATCommand*, CATNotification*, CATCommandClientData i_Data);
  void interfaceSelected(CATCommand*, CATNotification*, CATCommandClientData i_Data);
  void methodSelected(CATCommand*, CATNotification*, CATCommandClientData i_Data);

  void askAI(CATCommand*, CATNotification*, CATCommandClientData i_Data);
  void storeDBBulk(CATCommand*, CATNotification*, CATCommandClientData i_Data);

  void fillMultiList();

  void ShowContainerSpec(CATCommand*, CATNotification*, CATCommandClientData i_Data);

  CATBoolean checkFileExists(CATUnicodeString& o_rIntName);

  void initInterfaceDirectories(void);

  void getInstallPathes(CATUnicodeString& o_rPathes);
  HRESULT readDirectory(const CATUnicodeString& i_rDir, CATListOfCATUnicodeString& o_rHeadersDir);

  CATBoolean isEntryOk(const CATUnicodeString& i_rEntryStr);

  void setUpdateFacetLabel(CATDlgFrame* i_pFrame, int i_YGrid, int i_XGrid, CATBaseUnknown_var i_spAttrKey, CATISpecObject_var i_spSpec);

  int getDocUuid(CATDocument* i_pDoc, CATDlgFrame* i_pFrame);
  void buildFrameEditor(CATUnicodeString i_Title, const CATUnicodeString& i_rText, CATDlgFrame* i_pFrame, int i_GridY);

  CATUnicodeString octetToStringInt(const SEQUENCE(octet)& i_rOctet, CATDlgFrame* i_pFrame = NULL, int i_GridY = 0);

  void getGeoFactContent(CATGeoFactory_var i_spGeoFact, CATListOfCATUnicodeString& o_rColumn1, CATListOfCATUnicodeString& o_rColumn2, CATListOfCATUnicodeString& o_rColumn3);

  static int compareByPersistentTag(CATBaseUnknown_var* i_pspCGMObject1, CATBaseUnknown_var* i_pspCGMObject2);
  static int compareByPersistentTagOfBody(CATBaseUnknown_var* i_pspCGMObject1, CATBaseUnknown_var* i_pspCGMObject2);

  void onMultiListComponents(CATCommand*, CATNotification*, CATCommandClientData data);

  void saveStrAttr(CATCommand*, CATNotification*, CATCommandClientData data);

  void showAttributesXML(CATDlgFrame* i_pFrame);

  void buildAIContainer(CATDlgFrame* i_pFrame);

  void initDataToStoreInDB(void);

  void clearDB(void);

  int getListFromCont(CATIContainer_var i_spClientCont, CATListValCATBaseUnknown_var& o_rList);

  void getGoSpecs(CATListValCATBaseUnknown_var& o_rComponents);

  void getGoComponents(CATListValCATBaseUnknown_var& o_rComponents); 

  void getJSONContentOfCommandHeader(const int& i_rIdx, CATUnicodeString& o_rJSONContent);

  void getJSONContentOfSpec(TCAIUTLDoIt_var i_spDoItSpec, CATUnicodeString& o_rJSONContent);

  void getJSONContentOfComponent(TCAIUTLDoIt_var i_spDoItComp, CATUnicodeString& o_rJSONContent);

  void getCommands(CATListOfCATUnicodeString& o_rCmdNames, CATListOfCATUnicodeString& o_rCmdDescriptions);

  void addToDescription(CATUnicodeString& io_rDesc, CATUnicodeString& io_rStr);
};

//----------------------------------------------------------------------

#endif
