// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module TCAUTLItf
#======================================================================
#  2025.08.04 Creation: Code generated by the 3DS wizard
#======================================================================
#
#
# SHARED LIBRARY
#
BUILT_OBJECT_TYPE=SHARED LIBRARY

LINK_WITH = JS0GROUP


INCLUDED_MODULES =  TCAUTLItfCPP
