//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAIUTLDoIt.cpp
// Header definition of class TCAIUTLDoIt
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "TCAIUTLDoIt.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_TCAIUTLDoIt = {0x8d19af0a,0x0969,0x4d23,{ 0xbd,0xcd,0x1b,0x65,0x20,0xc1,0xcb,0xcd}};
#endif

CATImplementInterface(TCAIUTLDoIt, CATBaseUnknown);
CATImplementHandler(TCAIUTLDoIt, CATBaseUnknown);
