//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAIUTLDoItMember.cpp
// Header definition of class TCAIUTLDoItMember
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================
#include "CATMetaClass.h"
#include "TCAIUTLDoItMember.h"


#ifndef LOCAL_DEFINITION_FOR_IID
IID IID_TCAIUTLDoItMember = {0xf0860593,0xe025,0x46df,{ 0xaa,0x1b,0x85,0x90,0x20,0xb5,0x7b,0xe8}};
#endif

CATImplementInterface(TCAIUTLDoItMember, CATBaseUnknown);
CATImplementHandler(TCAIUTLDoItMember, CATBaseUnknown);
