// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoRenameObjects.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGoRenameObjects.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATScriptUtilities.h"
#include "CATAutoConversions.h"
#include "CATAfrCommandHeaderServices.h"
#include <stdlib.h>
#include "CATDocument.h"
#include "CATFrmEditor.h"
#include "CATIProduct.h"
#include "CATBody.h"
#include "CATIDrwGenDrawShape.h"
#include "CATListOfInt.h"
#include "CATIDftDrawing.h"
#include "CATISpecObject.h"
#include "CATIDftDocumentServices.h"
#include "CATSession.h"
#include "iostream.h" 
#include "CATSessionServices.h"
#include "CATDocumentServices.h" 
#include "TCAXmlUtils.h"
#include "CATInit.h"
#include "CATLISTP_CATMathPoint2D.h"
#include "CATIPrtContainer.h"
#include "CATIColInvariantId.h"
#include "CATIABase.h"
#include "CATITPSTextContent.h"
#include "TCAIUTLGo.h"
#include <Python.h>
#include <iostream>
#include <cstring>
#include "CATIIniSearchServices.h"
#include "CATIIniSearchCriterion.h"
#include "CATCreateInstance.h"
#include "CATIniSearchServicesComponent.h"
#include "CATViewer.h"
#include "CATPixelImage.h"
#include "CATUuid.h"
#include <windows.h>
#include "CATInteractiveApplication.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATCell.h" 
#include "CATIBRepAccess.h"
#include "CATMfBRepDecode.h"

TCA_UTL_COMPONENT_CPP(UTLGoRenameObjects)

CATImplementClass(TCAEUTLGoRenameObjects,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGoRenameObjects);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoRenameObjects);

//-----------------------------------------------------------------------------
// TCAEUTLGoRenameObjects : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoRenameObjects::TCAEUTLGoRenameObjects()
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
}

//-----------------------------------------------------------------------------
// TCAEUTLGoRenameObjects : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoRenameObjects::~TCAEUTLGoRenameObjects()
{}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoRenameObjects::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Renames CATIA objects in the specification tree according to their functions";
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoRenameObjects::doIt(void)
{
  HRESULT hr = E_FAIL;
  if( m_spThis == NULL_var || m_spSingleTon == NULL_var )
  {
    return E_FAIL;
  }


  int objIdx = 0;
  m_spSingleTon->getValue("obj_idx", objIdx);
  if( objIdx == 0 )
  {
    this->initObjects();
  }

  m_spSingleTon->getValue("objects", m_Objects);

  if( objIdx > 0 && objIdx <= m_Objects.Size() )
  {
    CATUnicodeString objAlias;
    m_spThis->getValue("obj_name", objAlias);
    if( objAlias != "" )
    {
      TCAUTLSetAlias(m_Objects[objIdx], objAlias);
    }
  }

  if( m_Objects.Size() > objIdx )
  {
    objIdx++;
    this->renameObject(m_Objects[objIdx]);

    m_spSingleTon->setValue("obj_idx", objIdx);
    m_spSingleTon->setValue("obj_name", TCADRTGetAlias(m_Objects[objIdx]));

    CATCommand* pCmd = NULL;
    CATAfrStartCommand("TCAUTLRenameObj", pCmd);
  }

  if( objIdx > m_Objects.Size() )
  {
    objIdx = 0;
    m_spSingleTon->setValue("obj_idx", objIdx);
  }
  return S_OK;
} // doIt

//-----------------------------------------------------------------------------
// TCAListFromCont
//-----------------------------------------------------------------------------
int TCAEUTLGoRenameObjects::listFromCont(CATIContainer_var i_spClientCont, CATListValCATBaseUnknown_var& o_rList)
{
  int countObjects = 0;
  o_rList.RemoveAll();
  if( !!i_spClientCont )
  {
    SEQUENCE(CATBaseUnknown_ptr) ListObj;
    CATLONG32 cnt = i_spClientCont->ListMembersHere("CATBaseUnknown", ListObj);
    for( int i = 0; i < cnt; i++ )
    {
      CATBaseUnknown* piObj = NULL;
      if( ListObj[i] && SUCCEEDED(ListObj[i]->QueryInterface(IID_CATBaseUnknown, (void**)&piObj)) )
      {
        o_rList.Append(piObj);
        piObj->Release();
        piObj = NULL;
      }
    }
    countObjects = o_rList.Size();
  }
  return countObjects;
} // TCAListFromCont

//----------------------------------------------------------------------------------
// initObjects
//----------------------------------------------------------------------------------
void TCAEUTLGoRenameObjects::initObjects(void)
{
  m_Objects.RemoveAll();
  CATDocument* pDoc = NULL;
  CATFrmEditor* pEditor = CATFrmEditor::GetCurrentEditor();
  if( pEditor )
  {
    pDoc = pEditor->GetDocument();
  }

  CATIContainer_var  spMechCont;
  CATInit_var spInit = pDoc;
  if( !!spInit )
  {
    const CATIdent contID = "CATIPrtContainer";
    CATIPrtContainer* piPartContainer = (CATIPrtContainer*)spInit->GetRootContainer(contID);
    if( piPartContainer )
    {
      spMechCont = piPartContainer->GetMechanicalContainer();
    }
  }

  CATListValCATBaseUnknown_var listObj;
  int  cntObj = this->listFromCont(spMechCont, listObj);

  for( int i = 1; i <= cntObj; i++ )
  {
    if( listObj[i]->GetImpl()->IsAKindOf("GSMBiDim") != 1 || listObj[i]->GetImpl()->IsAKindOf("GSMPlane") )
    {
      continue;
    }
    m_Objects.Append(listObj[i]);

    CATUnicodeString alias("alias");
    CATIAlias_var spAlias = listObj[i];
    if( !!spAlias )
    {
      alias = spAlias->GetAlias();
    }
    // cerr << alias << ":\t" << spAlias->GetImpl()->IsA() << endl;

  }
  if( !!m_spSingleTon )
  {
    m_spSingleTon->setValue("objects", m_Objects);
  }

  return;
} // initObjects

//---------------------------------------------------------------------------
// setExtRefColor 
//---------------------------------------------------------------------------
void TCAEUTLGoRenameObjects::setColorRGB(CATIGeometricalElement_var i_spGeomElm,
                                         const unsigned int& i_R,
                                         const unsigned int& i_G,
                                         const unsigned int& i_B)
{
  if( i_spGeomElm == NULL_var )
  {
    return;
  }
  CATBody_var spCATBody = i_spGeomElm->GetBodyResult();
  if( spCATBody == NULL_var )
  {
    return;
  }

  CATVisPropertiesValues valueToSet;
  valueToSet.SetColor(i_R, i_G, i_B, 1);


  CATLISTP(CATCell) faces;
  spCATBody->GetAllCells(faces, 2);
  for( int i = 1; i <= faces.Size(); i++ )
  {
    CATIBRepAccess_var spBRepAccess(CATBRepDecode(faces[i], i_spGeomElm));
    if( spBRepAccess == NULL_var )
    {
      continue;
    }

    CATIVisProperties_var spBRepAccessAsGraphics = spBRepAccess;
    if( spBRepAccessAsGraphics == NULL_var )
    {
      continue;
    }

    spBRepAccessAsGraphics->SetPropertiesAtt(valueToSet, CATVPColor, CATVPMesh);
  }
  this->refreshVisu(i_spGeomElm);
  return;
}// setExtRefColor

//---------------------------------------------------------------------------
// refreshVisu
//---------------------------------------------------------------------------
void TCAEUTLGoRenameObjects::refreshVisu(CATBaseUnknown_var i_spUnknown)
{
  CATIModelEvents_var spModelEvents(i_spUnknown);
  if( spModelEvents != NULL_var )
  {
    CATBaseUnknown* piUnknown = NULL;
    HRESULT hr = spModelEvents->QueryInterface(IID_CATBaseUnknown, (void**)&piUnknown);
    if( SUCCEEDED(hr) && piUnknown != NULL )
    {
      CATModify Notif(piUnknown);
      spModelEvents->Dispatch(Notif);

      if( piUnknown != NULL )
      {
        piUnknown->Release();
        piUnknown = NULL;
      }
    }
  } // spModelEvents != NULL_var  
  return;
} // refreshVisu

//----------------------------------------------------------------------------------
// renameObject
//----------------------------------------------------------------------------------
void TCAEUTLGoRenameObjects::renameObject(CATISpecObject_var i_spObj)
{
  if( i_spObj == NULL_var )
  {
    return;
  }

  for( int i = 1; i <= m_Objects.Size(); i++ )
  {
    this->setColorRGB(m_Objects[i], 255, 255, 255);
  }

  this->setColorRGB(i_spObj, 255, 0, 0);
  cerr << "Red: " << TCADRTGetAlias(i_spObj) << endl;

  return;
} // renameObject


//---------------------------------------------------------------------------
// printViewer
//---------------------------------------------------------------------------
void TCAEUTLGoRenameObjects::printViewer(void)
{
  CATFrmLayout* pCurrentLayout = CATFrmLayout::GetCurrentLayout();
  if( !pCurrentLayout )
    return;

  CATFrmWindow* pCurrentWindow = pCurrentLayout->GetCurrentWindow();
  if( !pCurrentWindow )
    return;

  CATViewer* pViewer = pCurrentWindow->GetViewer();
  if( !pViewer )
    return;

  m_ImagePath = "c:\\tmp\\IMG_NAME.png";

  CATUuid uuid;
  char* c = new char[255];
  uuid.UUID_to_chaine(c);
  m_ImagePath.ReplaceSubString("IMG_NAME", CATString(c));
  delete[] c;

  CATPixelImage* pImg = pViewer->GrabPixelImage();

  pImg->WriteToFile("PNG", m_ImagePath);
  return;
} // printViewer

//-------------------------------------------------------------------------
// callAI
//-------------------------------------------------------------------------
void TCAEUTLGoRenameObjects::callAI(void)
{
  CATUnicodeString answerAI;
  cerr << __FUNCTION__ << endl;

  // Check Python version
  const char* version = Py_GetVersion();
  cerr << "Python version in use: " << version << endl;

  static PyObject* s_pAIMmodule = NULL;
  if( !s_pAIMmodule )
  {
    s_pAIMmodule = PyImport_ImportModule("TCACATPythonCAA");
  }

  if( !s_pAIMmodule )
  {
    PyErr_Print();
    std::cerr << "Failed to load TCACATPythonCAA.h\n";
    return;
  }

  PyObject* s_pFunc = NULL;
  if( !s_pFunc )
  {
    s_pFunc = PyObject_GetAttrString(s_pAIMmodule, "describe_screnshot");  // 3. Get aksAI()
  }
  if( !s_pFunc || !PyCallable_Check(s_pFunc) )
  {
    PyErr_Print();
    std::cerr << "Cannot find function TCACATPythonCAA::describe_screnshot()\n";
    return;
  }


  // PyObject* args = PyTuple_Pack(1, arg1); 
  PyObject* result = PyObject_CallObject(s_pFunc, nullptr);

  if( result )
  {
    // answerAI = PyUnicode_AsUTF8(result);
    const char* result_utf8 = PyUnicode_AsUTF8(result);
    if( result_utf8 )
    {
      // answerAI = CATUnicodeString(result_utf8);
      size_t utf8Length = strlen(result_utf8);
      answerAI.BuildFromUTF8(result_utf8, utf8Length);
    }
    std::cout << "Python function returned: " << answerAI << "\n";
    Py_DECREF(result);

  }
  else
  {
    PyErr_Print();
  }

  answerAI.ReplaceAll(".", ",");
  CATListOfCATUnicodeString tokens;
  CATToken token(answerAI);
  CATUnicodeString sep(";");
  CATUnicodeString tok = token.GetNextToken(sep);
  while( tok != "" )
  {
    tokens.Append(tok);
    tok = token.GetNextToken(sep);
  }
  return;
} // callAI
