// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoExportJSON.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATPrsWorkModeServices.h"
#include "CATSession.h"
#include "CATLib.h" 
#include "CATEdge.h"
#include "CATBody.h"
#include "CATCell.h"
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGoExportJSON.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "IDMCurve2D.h"

TCA_UTL_COMPONENT_CPP(UTLGoExportJSON)

CATImplementClass(TCAEUTLGoExportJSON,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGoExportJSON);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoExportJSON);

//-----------------------------------------------------------------------------
// TCAEUTLGoExportJSON : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoExportJSON::TCAEUTLGoExportJSON() : m_pRootDoc(NULL)
{}

//-----------------------------------------------------------------------------
// TCAEUTLGoExportJSON : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoExportJSON::~TCAEUTLGoExportJSON()
{
  m_pRootDoc = NULL;
}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoExportJSON::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Generates the JSON representation of the current CATIA document";
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoExportJSON::doIt(void)
{
  m_Items.RemoveAll();
  m_Lines.RemoveAll();
  HRESULT hr = E_FAIL;
  TCAIUTLGo_var spThis = this;
  m_Lines.RemoveAll();
  m_spRootItem = this->newItem();
  if( !!spThis && !!m_spRootItem )
  {

    CATBoolean writeFile = FALSE;
    spThis->getInput(writeFile);

    spThis->getInput(m_pRootDoc);
    if( m_pRootDoc )
    {
      TCAIUTLGo_var spCATDocItem = this->getItemOfDocument(m_pRootDoc);
      if( !!spCATDocItem )
      {
        this->addItem(m_spRootItem, "CATDocument", spCATDocItem);
        spThis->setOutput(m_Items);
      }

      CATUnicodeString storageName = m_pRootDoc->StorageName();
      char valueDir[1024];
      char valueFile[512];
      ::CATSplitPath(storageName.ConvertToChar(), valueDir, valueFile);
      m_RootDocName = valueFile;
      m_RootDocDir = valueDir;

      storageName.Append(".json");

      this->writeJSON(m_spRootItem);
      hr = spThis->setOutput(m_Lines);
      if( writeFile )
      {
        ofstream jsonFile;
        jsonFile.open(storageName.ConvertToChar(), ios::binary);
        if( jsonFile )
        {
          for( int j = 1; j <= m_Lines.Size(); j++ )
          {
            jsonFile << m_Lines[j].ConvertToChar() << ENDL;
          }
          jsonFile.close();
        }
      }
    }
  }
  return hr;
} // doIt

//-----------------------------------------------------------------------------
// newItem
//-----------------------------------------------------------------------------
TCAIUTLGo_var TCAEUTLGoExportJSON::newItem(void)
{
  TCAIUTLGo_var spItem = UTL_INST(UTLGoItem);
  if( !!spItem )
  {
    this->addValue(spItem, "uuid", spItem->getUuid());
    m_Items.Append(spItem);
  }
  return spItem;
} // newItem

//-----------------------------------------------------------------------------
// addToItem
//-----------------------------------------------------------------------------
TCAIUTLGo_var TCAEUTLGoExportJSON::getItemOfDocument(CATDocument* i_pDoc)
{
  if( !i_pDoc )
  {
    return NULL_var;
  }
  TCAIUTLGo_var spItem = this->newItem();
  if( spItem == NULL_var )
  {
    return NULL_var;
  }
  CATUnicodeString alias = TCAUTLGetAlias(i_pDoc);
  this->addValue(spItem, "alias", alias);
  CATUnicodeString storageName = i_pDoc->StorageName();
  storageName.ReplaceAll("\\", "\\\\");
  this->addValue(spItem, "path", storageName);

  // containers 
  CATIContainer_var spClientCont = i_pDoc->GetCompoundContainer();
  CATListValCATBaseUnknown_var containerItems;
  if( !!spClientCont )
  {
    // containerItems.Append(this->getItemOfContainer(spClientCont));
    SEQUENCE(CATBaseUnknown_ptr) listObj;
    CATLONG32 cnt = spClientCont->ListMembersHere("CATIContainer", listObj);
    for( int i = 0; i < cnt; i++ )
    {
      CATBaseUnknown* piObj = NULL;
      if( listObj[i] && SUCCEEDED(listObj[i]->QueryInterface(IID_CATBaseUnknown, (void**)&piObj)) )
      {
        containerItems.Append(this->getItemOfContainer(piObj));
        piObj->Release();
        piObj = NULL;
      }
    }
    this->addItems(spItem, "containers", containerItems);
  } // containers 

  return spItem;
} // getItemOfDocument

//-----------------------------------------------------------------------------
// getItemOfContainer
//-----------------------------------------------------------------------------
TCAIUTLGo_var TCAEUTLGoExportJSON::getItemOfContainer(CATIContainer_var i_spContainer)
{
  if( i_spContainer == NULL_var )
  {
    return NULL_var;
  }
  TCAIUTLGo_var spItem = this->newItem();
  if( spItem == NULL_var )
  {
    return NULL_var;
  }

  CATUnicodeString contType = i_spContainer->GetImpl()->IsA();
  this->addValue(spItem, "type", contType);

  // specs 
  CATListValCATBaseUnknown_var specItems;
  SEQUENCE(CATBaseUnknown_ptr) listObj;
  CATLONG32 cnt = i_spContainer->ListMembersHere("CATBaseUnknown", listObj);
  for( int i = 0; i < cnt; i++ )
  {
    CATBaseUnknown* piObj = NULL;
    if( listObj[i] && SUCCEEDED(listObj[i]->QueryInterface(IID_CATBaseUnknown, (void**)&piObj)) )
    {
      specItems.Append(this->getItemOfSpec(piObj));
      piObj->Release();
      piObj = NULL;
    }
  } // specs 
  this->addItems(spItem, "specs", specItems);
  return spItem;
} // getItemOfContainer

//-----------------------------------------------------------------------------
// getItemOfSpec
//-----------------------------------------------------------------------------
TCAIUTLGo_var TCAEUTLGoExportJSON::getItemOfSpec(CATBaseUnknown_var i_spSpec)
{
  if( i_spSpec == NULL_var )
  {
    return NULL_var;
  }
  TCAIUTLGo_var spItem = this->newItem();
  if( spItem == NULL_var )
  {
    return NULL_var;
  }

  this->addValue(spItem, "type", i_spSpec->GetImpl()->IsA());

  CATUnicodeString alias = TCAUTLGetAlias(i_spSpec);
  alias.ReplaceAll("\\", "\\\\");
  this->addValue(spItem, "alias", alias);

  CATISpecObject_var spSpec = i_spSpec;
  if( !!spSpec )
  {
    CATUnicodeString internName = spSpec->GetName();
    internName.ReplaceAll("\\", "\\\\");
    this->addValue(spItem, "name", internName);
  }

  // attributes
  CATISpecAttrAccess_var spSpecAttrAcc = i_spSpec;
  if( !!spSpecAttrAcc )
  {
    CATListValCATBaseUnknown_var attrItems;
    CATListValCATISpecAttrKey_var attrKeys;
    HRESULT hr = spSpecAttrAcc->ListAttrKeys(attrKeys);
    for( int i = 1; i <= attrKeys.Size(); i++ )
    {
      attrItems.Append(this->getItemOfAttr(spSpecAttrAcc, attrKeys[i]));
    }
    this->addItems(spItem, "attributes", attrItems);
  }  // attributes

  // interfaces
  CATListValCATBaseUnknown_var interfacesItems;
  this->getInterfacesItemsOf(i_spSpec, interfacesItems);
  this->addItems(spItem, "interfaces", interfacesItems);

  return spItem;
} // getItemOfSpec

//-----------------------------------------------------------------------------
// getInterfacesItemsOf
//-----------------------------------------------------------------------------
void TCAEUTLGoExportJSON::getInterfacesItemsOf(CATBaseUnknown_var i_spSpec,
                                               CATListValCATBaseUnknown_var& o_rItems)
{
  // IDMCurve2D
  IDMCurve2D_var spIDMCurve2D = i_spSpec;
  if( !!spIDMCurve2D )
  {
    TCAIUTLGo_var spItem = this->newItem();
    if( !!spItem )
    {
      this->addValue(spItem, "interface", "IDMCurve2D");
      o_rItems.Append(spItem);

      DWORD geoForm;
      if( SUCCEEDED(spIDMCurve2D->GetGeometryForm(&geoForm)) )
      {
        this->addValue(spItem, "GeometryForm", TCAUTLBuildFromNum((unsigned int)geoForm));
      }
      double startParam = 0.0;
      double endParam = 0.0;
      if( SUCCEEDED(spIDMCurve2D->GetParamExtents(&startParam, &endParam)) )
      {
        this->addValue(spItem, "GetParamExtents:StartParam", TCAUTLBuildFromDbl(startParam));
        this->addValue(spItem, "GetParamExtents:EndParam", TCAUTLBuildFromDbl(endParam));
      }

      double minPnt = 0.0;
      double maxPnt = 0.0;
      if( SUCCEEDED(spIDMCurve2D->GetRangeBox(&minPnt, &maxPnt)) )
      {
        this->addValue(spItem, "GetRangeBox:MinPoint", TCAUTLBuildFromDbl(minPnt));
        this->addValue(spItem, "GetRangeBox:MaxPoint", TCAUTLBuildFromDbl(maxPnt));
      }


    }
  } // IDMCurve2D
  return;
} // getInterfacesItemsOf

//-----------------------------------------------------------------------------
// getItemOfAttr
//-----------------------------------------------------------------------------
TCAIUTLGo_var TCAEUTLGoExportJSON::getItemOfAttr(CATISpecAttrAccess_var i_spAttrAccess,
                                                 CATISpecAttrKey_var i_spAttrKey)
{
  if( i_spAttrAccess == NULL_var || i_spAttrKey == NULL_var )
  {
    return NULL_var;
  }
  TCAIUTLGo_var spItem = this->newItem();
  if( spItem == NULL_var )
  {
    return NULL_var;
  }

  CATISpecAttrKey* piAttrKey = NULL;
  UTL_QUERY(i_spAttrKey, CATISpecAttrKey, piAttrKey);
  if( !piAttrKey )
  {
    return NULL_var;
  }

  CATUnicodeString attrName = i_spAttrKey->GetName();
  CATUnicodeString attrType;

  int attrSize = 0;

  CATAttrKind attrKind = i_spAttrKey->GetType();
  CATAttrKind attrKindList = i_spAttrKey->GetListType();

  CATUnicodeString attrValue;

  // tk_boolean
  if( attrKind == tk_boolean )
  {
    attrType = "tk_boolean";
    attrValue = "FALSE";
    CATBoolean valueBool = i_spAttrAccess->GetBoolean(piAttrKey);
    if( valueBool )
    {
      attrValue = "TRUE";
    }
  } // tk_boolean

  // tk_list(tk_boolean) 
  else if( attrKindList == tk_boolean )
  {
    attrType = "tk_list(tk_boolean)";
    int cnt = i_spAttrAccess->GetListSize(piAttrKey);
    attrSize = cnt;
    for( int i = 1; i <= cnt; i++ )
    {
      if( i > 1 )
      {
        attrValue.Append(";");
      }
      CATBoolean valueBool = i_spAttrAccess->GetBoolean(piAttrKey, i);
      if( valueBool )
      {
        attrValue.Append("TRUE");
      }
      else
      {
        attrValue.Append("FALSE");
      }
    }
  } // tk_list(tk_boolean) 

  // tk_integer
  if( attrKind == tk_integer )
  {
    attrType = "tk_integer";
    int valueInt = i_spAttrAccess->GetInteger(piAttrKey);
    attrValue.BuildFromNum(valueInt);
  } // tk_integer

  // tk_list(tk_integer) 
  else if( attrKindList == tk_integer )
  {
    attrType = "tk_list(tk_integer)";
    CATListOfInt listInt;
    int cnt = i_spAttrAccess->GetListSize(piAttrKey);
    attrSize = cnt;
    for( int i = 1; i <= cnt; i++ )
    {
      if( i > 1 )
      {
        attrValue.Append(";");
      }
      int valueInt = i_spAttrAccess->GetInteger(piAttrKey, i);
      CATUnicodeString valueStr;
      valueStr.BuildFromNum(valueInt);
      attrValue.Append(valueStr);
    }
  } // tk_list(tk_integer) 

  // tk_double
  if( attrKind == tk_double )
  {
    attrType = "tk_double";
    double valueDbl = i_spAttrAccess->GetInteger(piAttrKey);
    attrValue.BuildFromNum(valueDbl);
  } // tk_double

  // tk_list(tk_double) 
  else if( attrKindList == tk_double )
  {
    attrType = "tk_list(tk_double)";
    int cnt = i_spAttrAccess->GetListSize(piAttrKey);
    attrSize = cnt;
    for( int i = 1; i <= cnt; i++ )
    {
      if( i > 1 )
      {
        attrValue.Append(";");
      }
      double valueDbl = i_spAttrAccess->GetInteger(piAttrKey, i);
      CATUnicodeString valueStr;
      valueStr.BuildFromNum(valueDbl);
      attrValue.Append(valueStr);
    }
  } // tk_list(tk_double) 

  // tk_string
  else if( attrKind == tk_string )
  {
    attrType = "tk_string";
    attrValue = i_spAttrAccess->GetString(piAttrKey);
    if( attrValue.SearchSubString("#In String") > -1 )
    {
      // cerr << attrValue << endl;
    }
  } // tk_string

  // tk_list(tk_string) 
  else if( attrKindList == tk_string )
  {
    attrType = "tk_list(tk_string)";
    int cnt = i_spAttrAccess->GetListSize(piAttrKey);
    attrSize = cnt;
    for( int i = 1; i <= cnt; i++ )
    {
      if( i > 1 )
      {
        attrValue.Append(";");
      }
      CATUnicodeString valueStr = i_spAttrAccess->GetString(piAttrKey, i);
      attrValue.Append(valueStr);
    }
  } // tk_list(tk_string) 
  else if( attrKind == tk_octet )
  {
    attrType = "tk_octet";
    /*
    SEQUENCE(octet) octet = i_spAttrAccess->GetOctet(piAttrKey);
    int length = octet.length();
    for( int i = 0; i < length; i++ )
    {
      attrValue.Append(CATUnicodeString(octet[i]).ConvertToChar());
    }*/
  }
  else if( attrKindList == tk_octet )
  {
    attrType = "tk_list(tk_octet)";
    /*
    int size = i_spAttrAccess->GetListSize(piAttrKey);
    attrSize = size;
    for( int s = 1; s <= size; s++ )
    {
      if( s > 1 )
      {
        attrValue.Append(";");
      }
      CATUnicodeString attrStr;
      SEQUENCE(octet) octet = i_spAttrAccess->GetOctet(piAttrKey, s);
      int length = octet.length();
      for( int i = 0; i < length; i++ )
      {
        attrStr.Append(CATUnicodeString(octet[i]).ConvertToChar());
      }
      attrValue.Append(attrStr);
    }
    */
  }
  // tk_specobject or tk_component
  else if( attrKind == tk_specobject || attrKind == tk_component )
  {
    if( attrKind == tk_specobject )
    {
      attrType = "tk_specobject";
    }
    else if( attrKind == tk_component )
    {
      attrType = "tk_component";
    }

    CATISpecObject* piSpec = i_spAttrAccess->GetSpecObject(piAttrKey);
    if( piSpec )
    {
      attrValue = TCAUTLGetAlias(piSpec);

      attrValue.Append("[");
      attrValue.Append(piSpec->GetImpl()->IsA());
      attrValue.Append("]");
      piSpec->Release();
      piSpec = NULL;
    }
  } // tk_specobject or tk_component

  // tk_list(tk_specobject) or tk_list(tk_component)  
  else if( attrKindList == tk_specobject || attrKindList == tk_component )
  {
    if( attrKindList == tk_specobject )
    {
      attrType = "tk_list(tk_specobject)";
    }
    else if( attrKindList == tk_component )
    {
      attrType = "tk_list(tk_component)";
    }

    int size = i_spAttrAccess->GetListSize(piAttrKey);
    attrSize = size;
    for( int s = 1; s <= size; s++ )
    {
      if( s > 1 )
      {
        attrValue.Append(";");
      }
      CATISpecObject* piSpec = i_spAttrAccess->GetSpecObject(piAttrKey, s);
      if( piSpec )
      {
        CATUnicodeString valueStr = TCAUTLGetAlias(piSpec);
        valueStr.Append("[");
        valueStr.Append(piSpec->GetImpl()->IsA());
        valueStr.Append("]");
        attrValue.Append(valueStr);

        piSpec->Release();
        piSpec = NULL;
      }
    }
  } // tk_list(tk_specobject) or tk_list(tk_component)     

  // tk_external
  else if( attrKind == tk_external )
  {
    attrType = "tk_external";
    /*
    SEQUENCE(octet) octet = i_spAttrAccess->GetExternalObjectName(piAttrKey);
    int length = octet.length();
    for( int i = 0; i < length; i++ )
    {
      attrValue.Append(CATUnicodeString(octet[i]).ConvertToChar());
    }
    */
  } // tk_external

  // tk_list(tk_external)
  else if( attrKindList == tk_external )
  {
    attrType = "tk_list(tk_external)";
  }
  else if( attrKind == tk_any )
  {
    attrType = "tk_any";
  }
  else if( attrKindList == tk_any )
  {
    attrType = "tk_list(tk_any)";
  }


  if( attrType == "" )
  {
    // cerr << attrName << endl;
  }

  piAttrKey->Release();
  piAttrKey = NULL;


  attrValue.ReplaceAll("\"", "'");
  attrValue.ReplaceAll("\\", "\\\\");
  attrValue.ReplaceAll("\n", "");

  this->addValue(spItem, "attr_name", attrName);
  this->addValue(spItem, "attr_type", attrType);
  this->addValue(spItem, "attr_value", attrValue);
  if( attrSize > 0 )
  {
    CATUnicodeString attrSizeStr;
    attrSizeStr.BuildFromNum(attrSize);
    this->addValue(spItem, "attr_size", attrSizeStr);
  }

  return spItem;
} // getItemOfAttr


//-----------------------------------------------------------------------------
// addItem
//-----------------------------------------------------------------------------
void TCAEUTLGoExportJSON::addItem(TCAIUTLGo_var i_spParent,
                                  const CATUnicodeString& i_rKey,
                                  TCAIUTLGo_var i_spItem)
{
  if( i_spParent == NULL_var || i_spItem == NULL_var || i_rKey == "" )
  {
    return;
  }
  i_spParent->setValue(i_rKey, i_spItem);
  CATUnicodeString parentUuid = i_spParent->getUuid();
  i_spItem->setParentUuid(parentUuid);
  this->addValue(i_spItem, "uuid_of_parent_element", parentUuid);
  return;
} // addItem

//-----------------------------------------------------------------------------
// addToItem
//-----------------------------------------------------------------------------
void TCAEUTLGoExportJSON::addItems(TCAIUTLGo_var i_spParent,
                                   const CATUnicodeString& i_rKey,
                                   const CATListValCATBaseUnknown_var& i_rItems)
{
  if( i_spParent == NULL_var || i_rItems.Size() == 0 || i_rKey == "" )
  {
    return;
  }
  i_spParent->setValue(i_rKey, i_rItems);
  for( int i = 1; i <= i_rItems.Size(); i++ )
  {
    TCAIUTLGo_var spItem = i_rItems[i];
    if( spItem == NULL_var )
    {
      continue;
    }
    CATUnicodeString parentUuid = i_spParent->getUuid();
    spItem->setParentUuid(parentUuid);
    this->addValue(spItem, "uuid_of_parent_element", parentUuid);
  }
  return;
} // addItems

//-----------------------------------------------------------------------------
// addValue
//-----------------------------------------------------------------------------
void TCAEUTLGoExportJSON::addValue(TCAIUTLGo_var i_spItem,
                                   const CATUnicodeString& i_rKey,
                                   const CATUnicodeString& i_rValue)
{
  if( i_spItem == NULL_var || i_rKey == "" )
  {
    return;
  }
  i_spItem->setValue(i_rKey, i_rValue);
  this->addLine(i_spItem, i_rKey, i_rValue);
  return;
} // addValue

//-----------------------------------------------------------------------------
// initLinesOfItem
//-----------------------------------------------------------------------------
void TCAEUTLGoExportJSON::writeJSON(TCAIUTLGo_var i_spItem,
                                    const CATUnicodeString& i_rKey,
                                    int i_Level)
{
  if( i_spItem == NULL_var )
  {
    return;
  }

  CATUnicodeString itemLine;

  CATBoolean propertyWritten = FALSE;
  CATListValCATBaseUnknown_var goMembers;
  i_spItem->getMembersRef(goMembers);
  if( i_rKey != "" )
  {
    m_Lines.Append("\"" + i_rKey + "\":");
  }
  m_Lines.Append("{");
  for( int m = 1; m <= goMembers.Size(); m++ )
  {
    TCAIUTLDoItMember_var spMember = goMembers[m];
    if( spMember == NULL_var )
    {
      continue;
    }

    CATUnicodeString key;
    spMember->getName(key);

    if( propertyWritten )
    {
      m_Lines.Append(",");
    }

    CATListValCATBaseUnknown_var childItems;
    spMember->getValue(childItems);
    if( childItems.Size() > 0 )
    {
      m_Lines.Append("\"" + key + "\": [");

      int cnt = childItems.Size();
      for( int i = 1; i <= cnt; i++ )
      {
        if( i > 1 )
        {
          m_Lines.Append(",");
        }
        this->writeJSON(childItems[i], "", i_Level + 1);
      }
      m_Lines.Append("]");

      continue;
    }

    TCAIUTLGo_var spChildItem = spMember->getUnknown();
    if( !!spChildItem )
    {
      this->writeJSON(spChildItem, key, i_Level + 1);
      continue;
    }

    CATUnicodeString value;
    spMember->getValue(value);

    m_Lines.Append("\"" + key + "\": " + "\"" + value + "\"");
    propertyWritten = TRUE;
  }
  m_Lines.Append("}");

  return;
} // initLinesOfItem

//-----------------------------------------------------------------------------
// addLine
//-----------------------------------------------------------------------------
void TCAEUTLGoExportJSON::addLine(TCAIUTLGo_var i_spItem,
                                  const CATUnicodeString& i_rKey,
                                  const CATUnicodeString& i_rValue)
{
  if( i_spItem == NULL_var )
  {
    return;
  }

  CATUnicodeString newLine;
  newLine.Append("\"");
  newLine.Append(i_rKey);
  newLine.Append("\": ");
  newLine.Append("\"");
  newLine.Append(i_rValue);
  newLine.Append("\"");

  i_spItem->addJLine(newLine);
  return;
} // addLine