// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoCreateCATPart.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGoCreateCATPart.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATScriptUtilities.h"
#include "CATAutoConversions.h"
#include "CATAfrCommandHeaderServices.h"
#include <stdlib.h>

TCA_UTL_COMPONENT_CPP(UTLGoCreateCATPart)

CATImplementClass(TCAEUTLGoCreateCATPart,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGoCreateCATPart);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoCreateCATPart);

//-----------------------------------------------------------------------------
// TCAEUTLGoCreateCATPart : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoCreateCATPart::TCAEUTLGoCreateCATPart()
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
}

//-----------------------------------------------------------------------------
// TCAEUTLGoCreateCATPart : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoCreateCATPart::~TCAEUTLGoCreateCATPart()
{}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoCreateCATPart::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Creates part document CATPart";
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoCreateCATPart::doIt(void)
{
  if( m_spThis == NULL_var || m_spSingleTon == NULL_var )
  {
    return E_FAIL;
  }   

  CATString macroName("UTLGoCreateCATPart.CATScript");
  m_spSingleTon->setValue("macro_name", macroName);

  HRESULT hr = E_FAIL;
  CATCommand* pCmd = NULL;
  CATAfrStartCommand("TCAUTLMacro", pCmd);
  if( pCmd )
  {
    pCmd = NULL;
    hr = S_OK;
  }
  return hr;
} // doIt