//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGoGSMBiDim.cpp
// Header definition of class TCAEUTLGoGSMBiDim
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#include "TCAEUTLGoGSMBiDim.h"
#include "CATPoint.h"
#include "CATIAlias.h"
#include "CATIGeometricalElement.h"
#include "CATBody.h"
#include "CATBodyTessellator.h"
#include "CATLine.h"
#include "CATTessPointIter.h"
#include "CATTessStripeIter.h" // CATTessStripeIter
#include "CATTessFanIter.h"    // CATTessFanIter
#include "CATTessPolyIter.h"   // CATTessPolyIter
#include "CATTessTrianIter.h"  // CATTessTrianIter
#include "CATMath.h"
#include "CATIGSMPlane.h"
#include "CATTopPointOperator.h" 
#include "CATIDatumFactory.h" 
#include "CATSoftwareConfiguration.h"  // CATSoftwareConfiguration
#include "CATTopData.h"               // CATTopData
#include "CATLISTV_CATBaseUnknown.h"
#include "CATIContainerOfDocument.h"   // CATIContainerOfDocument_var
#include "CATILinkableObject.h"        // CATILinkableObject_var
#include "CATDocument.h" 
#include "CATCrvParam.h" 
#include "CATCrvLimits.h" 
#include "CATCrvEvalLocal.h"
#include "CATVertex.h"
#include "CATCreateProjection.h"     // CATCreateProjection(...) overloads
#include "CATProjectionPtSur.h"      // CATProjectionPtSur class
#include "CATSurface.h"              // CATSurface*
#include "CATSkillValue.h"           // ADVANCED/BASIC skill level enum
#include "CATDynMassProperties1D.h"   // CATDynMassProperties1D, CATDynCreateMassProperties1D(...)
#include "CATHybProject.h"
#include "CreateDistanceMinTopo.h"     // CATCreateDistanceMinTopo(...)
#include "CATDistanceMinBodyBody.h"    // CATDistanceMinBodyBody class
#include "CATGeoFactory.h"             // CATGeoFactory* 

#define TCA_PWP_TOL 0.1

TCA_UTL_COMPONENT_CPP(UTLGoGSMBiDim)

CATImplementClass(TCAEUTLGoGSMBiDim,
                  DataExtension,
                  CATBaseUnknown,
                  GSMBiDim);


#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoGSMBiDim);

//-----------------------------------------------------------------------------
// TCAEUTLGoGSMBiDim : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoGSMBiDim::TCAEUTLGoGSMBiDim() :CATBaseUnknown()
{
  m_CountPoints = 0;
  m_spThis = this;
  this->initFactories();
}

//-----------------------------------------------------------------------------
// TCAEUTLGoGSMBiDim : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoGSMBiDim::~TCAEUTLGoGSMBiDim()
{
  this->initFactories();
}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "";

  CATBoolean isPlane = FALSE;

  CATUnicodeString function = "3D-Surface";
  CATISpecObject* piSpecFather = NULL;
  CATISpecObject_var spSpec = this;
  CATIGSMPlane_var spPlane = this;
  if( !!spPlane && !!spSpec )
  {
    cerr << spSpec->GetName() << endl;
    function = "3D-Plane";
    isPlane = TRUE;
  }
  CATIAlias_var spAlias = this;
  if( !!spAlias )
  {
    m_Alias = spAlias->GetAlias();
  }

  CATBody_var spBody;
  CATIGeometricalElement_var spGeomElm = this;
  if( !!spGeomElm )
  {
    spBody = spGeomElm->GetBodyResult();
  }

  CATUnicodeString coordinates;
  if( isPlane )
  {
    this->tessBody(spBody, coordinates);
  }
  else
  {
    this->getPointsCloud(spBody, coordinates);
  }

  CATUnicodeString count_points;
  count_points.BuildFromNum(m_CountPoints);

  o_rInfo.Append("[\n{");
  o_rInfo.Append("\"id\":\"" + m_Alias + "\",");
  o_rInfo.Append("\"document\":\"This is a 3D point cloud representing a surface with " + count_points + " points. The points define a curved surface generated by PointNet.\",");
  o_rInfo.Append("\"metadata\": {\"name\": \"" + m_Alias + "\",\"function\": \"3D-Surface\",\"source\": \"pointnet\",\"format\": \"pointcloud\",\"points\": [\n");
  o_rInfo.Append(coordinates);
  o_rInfo.Append("]\n}\n}\n]");

  return S_OK;
} // getInfo


//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::doIt(void)
{
  HRESULT hr = E_FAIL;
  cerr << "NOT IMPLEMENTED: " << __FUNCTION__ << endl;
  return hr;
} // doIt


//-------------------------------------------------------------------------
// getPointsCloud
//-------------------------------------------------------------------------
void TCAEUTLGoGSMBiDim::getPointsCloud(CATBody_var i_spBody, CATUnicodeString& o_rCoordinates)
{
  m_CountPoints = 0;
  o_rCoordinates = "";
  if( i_spBody == NULL_var || m_spThis == NULL_var )
  {
    return;
  }

  CATListOfDouble listX, listY, listZ;
  this->getPointsOnSurfInUVDirWithConstDist(i_spBody, 10.0, 10.0, listX, listY, listZ);

  int cnt1 = listX.Size();
  int cnt2 = listY.Size();
  int cnt3 = listZ.Size();

  if( cnt1 != cnt2 || cnt2 != cnt3 )
  {
    return;
  }

  m_CountPoints = cnt1;

  m_spThis->setOutput(m_CountPoints);

  for( int j = 1; j <= m_CountPoints; j++ )
  {
    // this->createDatumPoint(CATMathPoint(listX[j], listY[j], listZ[j]));

    CATUnicodeString xStr, yStr, zStr;
    xStr.BuildFromNum(listX[j]);
    yStr.BuildFromNum(listY[j]);
    zStr.BuildFromNum(listZ[j]);
    xStr.ReplaceAll(",", ".");
    yStr.ReplaceAll(",", ".");
    zStr.ReplaceAll(",", ".");
    if( o_rCoordinates != "" )
    {
      o_rCoordinates.Append(",\n");
    }
    o_rCoordinates.Append("{ \"x\":" + xStr + ",  \"y\":" + yStr + ",  \"z\":" + zStr + "}");
  }
  return;
} // tessBody


//-------------------------------------------------------------------------
// tessBody
//-------------------------------------------------------------------------
void TCAEUTLGoGSMBiDim::tessBody(CATBody_var i_spBody, CATUnicodeString& o_rCoordinates)
{
  o_rCoordinates = "";
  if( i_spBody == NULL_var )
  {
    return;
  }

  CATBody* piBody = NULL;
  HRESULT hr = i_spBody->QueryInterface(IID_CATBody, (void**)&piBody);
  CATGeoFactory* piGeoFact = i_spBody->GetContainer();
  if( piBody && piGeoFact )
  {
    double sag = 0.1;
    CATBodyTessellator* pTess = new CATBodyTessellator(piBody, sag);
    if( pTess )
    {
      pTess->Run();

      //-----------------------------------------------------------------------------
      // 4- Gets the results
      //-----------------------------------------------------------------------------
      CATBoolean isPlanar;
      CATTessPointIter* pVertices = NULL;
      CATTessStripeIter* pStrips = NULL;
      CATTessFanIter* pFans = NULL;
      CATTessPolyIter* pPolygons = NULL;
      CATTessTrianIter* pTriangles = NULL;

      float  (*aCoord)[3] = NULL;
      int* aNuPts = NULL;
      CATLine* piln = NULL;

      CATLISTP(CATCell) faces;
      piBody->GetAllCells(faces, 2);
      int numberOfFaces = faces.Size();

      for( int i = 1; i <= numberOfFaces; i++ )
      {
        CATFace* piFace = (CATFace*)faces[i];
        pTess->GetFace(piFace, isPlanar, &pVertices, &pStrips, &pFans, &pPolygons, &pTriangles);

        if( NULL != pVertices )
        {
          CATLONG32 nbp = pVertices->GetNbPoint();
          aCoord = new float[nbp][3];
          pVertices->GetPointXyzAll(aCoord);

          for( int j = 0; j < nbp; j++ )
          {
            this->createDatumPoint(CATMathPoint(aCoord[j][0], aCoord[j][2], aCoord[j][3]));

            CATUnicodeString xStr, yStr, zStr;
            xStr.BuildFromNum(aCoord[j][0]);
            yStr.BuildFromNum(aCoord[j][1]);
            zStr.BuildFromNum(aCoord[j][2]);
            xStr.ReplaceAll(",", ".");
            yStr.ReplaceAll(",", ".");
            zStr.ReplaceAll(",", ".");
            if( o_rCoordinates != "" )
            {
              o_rCoordinates.Append(", ");
            }
            o_rCoordinates.Append(xStr + ", " + yStr + ", " + zStr);
          }

        }
        delete[] aCoord;
        aCoord = NULL;
      }
      delete pTess;
      pTess = NULL;
    }
    piBody->Release();
    piBody = NULL;
  }
  return;
} // tessBody


//-----------------------------------------------------------------------------
// TCACreateDatumPoint
//-----------------------------------------------------------------------------
CATISpecObject_var TCAEUTLGoGSMBiDim::createDatumPoint(const CATMathPoint& i_rPnt1)
{
  CATISpecObject_var spSpecDatum;
  if( !!m_spDatumFactory && !!m_spGeoFactory )
  {
    CATSoftwareConfiguration* pConfig = new CATSoftwareConfiguration();
    CATTopData topData(pConfig, NULL);

    CATBody* pPntBody1 = CATCreateTopPointXYZ(m_spGeoFactory, &topData, i_rPnt1.GetX(), i_rPnt1.GetY(), i_rPnt1.GetZ());
    if( pPntBody1 )
    {
      CATListValCATBaseUnknown_var objToBeEncapsulated;
      objToBeEncapsulated.Append(pPntBody1);
      spSpecDatum = m_spDatumFactory->InstanciateDatum(&objToBeEncapsulated);
      if( !!spSpecDatum )
      {
        spSpecDatum->Update();
      }
    }
  }
  CATIAlias_var spAlias = spSpecDatum;
  if( !!spAlias )
  {
    spAlias->SetAlias(m_Alias);
  }
  return spSpecDatum;
} // TCACreateDatumPoint

//-----------------------------------------------------------------------------
// initFactories
//-----------------------------------------------------------------------------
void TCAEUTLGoGSMBiDim::initFactories(void)
{
  CATIContainerOfDocument_var spContainerOfDocument;
  CATILinkableObject_var spLink = this;
  if( !!spLink )
  {
    CATDocument* pDocument = spLink->GetDocument();
    if( pDocument )
    {
      CATIContainerOfDocument* piContainerOfDocument = NULL;
      pDocument->QueryInterface(IID_CATIContainerOfDocument, (void**)&piContainerOfDocument);
      if( piContainerOfDocument )
      {
        spContainerOfDocument = piContainerOfDocument;
        piContainerOfDocument->Release();
        piContainerOfDocument = NULL;
      }
    }
  }
  if( !!spContainerOfDocument )
  {
    CATIContainer* piContainer = NULL;
    spContainerOfDocument->GetSpecContainer(piContainer);
    if( NULL != piContainer )
    {
      m_spDatumFactory = piContainer;
      piContainer->Release();
      piContainer = NULL;
    }
    CATIContainer* piGeoContainer = NULL;
    spContainerOfDocument->GetResultContainer(piGeoContainer);
    if( NULL != piGeoContainer )
    {
      m_spGeoFactory = piGeoContainer;
      piGeoContainer->Release();
      piGeoContainer = NULL;
    }
  }
  return;
} // initFactories

//-------------------------------------------------------------------------
// getPointsOnFaceInUVDirWithConstDist
//-------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::getPointsOnSurfInUVDirWithConstDist(CATBody_var i_spBodySurf,
                                                               double i_distanceU,
                                                               double i_distanceV,
                                                               CATListOfDouble& o_rListXCoord,
                                                               CATListOfDouble& o_rListYCoord,
                                                               CATListOfDouble& o_rListZCoord)
{
  HRESULT hr = S_OK;
  if( i_spBodySurf == NULL_var )
  {
    return E_FAIL;
  }

  int indDom = 1;
  HRESULT hr1 = S_OK;
  for( indDom = 1; indDom <= i_spBodySurf->GetNbDomains(); indDom++ )
  {
    CATDomain_var spDomain = i_spBodySurf->GetDomain(indDom);
    if( spDomain == NULL_var )
      continue;

    int indCell = 1;
    int nbCellUse = spDomain->GetNbCellUses();
    for( indCell = 1; indCell <= nbCellUse; indCell++ )
    {

      CATTry
      {
        hr1 = this->getPointsOnFaceInUVDirWithConstDist(i_spBodySurf,
                                                        indDom,
                                                        indCell,
                                                        i_distanceU,
                                                        i_distanceV,
                                                        o_rListXCoord,
                                                        o_rListYCoord,
                                                        o_rListZCoord);
      }
        CATCatch(CATError, pError)
      {
        cerr << pError->GetNLSMessage() << endl;
        delete pError;
        hr = E_FAIL;
      }
      CATEndTry;
      if( FAILED(hr1) )
        hr = hr1;
    }
  }

  return hr;
}// getPointsOnSurfInUVDirWithConstDist

//-------------------------------------------------------------------------
// getPointsOnFaceInUVDirWithConstDist
//-------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::getPointsOnFaceInUVDirWithConstDist(CATBody_var i_spBodySurf,
                                                               int i_indexDomain,
                                                               int i_indexCell,
                                                               double i_distanceU,
                                                               double i_distanceV,
                                                               CATListOfDouble& o_rListXCoord,
                                                               CATListOfDouble& o_rListYCoord,
                                                               CATListOfDouble& o_rListZCoord)
{
  HRESULT hr = S_OK;
  if( i_spBodySurf == NULL_var ||
     i_distanceU < TCA_PWP_TOL ||
     i_distanceV < TCA_PWP_TOL ||
     m_spGeoFactory == NULL_var )
  {

    return E_FAIL;
  }

  int nrDomains = i_spBodySurf->GetNbDomains();
  if( i_indexDomain < 1 || i_indexDomain > nrDomains )
  {

    return E_FAIL;
  }

  CATDomain_var spDomain = i_spBodySurf->GetDomain(i_indexDomain);
  if( spDomain == NULL_var )
  {

    return E_FAIL;
  }

  int nrCells = spDomain->GetNbCellUses();
  if( i_indexCell < 1 || i_indexCell > nrCells )
  {

    return E_FAIL;
  }

  CATFace_var spFace = spDomain->GetCell(i_indexCell);
  if( spFace == NULL_var )
  {

    return E_FAIL;
  }

  CATOrientation  orientation = CATOrientationUnknown;
  CATSurface_var spSurface = spFace->GetSurface(&orientation);
  if( spSurface == NULL_var )
  {
    return E_FAIL;
  }

  //retrieve the 2D bounding box of this CATFace on its surface.
  //------------------------------------------------------------
  CATSurLimits surLimits2DBB;
  surLimits2DBB = *( spFace->Get2DBoundingBox() );

  //retrieve the low parameter of this CATFace
  //------------------------------------------
  CATSurParam surLowParam;
  surLimits2DBB.GetLow(surLowParam);

  // get old limits
  //---------------
  CATSurLimits oldSurlimits;
  spSurface->GetLimits(oldSurlimits);

  // set the limits of the selected surface as the same as the face
  //---------------------------------------------------------------
  spSurface->SetLimits(surLimits2DBB);

  // create an isoparametric curve on this CATSurface in direction U 
  //----------------------------------------------------------------
  CATCurve_var spIsoCurveU = spSurface->ExtractIsoParametricCurve(CATIsoParamU,
                                                                  surLowParam,
                                                                  m_spGeoFactory);
  if( spIsoCurveU == NULL_var )
  {
    spSurface->SetLimits(oldSurlimits);

    return E_FAIL;
  }

  CATListOfDouble listXCoordU;
  CATListOfDouble listYCoordU;
  CATListOfDouble listZCoordU;
  hr = this->getPointsOnCATCurveWithConstDist(spIsoCurveU, i_distanceU,
                                              listXCoordU, listYCoordU, listZCoordU);
  if( FAILED(hr) ||
     listXCoordU.Size() != listYCoordU.Size() ||
     listXCoordU.Size() != listZCoordU.Size() )
  {
    spSurface->SetLimits(oldSurlimits);

    return E_FAIL;
  }

  double tolerance = 0.001;
  double distPtToSurf = 0.;

  CATMathPoint mathPtU;
  CATMathPoint mathPtV;
  CATListOfDouble listXCoordV;
  CATListOfDouble listYCoordV;
  CATListOfDouble listZCoordV;
  CATCurve_var spIsoCurveV = NULL_var;

  CATBody_var spBodyPoint = NULL_var;
  CATPoint_var spCATPoint = NULL_var;
  CATSurParam paramNextIsoCrv;
  double distance = 0.;

  int i = 1;
  CATUnicodeString errMsg = "";
  for( i = 1; i <= listXCoordU.Size(); i++ )
  {
    mathPtU.SetCoord(listXCoordU[i], listYCoordU[i], listZCoordU[i]);

    spBodyPoint = this->createTopPoint(m_spGeoFactory, mathPtU);
    if( spBodyPoint == NULL_var )
      continue;

    spCATPoint = this->getCATPointOfBody(spBodyPoint);
    if( spCATPoint != NULL_var )
    {
      hr = this->createGeomProjection(m_spGeoFactory, spCATPoint,
                                      spSurface, surLimits2DBB,
                                      distance, paramNextIsoCrv, errMsg);
    }

    // remove the created CATBody of point from GeoFactory:
    m_spGeoFactory->Remove(spBodyPoint);

    if( FAILED(hr) )
      continue;

    // iso curve in V direction
    //-------------------------
    spIsoCurveV = spSurface->ExtractIsoParametricCurve(CATIsoParamV,
                                                       paramNextIsoCrv,
                                                       m_spGeoFactory);
    if( spIsoCurveV == NULL_var )
      continue;

    listXCoordV.Size(0);
    listYCoordV.Size(0);
    listZCoordV.Size(0);
    hr = this->getPointsOnCATCurveWithConstDist(spIsoCurveV, i_distanceV,
                                                listXCoordV, listYCoordV, listZCoordV);
    if( FAILED(hr) ||
       listXCoordV.Size() != listYCoordV.Size() ||
       listXCoordV.Size() != listZCoordV.Size() ) continue;

    int j = 1;
    for( j = 1; j <= listXCoordV.Size(); j++ )
    {
      mathPtV.SetCoord(listXCoordV[j], listYCoordV[j], listZCoordV[j]);

      //call method to check if the point to create lies on the current cell
      //--------------------------------------------------------------------
      HRESULT hr = this->getDistanceOfCATMathPointToSurf(m_spGeoFactory, i_spBodySurf,
                                                         mathPtV, FALSE,
                                                         distPtToSurf, errMsg);
      if( FAILED(hr) ) continue;

      if( fabs(distPtToSurf) < tolerance )
      {
        // add point
        o_rListXCoord.Append(mathPtV.GetX());
        o_rListYCoord.Append(mathPtV.GetY());
        o_rListZCoord.Append(mathPtV.GetZ());
      }
    }// for( j = 1;

  }// for( i = 1;

  // set old limits
  //---------------
  spSurface->SetLimits(oldSurlimits);

  return hr;
}// getPointsOnFaceInUVDirWithConstDist

//-------------------------------------------------------------------------
// getPointsOnCATCurveWithConstDist
//-------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::getPointsOnCATCurveWithConstDist(CATCurve_var i_spCurve,
                                                            double i_distance,
                                                            CATListOfDouble& o_rListXCoord,
                                                            CATListOfDouble& o_rListYCoord,
                                                            CATListOfDouble& o_rListZCoord)
{
  HRESULT hr = S_OK;
  double tolerance = 0.001;
  if( i_spCurve == NULL_var || i_distance < tolerance )
  {

    return E_FAIL;
  }

  CATCrvParam  crvStartParam;
  CATCrvLimits crvLimit;
  i_spCurve->GetLimits(crvLimit);
  crvLimit.GetLow(crvStartParam);

  double length = 0.;
  hr = this->getLengthOfCATCurve(i_spCurve, length);
  if( FAILED(hr) )
  {

    return hr;
  }

  CATMathPoint mathPt;
  CATCrvParam paramNextPt;

  if( length < i_distance || fabs(length - i_distance) < tolerance )
  {
    hr = this->getParamFromLengthOnCATCurve(i_spCurve, crvStartParam, 0., paramNextPt);
    if( FAILED(hr) )
    {

      return E_FAIL;
    }

    CATCrvEvalLocal EvalResult;
    i_spCurve->Eval(paramNextPt, CATCrvEvalCommand::EvalPoint, EvalResult);
    EvalResult.GetPoint(mathPt);

    // add point
    o_rListXCoord.Append(mathPt.GetX());
    o_rListYCoord.Append(mathPt.GetY());
    o_rListZCoord.Append(mathPt.GetZ());

    hr = this->getParamFromLengthOnCATCurve(i_spCurve, crvStartParam, length, paramNextPt);
    if( FAILED(hr) )
    {

      return E_FAIL;
    }

    i_spCurve->Eval(paramNextPt, CATCrvEvalCommand::EvalPoint, EvalResult);
    EvalResult.GetPoint(mathPt);

    // add point
    o_rListXCoord.Append(mathPt.GetX());
    o_rListYCoord.Append(mathPt.GetY());
    o_rListZCoord.Append(mathPt.GetZ());
  }
  else
  {
    double currDist = 0.;
    while( currDist < length || fabs(currDist - length) < tolerance )
    {
      hr = this->getParamFromLengthOnCATCurve(i_spCurve, crvStartParam, currDist, paramNextPt);
      if( SUCCEEDED(hr) )
      {
        CATCrvEvalLocal EvalResult;
        i_spCurve->Eval(paramNextPt, CATCrvEvalCommand::EvalPoint, EvalResult);

        EvalResult.GetPoint(mathPt);

        // add point
        o_rListXCoord.Append(mathPt.GetX());
        o_rListYCoord.Append(mathPt.GetY());
        o_rListZCoord.Append(mathPt.GetZ());
      }

      currDist += i_distance;
    }

    // add end
    if( currDist > length && fabs(currDist - length) > tolerance )
    {
      hr = this->getParamFromLengthOnCATCurve(i_spCurve, crvStartParam, length, paramNextPt);
      if( FAILED(hr) )
      {

        return E_FAIL;
      }

      CATCrvEvalLocal EvalResult;
      i_spCurve->Eval(paramNextPt, CATCrvEvalCommand::EvalPoint, EvalResult);

      EvalResult.GetPoint(mathPt);

      // add point
      o_rListXCoord.Append(mathPt.GetX());
      o_rListYCoord.Append(mathPt.GetY());
      o_rListZCoord.Append(mathPt.GetZ());
    }

  }

  return hr;
}// getPointsOnCATCurveWithConstDist


//-------------------------------------------------------------------------
// createTopPoint
//-------------------------------------------------------------------------
CATBody_var TCAEUTLGoGSMBiDim::createTopPoint(CATGeoFactory_var i_spGeoFactory,
                                              CATMathPoint i_mathPoint)
{
  CATBody_var spBody = NULL_var;
  if( i_spGeoFactory == NULL_var ) return spBody;

  CATSoftwareConfiguration* piConfig = new CATSoftwareConfiguration();
  if( piConfig == NULL ) return spBody;
  CATTopData topData = CATTopData(piConfig);

  spBody = ::CATCreateTopPointXYZ(i_spGeoFactory,
                                  &topData,
                                  i_mathPoint.GetX(),
                                  i_mathPoint.GetY(),
                                  i_mathPoint.GetZ());

  piConfig->Release();
  piConfig = NULL;

  return spBody;
}// createTopPoint

//-------------------------------------------------------------------------
// getCATPointOfBody
//-------------------------------------------------------------------------
CATPoint_var TCAEUTLGoGSMBiDim::getCATPointOfBody(CATBody_var i_spBody)
{
  CATPoint_var spPoint = NULL_var;
  if( i_spBody == NULL_var ) return spPoint;

  if( this->getCellsHighestDimension(i_spBody) != 0 )
    return spPoint;

  CATLISTP(CATCell) listCells;
  i_spBody->GetAllCells(listCells, 0);
  if( listCells.Size() == 0 ) return spPoint;

  CATVertex_var spVertex = listCells[1];
  if( spVertex == NULL_var ) return spPoint;

  spPoint = spVertex->GetPoint();

  return spPoint;
}// getCATPointOfBody

//-------------------------------------------------------------------------
// getCellsHighestDimension
//-------------------------------------------------------------------------
CATLONG32 TCAEUTLGoGSMBiDim::getCellsHighestDimension(CATBody_var i_spBody)
{
  CATLONG32 cellsHighestDim = 0;
  if( i_spBody == NULL_var ) return cellsHighestDim;
  CATBoolean ioIsHomogeneous;
  i_spBody->GetCellsHighestDimension(cellsHighestDim, ioIsHomogeneous);
  return cellsHighestDim;
}// getCellsHighestDimension

//-------------------------------------------------------------------------
// this->createGeomProjection
//-------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::createGeomProjection(CATGeoFactory_var i_spGeoFactory,
                                                CATPoint_var i_spPoint,
                                                CATSurface_var i_spSurface,
                                                CATSurLimits i_useSurLimits,
                                                double& o_distance,
                                                CATSurParam& o_surParam,
                                                CATUnicodeString& o_rErrMsg)
{
  HRESULT hr = S_OK;
  o_distance = 0.;

  if( i_spSurface == NULL_var || i_spPoint == NULL_var || i_spGeoFactory == NULL_var )
  {
    return E_FAIL;
  }
  // Defines an open configuration for the operator
  //-----------------------------------------------
  CATSoftwareConfiguration* pConfig = new CATSoftwareConfiguration();
  if( pConfig == NULL ) return E_FAIL;

  CATSurface* piSurface = NULL;
  i_spSurface->QueryInterface(IID_CATSurface, (void**)&piSurface);
  if( piSurface != NULL )
  {
    CATPoint* piPoint = NULL;
    i_spPoint->QueryInterface(IID_CATPoint, (void**)&piPoint);
    if( piPoint != NULL )
    {
      CATTry
      {
        CATProjectionPtSur * piProjPtSur = ::CATCreateProjection(i_spGeoFactory,
          pConfig,
          piPoint,
          piSurface,
          NULL,
          ADVANCED);
        if( piProjPtSur != NULL )
        {
          piProjPtSur->UseLimits(&i_useSurLimits);
          piProjPtSur->Run();

          if( piProjPtSur->GetNumberOfPoints() == 0 )
            hr = E_FAIL;
          else
          {
            CATSurParam param;
            double dist = 0.;
            CATBoolean first = TRUE;
            while( piProjPtSur->NextPoint() )
            {
              param = piProjPtSur->GetParam();
              dist = piProjPtSur->GetDistance();

              if( fabs(dist) < fabs(o_distance) || first )
              {
                o_distance = dist;
                o_surParam = param;
                first = FALSE;
              }// fabs( dist ) < fabs( minDist )

            }// while( piProjPtSur->NextPoint() == TRUE )
          }// if( piProjPtSur->GetNumberOfPoints() == 0 )

          delete piProjPtSur;
          piProjPtSur = NULL;
        }// if( piProjPtSur != NULL )
      }
        CATCatch(CATError, pError)
      {
        o_rErrMsg = pError->GetNLSMessage();
        delete pError;
        hr = E_FAIL;
      }
      CATEndTry;

      piPoint->Release();
      piPoint = NULL;
    }// if( piPoint != NULL )

    piSurface->Release();
    piSurface = NULL;
  }// if( piSurface != NULL )

  pConfig->Release();
  pConfig = NULL;

  return hr;
}// this->createGeomProjection 

//-------------------------------------------------------------------------
// this->getDistanceOfCATMathPointToSurf
//-------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::getDistanceOfCATMathPointToSurf(CATGeoFactory_var i_spGeoFactory,
                                                           CATBody_var i_spCATBodySur,
                                                           CATMathPoint i_mathPt,
                                                           CATBoolean i_ifProjectable,
                                                           double& o_rDist,
                                                           CATUnicodeString& o_rErrMsg)
{
  HRESULT hr = S_OK;

  //check input i_Data
  //----------------
  if( i_spGeoFactory == NULL_var ||
     i_spCATBodySur == NULL_var ) return E_FAIL;

  //create a topological point body from CATMathPoint
  //------------------------------------------------------
  CATBody_var spBodyPt = this->createTopPoint(i_spGeoFactory, i_mathPt);
  if( spBodyPt == NULL_var ) return E_FAIL;

  if( i_ifProjectable )
  {
    CATBody_var spBodyProj = this->createTopProjection(i_spGeoFactory, i_spCATBodySur, spBodyPt, o_rErrMsg);
    if( spBodyProj == NULL_var )
      hr = E_FAIL;
    else i_spGeoFactory->Remove(spBodyProj);
  }

  if( SUCCEEDED(hr) )
  {
    hr = this->getDistanceMinTopo(i_spGeoFactory,
                                  i_spCATBodySur,
                                  spBodyPt,
                                  o_rDist,
                                  o_rErrMsg);
  }

  i_spGeoFactory->Remove(spBodyPt);

  return hr;
}//this->getDistanceOfCATMathPointToSurf



//-------------------------------------------------------------------------
// thisthis->getLengthOfCATCurve
//-------------------------------------------------------------------------
HRESULT  TCAEUTLGoGSMBiDim::getLengthOfCATCurve(CATCurve_var i_spCurve, double& o_rLength)
{
  HRESULT hr = E_FAIL;
  if( !!i_spCurve )
  {
    CATSoftwareConfiguration* pSoftConfig = new CATSoftwareConfiguration();
    if( pSoftConfig )
    {
      CATCurve* piCurve = NULL;
      i_spCurve->QueryInterface(IID_CATCurve, (void**)&piCurve);
      if( piCurve )
      {
        CATDynMassProperties1D* pDynMassProp1D = CATDynCreateMassProperties1D(piCurve, pSoftConfig);
        if( pDynMassProp1D )
        {
          hr = S_OK;
          o_rLength = pDynMassProp1D->GetLength();
          delete pDynMassProp1D;
          pDynMassProp1D = NULL;
        }
        piCurve->Release();
        piCurve = NULL;
      }
      pSoftConfig->Release();
      pSoftConfig = NULL;
    }
  }
  return hr;
}// thisthis->getLengthOfCATCurve

//-------------------------------------------------------------------------
// this->getParamFromLengthOnCATCurve
//-------------------------------------------------------------------------
HRESULT TCAEUTLGoGSMBiDim::getParamFromLengthOnCATCurve(CATCurve_var i_spCurve, CATCrvParam i_startParam, double i_lengthOnCurve, CATCrvParam& o_rCrvParam)
{
  HRESULT hr = E_FAIL;
  if( !!i_spCurve )
  {
    CATCurve* piCurve = NULL;
    i_spCurve->QueryInterface(IID_CATCurve, (void**)&piCurve);
    if( piCurve )
    {
      CATSoftwareConfiguration* pSoftConfig = new CATSoftwareConfiguration();
      if( pSoftConfig )
      {
        CATDynMassProperties1D* pDynMassProp1D = CATDynCreateMassProperties1D(piCurve, pSoftConfig);
        if( pDynMassProp1D )
        {
          hr = S_OK;
          o_rCrvParam = pDynMassProp1D->GetParamFromLength(i_startParam, i_lengthOnCurve);
          delete pDynMassProp1D;
          pDynMassProp1D = NULL;
        }
        pSoftConfig->Release();
        pSoftConfig = NULL;
      }
      piCurve->Release();
      piCurve = NULL;
    }
  }
  return hr;
}// this->getParamFromLengthOnCATCurve


//-------------------------------------------------------------------------
// this->createTopProjection
//-------------------------------------------------------------------------
CATBody_var TCAEUTLGoGSMBiDim::createTopProjection(CATGeoFactory_var i_spGeoFactory,
                                                   CATBody_var i_spBodySupport,
                                                   CATBody_var i_spBodyToProj,
                                                   CATUnicodeString& o_rErrMsg)
{
  CATBody_var spResultBody = NULL_var;
  if( i_spBodySupport == NULL_var ||
     i_spBodyToProj == NULL_var ||
     i_spGeoFactory == NULL_var ) return spResultBody;

  CATSoftwareConfiguration* pSoftConfig = new CATSoftwareConfiguration();
  if( pSoftConfig == NULL ) return spResultBody;
  CATTopData topData(pSoftConfig, NULL);

  CATBody* piBodySupport = NULL;
  i_spBodySupport->QueryInterface(IID_CATBody, (void**)&piBodySupport);
  if( piBodySupport != NULL )
  {
    CATBody* piBodyToProj = NULL;
    i_spBodyToProj->QueryInterface(IID_CATBody, (void**)&piBodyToProj);
    if( piBodyToProj != NULL )
    {
      CATTry
      {
        // create topological operator that projects a body on another one.
        //-----------------------------------------------------------------
        CATHybProject * pProjectionOperator = ::CATCreateTopProject(i_spGeoFactory,
          &topData,
          piBodyToProj,
          piBodySupport,
          NULL);
        if( pProjectionOperator != NULL )
        {
          //run the operator
          pProjectionOperator->Run();

          //retrieve result of projection
          spResultBody = pProjectionOperator->GetResult();

          //delete operator for projection
          delete pProjectionOperator;
          pProjectionOperator = NULL;
        }
      }
        CATCatch(CATError, pError)
      {
        o_rErrMsg = pError->GetNLSMessage();
        delete pError;
      }
      CATEndTry;

      piBodyToProj->Release();
      piBodyToProj = NULL;
    }// if( piBodyToProj != NULL )

    piBodySupport->Release();
    piBodySupport = NULL;
  }// if( piBodySupport != NULL )

  // Release the configuration after the deletion of the operator
  pSoftConfig->Release();
  pSoftConfig = NULL;

  return spResultBody;
}// this->createTopProjection


//---------------------------------------------------------------------------
// this->getDistanceMinTopo
//---------------------------------------------------------------------------
HRESULT  TCAEUTLGoGSMBiDim::getDistanceMinTopo(CATGeoFactory_var i_spGeoFactory,
                                               CATBody_var i_spCATBody1,
                                               CATBody_var i_spCATBody2,
                                               double& o_rMinDistance,
                                               CATUnicodeString& o_rErrMsg)
{
  HRESULT hr = S_OK;

  if( i_spCATBody1 == NULL_var ||
     i_spCATBody2 == NULL_var ||
     i_spGeoFactory == NULL_var ) return E_FAIL;

  // Defines an open configuration for the operator
  //-----------------------------------------------
  CATSoftwareConfiguration* pConfig = new CATSoftwareConfiguration();
  if( pConfig == NULL ) return E_FAIL;

  // defines the i_Data of the operator: configuration + journal
  //----------------------------------------------------------
  CATTopData topData(pConfig, NULL);

  CATBody* piBody1 = NULL;
  i_spCATBody1->QueryInterface(IID_CATBody, (void**)&piBody1);
  if( piBody1 != NULL )
  {
    CATBody* piBody2 = NULL;
    i_spCATBody2->QueryInterface(IID_CATBody, (void**)&piBody2);
    if( piBody2 != NULL )
    {
      CATDistanceMinBodyBody* piDistMinTopOp = ::CATCreateDistanceMinTopo(i_spGeoFactory,
                                                                          &topData,
                                                                          piBody1,
                                                                          piBody2,
                                                                          ADVANCED);
      if( piDistMinTopOp != NULL )
      {
        CATTry
        {
          piDistMinTopOp->Run();
          o_rMinDistance = piDistMinTopOp->GetDistance();
        }
          CATCatch(CATError, pError)
        {
          o_rErrMsg = pError->GetNLSMessage();
          delete pError;
          hr = E_FAIL;
        }
        CATEndTry;

        delete piDistMinTopOp;
        piDistMinTopOp = NULL;
      }// if( piDistMinTopOp != NULL )

      piBody2->Release();
      piBody2 = NULL;
    }// if( piBody2 != NULL )

    piBody1->Release();
    piBody1 = NULL;
  }// if( piBody1 != NULL )

  return hr;
}// this->getDistanceMinTopo