// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoMeasureFenderChargingFlap.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGoMeasureFenderChargingFlap.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATScriptUtilities.h"
#include "CATAutoConversions.h"
#include "CATAfrCommandHeaderServices.h"
#include <stdlib.h>

TCA_UTL_COMPONENT_CPP(UTLGoMeasureFenderChargingFlap)

CATImplementClass(TCAEUTLGoMeasureFenderChargingFlap,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGoMeasureFenderChargingFlap);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoMeasureFenderChargingFlap);

//-----------------------------------------------------------------------------
// TCAEUTLGoMeasureFenderChargingFlap : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoMeasureFenderChargingFlap::TCAEUTLGoMeasureFenderChargingFlap()
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
}

//-----------------------------------------------------------------------------
// TCAEUTLGoMeasureFenderChargingFlap : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoMeasureFenderChargingFlap::~TCAEUTLGoMeasureFenderChargingFlap()
{}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoMeasureFenderChargingFlap::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Finds vehicle fender that contains the charging-port opening and measure its geometry. Inspects fender with charging flap. Find and measure fender with cut-out for charging socket.";
  o_rInfo.Append("Findet den Fahrzeugkotfluegel, der den Auschnitt fuer die Ladebuchse enthaelt, und vermisst dessen Geometrie. ");
  o_rInfo.Append("Analysiere den Kotfluegel mit der Ladeklappe. ");
  o_rInfo.Append("Findet und vermisst den Kotfluegel mit der Aussparung fuer die Ladesteckdose. ");
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoMeasureFenderChargingFlap::doIt(void)
{
  m_spSpecPbject = TCAUTLGetSelectedElement();
  if( m_spThis == NULL_var || m_spSingleTon == NULL_var || m_spSpecPbject == NULL_var )
  {
    return E_FAIL;
  }
  cerr << TCAUTLGetAlias(m_spSpecPbject) << endl;
  HRESULT hr = E_FAIL;
  CATCommand* pCmd = NULL;
  CATAfrStartCommand("MeasureFenderChargingFlap", pCmd);
  if( pCmd )
  {
    pCmd = NULL;
    hr = S_OK;
  }
  return hr;
} // doIt

