// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGoAskAI.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGoAskAI.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATScriptUtilities.h"
#include "CATAutoConversions.h"
#include "CATAfrCommandHeaderServices.h"
#include <stdlib.h>
#include <iostream>
#include <cstring>

TCA_UTL_COMPONENT_CPP(UTLGoAskAI)

CATImplementClass(TCAEUTLGoAskAI,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGoAskAI);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGoAskAI);

//-----------------------------------------------------------------------------
// TCAEUTLGoAskAI : constructor
//-----------------------------------------------------------------------------
TCAEUTLGoAskAI::TCAEUTLGoAskAI()
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
  PyRun_SimpleString("import sys; sys.path.insert(0, 'C:\\EXAMPLES\\AI\\AskAI')");
}

//-----------------------------------------------------------------------------
// TCAEUTLGoAskAI : destructor
//-----------------------------------------------------------------------------
TCAEUTLGoAskAI::~TCAEUTLGoAskAI()
{
}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoAskAI::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Asks AI via python and returns answer as string";
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGoAskAI::doIt(void)
{
  HRESULT hr = E_FAIL;
  if( m_spThis == NULL_var || m_spSingleTon == NULL_var )
  {
    return E_FAIL;
  }
  m_spThis->getInput(m_PYModuleName, 1);
  m_spThis->getInput(m_PYFunctionName, 2);
  if( m_PYModuleName == "" || m_PYFunctionName == "" )
  {
    return E_FAIL;
  }
  PyObject* pMmodule = NULL;
  pMmodule = PyImport_ImportModule(m_PYModuleName.ConvertToChar());
  if( !pMmodule )
  {
    PyErr_Print();
    return E_FAIL;
  }
  PyObject* pFunc = NULL;
  pFunc = PyObject_GetAttrString(pMmodule, m_PYFunctionName.ConvertToChar());
  if( !pFunc || !PyCallable_Check(pFunc) )
  {
    PyErr_Print();
    std::cerr << "Cannot find function: " << m_PYFunctionName << endl;;
    return E_FAIL;
  }
  PyObject* arg4 = nullptr;
  PyObject* arg3 = nullptr;
  PyObject* arg2 = nullptr;
  PyObject* arg1 = nullptr;
  PyObject* args = nullptr;
  int argCnt = 0;
  m_spThis->getInput(argCnt, 1);
  if( argCnt > 0 )
  {
    if( argCnt == 4 )
    {
      this->getPYArgument(1, arg1);
      this->getPYArgument(2, arg2);
      this->getPYArgument(3, arg3);
      this->getPYArgument(4, arg4);
      args = PyTuple_Pack(4, arg1, arg2, arg3, arg4);
    }
    else if( argCnt == 3 )
    {
      this->getPYArgument(1, arg1);
      this->getPYArgument(2, arg2);
      this->getPYArgument(3, arg3);
      args = PyTuple_Pack(3, arg1, arg2, arg3);
    }
    else if( argCnt == 2 )
    {
      this->getPYArgument(1, arg1);
      this->getPYArgument(2, arg2);
      args = PyTuple_Pack(2, arg1, arg2);
    }
    else if( argCnt == 1 )
    {
      this->getPYArgument(1, arg1);
      args = PyTuple_Pack(1, arg1);
    }
  }
  CATUnicodeString answerAI;
  PyObject* result = PyObject_CallObject(pFunc, args);
  if( result )
  {
    const char* result_utf8 = PyUnicode_AsUTF8(result);
    if( result_utf8 )
    {
      // answerAI = CATUnicodeString(result_utf8);
      size_t utf8Length = strlen(result_utf8);
      answerAI.BuildFromUTF8(result_utf8, utf8Length);
    }
    std::cout << "Python function returned: " << answerAI << "\n";
    Py_DECREF(result);
    m_spThis->setOutput(answerAI);
    hr = S_OK;
  }
  else
  {
    cerr << "FAILED to get PYTHON result" << endl;
    PyErr_Print();
  }
  if( arg1 != nullptr )
  {
    Py_DECREF(arg1);
  }
  if( arg2 != nullptr )
  {
    Py_DECREF(arg2);
  }
  if( arg3 != nullptr )
  {
    Py_DECREF(arg3);
  }
  if( arg4 != nullptr )
  {
    Py_DECREF(arg4);
  }
  if( arg4 != nullptr )
  {
    Py_DECREF(arg4);
  }
  if( args != nullptr )
  {
    Py_DECREF(args);
  }
  if( pFunc != nullptr )
  {
    Py_DECREF(pFunc);
  }
  if( pMmodule != nullptr )
  {
    Py_DECREF(pMmodule);
  }
  return hr;
} // doIt

//-----------------------------------------------------------------------------
// getPYArgument
//-----------------------------------------------------------------------------
void TCAEUTLGoAskAI::getPYArgument(const int i_rIdx, PyObject*& o_rPYArg)
{
  if( m_spThis == NULL_var || i_rIdx < 1 )
  {
    return;
  }
  CATUnicodeString argStr;
  int argIdx = i_rIdx + 2;
  m_spThis->getInput(argStr, argIdx);
  if( argStr != "" )
  {
    const char* cstr = argStr.ConvertToChar();
    o_rPYArg = PyUnicode_Decode(cstr, strlen(cstr), "utf-8", "strict");
  }
  if( o_rPYArg == nullptr )
  {
    PyErr_Print();
    std::cerr << "Error: Failed to create Python Unicode object: " << argStr << endl;
  }
  return;
} // getPYArgument