//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAEUTLGo.cpp
// Header definition of class TCAEUTLGo
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================

#include "iostream.h"
#include "TCAEUTLGo.h"
#include "TCAIUTLDoIt.h"
#include "TCAIUTLDoItMember.h"
#include "TCAXmlUtils.h"
#include "CATUuid.h"

CATBeginImplementClass(TCAEUTLGo,
                       DataExtension,
                       CATBaseUnknown,
                       UTLGoItem);

CATAddClassExtension(UTLSingleTon);
CATAddClassExtension(UTLGoExportJSON);
CATAddClassExtension(UTLGo3DPoint);
CATAddClassExtension(UTLGo3DLine);
CATAddClassExtension(UTLGo3DPlane);
CATAddClassExtension(UTLGoCreateCATPart);
CATAddClassExtension(UTLGoRenameObjects);
CATAddClassExtension(UTLGoMeasureFenderChargingFlap);
CATAddClassExtension(UTLGoAskAI);
CATAddClassExtension(UTLGoAssignContours);

CATAddClassExtension(GSMPoint);
CATAddClassExtension(GSMBiDim);


CATEndImplementClass(TCAEUTLGo);

TCA_UTL_COMPONENT_CPP(UTLSingleTon)

#include "TIE_TCAIUTLGo.h"
TIE_TCAIUTLGo(TCAEUTLGo);

//-----------------------------------------------------------------------------
// TCAEUTLGo : constructor
//-----------------------------------------------------------------------------
TCAEUTLGo::TCAEUTLGo() :CATBaseUnknown()
{}

//-----------------------------------------------------------------------------
// TCAEUTLGo : destructor
//-----------------------------------------------------------------------------
TCAEUTLGo::~TCAEUTLGo()
{
  m_Members.RemoveAll();
  m_InputMembers.RemoveAll();
  m_OutputMembers.RemoveAll();
}

//-----------------------------------------------------------------------------
// getUuid
//-----------------------------------------------------------------------------
CATUnicodeString TCAEUTLGo::getUuid(void)
{
  if( m_Uuid == "" )
  {
    CATUuid uuid;
    char* c = new char[255];
    uuid.UUID_to_chaine(c);
    m_Uuid = CATUnicodeString(c);
    delete[] c;
  }
  return m_Uuid;
} // getUuid

//-----------------------------------------------------------------------------
// getParentUuid
//-----------------------------------------------------------------------------
CATUnicodeString TCAEUTLGo::getParentUuid(void)
{
  return m_ParentUuid;
} // getParentUuid

//-----------------------------------------------------------------------------
// setParentUuid
//-----------------------------------------------------------------------------
void TCAEUTLGo::setParentUuid(const CATUnicodeString& i_rUuid)
{
  m_ParentUuid = i_rUuid;
  return;
} // setParentUuid

//-----------------------------------------------------------------------------
// addJLine
//-----------------------------------------------------------------------------
void TCAEUTLGo::addJLine(const CATUnicodeString& i_rToAdd)
{
  if( i_rToAdd == "" )
  {
    return;
  }
  if( m_JLine != "" )
  {
    m_JLine.Append(",");
  }
  m_JLine.Append(i_rToAdd);
  return;
} // addJLine

//-----------------------------------------------------------------------------
// getJLine
//-----------------------------------------------------------------------------
void TCAEUTLGo::getJLine(CATUnicodeString& o_rJLine)
{
  o_rJLine = m_JLine;
  return;
} // getJLine

//-----------------------------------------------------------------------------
// run
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::run(void)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoIt_var spDoIt = this;
  if( !!spDoIt )
  {
    this->resetOutputs();
    CATTry
    {
      hr = spDoIt->doIt();
    }
      CATCatch(CATError, pError)
    {
      hr = E_FAIL;
      cerr << "FAILED: " << __FUNCTION__ << " of " << this->GetImpl()->IsA() << endl;
      delete pError;
      pError = NULL;
    }
    CATEndTry;
  }
  return hr;
} // run

//-----------------------------------------------------------------------------
// resetOutputs
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::resetOutputs(void)
{
  m_OutputMembers.RemoveAll();
  return S_OK;
} // resetOutputs

//-----------------------------------------------------------------------------
// dump
//-----------------------------------------------------------------------------
void TCAEUTLGo::dump(void)
{
  int cnt = m_Members.Size();
  for( int i = 1; i <= cnt; i++ )
  {
    TCAIUTLDoItMember_var spMember = m_Members[i];
    if( !!spMember )
    {
      spMember->dump();
    }
  }
  return;
} // dump

//-----------------------------------------------------------------------------
// resetOutputs
//-----------------------------------------------------------------------------
void TCAEUTLGo::traceInputs(void)
{
  int cnt = m_InputMembers.Size();
  if( cnt > 0 )
  {

    for( int i = 1; i <= cnt; i++ )
    {
      TCAIUTLDoItMember_var spMember = m_InputMembers[i];
      if( !!spMember )
      {
        spMember->trace();
      }
    }

  }
  return;
} // traceInputs

//-----------------------------------------------------------------------------
// resetOutputs
//-----------------------------------------------------------------------------
void TCAEUTLGo::traceOutputs(void)
{
  int cnt = m_OutputMembers.Size();
  if( cnt > 0 )
  {

    for( int i = 1; i <= cnt; i++ )
    {
      TCAIUTLDoItMember_var spMember = m_OutputMembers[i];
      if( !!spMember )
      {
        spMember->trace();
      }
    }

  }
  return;
} // traceOutputs 

//-----------------------------------------------------------------------------
// getInputMember
//-----------------------------------------------------------------------------
CATBaseUnknown_var TCAEUTLGo::getInputMember(const int& i_rIdx)
{
  CATBaseUnknown_var spInputMember = NULL_var;
  if( i_rIdx < 1 )
  {
    return NULL_var;
  }

  int cnt = m_InputMembers.Size();
  while( cnt < i_rIdx )
  {
    CATBaseUnknown_var spInputMemberNew = TCAUTLInst("UTLDoItMember");
    if( !!spInputMemberNew )
    {
      m_InputMembers.Append(spInputMemberNew);
      cnt = m_InputMembers.Size();
    }
    else
    {
      break;
    }
  }

  if( cnt >= i_rIdx )
  {
    spInputMember = m_InputMembers[i_rIdx];
  }

  return spInputMember;
} // getInputMember

//-----------------------------------------------------------------------------
// getOutputMember
//-----------------------------------------------------------------------------
CATBaseUnknown_var TCAEUTLGo::getOutputMember(const int& i_rIdx)
{
  CATBaseUnknown_var spOutputMember = NULL_var;
  if( i_rIdx < 1 )
    return NULL_var;

  int cnt = m_OutputMembers.Size();
  if( cnt >= i_rIdx )
  {
    spOutputMember = m_OutputMembers[i_rIdx];
  }
  else
  {
    spOutputMember = TCAUTLInst("UTLDoItMember");
    if( !!spOutputMember )
    {
      m_OutputMembers.Append(spOutputMember);
    }
  }
  return spOutputMember;
} // getOutputMember

//-----------------------------------------------------------------------------
// getInOutMember
//-----------------------------------------------------------------------------
CATBaseUnknown_var TCAEUTLGo::getInOutMember(const int& i_rIdx)
{
  CATBaseUnknown_var spInOutMember;
  if( i_rIdx < 1 )
  {
    return NULL_var;
  }
  int cnt = m_InOutMembers.Size();
  if( cnt >= i_rIdx )
  {
    spInOutMember = m_InOutMembers[i_rIdx];
  }
  else
  {
    spInOutMember = TCAUTLInst("UTLDoItMember");
    if( !!spInOutMember )
    {
      m_InOutMembers.Append(spInOutMember);
    }
  }
  return spInOutMember;
} // getInOutMember

//-----------------------------------------------------------------------------
// getMembersRef
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getMembersRef(CATListValCATBaseUnknown_var& o_rListValue)
{
  o_rListValue = m_Members;
  return S_OK;
} // getMembersRef

//-----------------------------------------------------------------------------
// getMembers
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getMembers(CATListValCATBaseUnknown_var& o_rListValue)
{
  HRESULT hr = E_FAIL;
  o_rListValue.RemoveAll();
  for( int m = 1; m <= m_Members.Size(); m++ )
  {
    TCAIUTLDoItMember_var spMember = m_Members[m];
    if( !!spMember )
    {
      TCAIUTLDoItMember_var spMemberNew = TCAUTLInst("UTLDoItMember");
      if( !!spMemberNew )
      {
        o_rListValue.Append(spMemberNew);

        // name
        CATUnicodeString name;
        spMember->getName(name);
        spMemberNew->setName(name);

        // copy all values
        hr = spMemberNew->copyValuesFrom(spMember);
      }
    }
  }
  return S_OK;
} // getMembers

//-----------------------------------------------------------------------------
// setValueFrom
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::setValueFrom(const CATUnicodeString& i_rName, CATBaseUnknown_var i_spUTLGoFrom)
{
  HRESULT hr = E_FAIL;
  TCAIUTLGo_var spGoSrc = i_spUTLGoFrom;
  if( !!spGoSrc )
  {
    TCAIUTLDoItMember_var spMemberFrom = spGoSrc->getMemberByName(i_rName);
    if( !!spMemberFrom )
    {
      TCAIUTLDoItMember_var spMemberThis = this->addMember(i_rName);
      if( !!spMemberThis )
      {
        hr = spMemberThis->copyValuesFrom(spMemberFrom);
      }
    }
  }
  return hr;
} // setValueFrom

//-----------------------------------------------------------------------------
// copyMembersFrom
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::copyMembersFrom(CATBaseUnknown_var i_spUTLGoFrom)
{
  HRESULT hr = E_FAIL;
  m_Members.RemoveAll();
  TCAIUTLGo_var spGoSrc = i_spUTLGoFrom;
  if( !!spGoSrc )
  {
    hr = spGoSrc->getMembers(m_Members);
  }
  return hr;
} // copyMembersFrom

//-----------------------------------------------------------------------------
// getMemberByName
//-----------------------------------------------------------------------------
CATBaseUnknown_var TCAEUTLGo::getMemberByName(const CATUnicodeString& i_rName)
{
  CATBaseUnknown_var spMemberToReturn = NULL_var;
  for( int m = 1; m <= m_Members.Size(); m++ )
  {
    TCAIUTLDoItMember_var spMember = m_Members[m];
    if( !!spMember )
    {
      CATUnicodeString name;
      HRESULT hr = spMember->getName(name);
      if( SUCCEEDED(hr) && name == i_rName )
      {
        spMemberToReturn = spMember;
        break;
      }
    }
  }
  return spMemberToReturn;
} // getMemberByName

//-----------------------------------------------------------------------------
// addMember
//-----------------------------------------------------------------------------
CATBaseUnknown_var TCAEUTLGo::addMember(const CATUnicodeString& i_rName)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( spMember == NULL_var )
  {
    spMember = TCAUTLInst("UTLDoItMember");
    if( !!spMember )
    {
      hr = spMember->setName(i_rName);
      if( SUCCEEDED(hr) )
      {
        m_Members.Append(spMember);
      }
    }
  }
  return spMember;
} // addMember  

//-----------------------------------------------------------------------------
// needs
//-----------------------------------------------------------------------------
void TCAEUTLGo::needs(const CATUnicodeString& i_rType, const CATUnicodeString& i_rName)
{
  // cerr << endl << "VTA-GO-ERROR: [" << this->GetImpl()->IsA() << "] needs \"" << i_rName << "\" (" << i_rType << ")" << endl;
  return;
} // needs 

//-----------------------------------------------------------------------------
// CATDialog*
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::setDlg(const CATUnicodeString& i_rName, CATDialog* i_pValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setDlg(i_pValue);
  }
  return hr;
}
CATDialog* TCAEUTLGo::getDlg(const CATUnicodeString& i_rName)
{
  CATDialog* pDlg = NULL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    pDlg = spMember->getDlg();
  }
  else
  {
    this->needs("CATDialog*", i_rName);
  }
  return pDlg;
} // CATDialog*

//-----------------------------------------------------------------------------
// CATBaseUnknown_var
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::setUnknown(const CATUnicodeString& i_rName, CATBaseUnknown_var i_spValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setUnknown(i_spValue);
  }
  return hr;
}
CATBaseUnknown_var TCAEUTLGo::getUnknown(const CATUnicodeString& i_rName)
{
  HRESULT hr = E_FAIL;
  CATBaseUnknown_var spToReturn = NULL_var;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    spToReturn = spMember->getUnknown();
    hr = S_OK;
  }
  else
  {
    this->needs("CATBaseUnknown_var", i_rName);
  }
  return spToReturn;
} // CATBaseUnknown_var

//-----------------------------------------------------------------------------
// CATBaseUnknown_var getValue 
//-----------------------------------------------------------------------------
CATBaseUnknown_var TCAEUTLGo::getValue(const CATUnicodeString& i_rName)
{
  CATBaseUnknown_var spUnk = this->getUnknown(i_rName);
  return spUnk;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, CATBaseUnknown_var i_spValue)
{
  HRESULT hr = this->setUnknown(i_rName, i_spValue);
  return hr;
} // CATBaseUnknown_var setValue

//-----------------------------------------------------------------------------
// int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, int& o_rValue)
{
  o_rValue = 0;
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("int", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const int& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  return hr;
} // int

//-----------------------------------------------------------------------------
// unsigned int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, unsigned int& o_rValue)
{
  o_rValue = 0;
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("unsigned int", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const unsigned int& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  return hr;
} // unsigned int

//-----------------------------------------------------------------------------
// CATBoolean
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATBoolean& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue = FALSE;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATBoolean", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATBoolean& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  return hr;
} // CATBoolean 

//-----------------------------------------------------------------------------
// CATString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATString& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue = "";
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATString", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATString& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  return hr;
} // CATString 

//-----------------------------------------------------------------------------
// CATUnicodeString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATUnicodeString& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue = "";
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATUnicodeString", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATUnicodeString& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  return hr;
} // CATUnicodeString 

//-----------------------------------------------------------------------------
// CATListValCATBaseUnknown_var
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATListValCATBaseUnknown_var& o_rListValue)
{
  HRESULT hr = E_FAIL;
  o_rListValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rListValue);
  }
  else
  {
    this->needs("CATListValCATBaseUnknown_var", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATListValCATBaseUnknown_var& i_rListValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rListValue);
  }
  return hr;
} // CATListValCATBaseUnknown_var

//-----------------------------------------------------------------------------
// unsigned long
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, unsigned long& o_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("unsigned long", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const unsigned long& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  return hr;
} // unsigned long

//-----------------------------------------------------------------------------
// CATBaseUnknown_var Input
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::setInput(CATBaseUnknown_var i_spValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setUnknown(i_spValue);
  }
  return hr;
}
CATBaseUnknown_var TCAEUTLGo::getInput(const int& i_rIdx)
{
  CATBaseUnknown_var spUnk = NULL_var;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    spUnk = spInputMember->getUnknown();
  }
  return spUnk;
} // CATBaseUnknown_var Input

//-----------------------------------------------------------------------------
// int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getInput(int& o_rValue, const int& i_rIdx)
{
  o_rValue = 0;
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const int& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
} // int

//-----------------------------------------------------------------------------
// unsigned int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getInput(unsigned int& o_rValue, const int& i_rIdx)
{
  o_rValue = 0;
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const unsigned int& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
} // unsigned int

//-----------------------------------------------------------------------------
// CATBoolean
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getInput(CATBoolean& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue = FALSE;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATBoolean& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
} // CATBoolean 

//-----------------------------------------------------------------------------
// CATString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getInput(CATString& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue = "";
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATString& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
} // CATString 

//-----------------------------------------------------------------------------
// CATUnicodeString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getInput(CATUnicodeString& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue = "";
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATUnicodeString& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
} // CATUnicodeString 

//-----------------------------------------------------------------------------
// CATListValCATBaseUnknown_var
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getInput(CATListValCATBaseUnknown_var& o_rListValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rListValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rListValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATListValCATBaseUnknown_var& i_rListValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rListValue);
  }
  return hr;
} // CATListValCATBaseUnknown_var

//-----------------------------------------------------------------------------
// unsigned long
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getInput(unsigned long& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const unsigned long& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
} // unsigned long


//-----------------------------------------------------------------------------
// CATBaseUnknown_var Output
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::setOutput(CATBaseUnknown_var i_spValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setUnknown(i_spValue);
  }
  return hr;
}
CATBaseUnknown_var TCAEUTLGo::getOutput(const int& i_rIdx)
{
  CATBaseUnknown_var spUnk = NULL_var;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    spUnk = spOutputMember->getUnknown();
  }
  return spUnk;
} // CATBaseUnknown_var Output

//-----------------------------------------------------------------------------
// int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getOutput(int& o_rValue, const int& i_rIdx)
{
  o_rValue = 0;
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const int& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // int

//-----------------------------------------------------------------------------
// unsigned int
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getOutput(unsigned int& o_rValue, const int& i_rIdx)
{
  o_rValue = 0;
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const unsigned int& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // unsigned int

//-----------------------------------------------------------------------------
// CATBoolean
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getOutput(CATBoolean& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue = FALSE;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATBoolean& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATBoolean 

//-----------------------------------------------------------------------------
// CATString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getOutput(CATString& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue = "";
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATString& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATString 

//-----------------------------------------------------------------------------
// CATUnicodeString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getOutput(CATUnicodeString& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue = "";
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATUnicodeString& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATUnicodeString 

//-----------------------------------------------------------------------------
// CATListValCATBaseUnknown_var
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getOutput(CATListValCATBaseUnknown_var& o_rListValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rListValue.RemoveAll();
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rListValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATListValCATBaseUnknown_var& i_rListValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rListValue);
  }
  return hr;
} // CATListValCATBaseUnknown_var

//-----------------------------------------------------------------------------
// unsigned long
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getOutput(unsigned long& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const unsigned long& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // unsigned long

//-----------------------------------------------------------------------------
// CATLISTP(CATCell)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATLISTP(CATCell)& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATLISTP(CATCell)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATLISTP(CATCell)& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATLISTP(CATCell)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATLISTP(CATCell)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATLISTP(CATCell)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATLISTP(CATCell)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATLISTP(CATCell)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATLISTP(CATCell)


//-----------------------------------------------------------------------------
// CATMathVector
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATMathVector& o_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATMathVector", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATMathVector& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATMathVector", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATMathVector& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATMathVector& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATMathVector& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATMathVector& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATMathVector

//-----------------------------------------------------------------------------
// CATMathPoint
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATMathPoint& o_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATMathPoint", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATMathPoint& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATMathPoint", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATMathPoint& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATMathPoint& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATMathPoint& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATMathPoint& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATMathPoint

//-----------------------------------------------------------------------------
// CATLISTV(CATMathPoint)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATLISTV(CATMathPoint)& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATLISTV(CATMathPoint)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATLISTV(CATMathPoint)& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATLISTV(CATMathPoint)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATLISTV(CATMathPoint)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATLISTV(CATMathPoint)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATLISTV(CATMathPoint)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATLISTV(CATMathPoint)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATLISTV(CATMathPoint)

//-----------------------------------------------------------------------------
// CATLISTV(CATMathVector)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATLISTV(CATMathVector)& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATLISTV(CATMathVector)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATLISTV(CATMathVector)& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATLISTV(CATMathVector)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATLISTV(CATMathVector)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATLISTV(CATMathVector)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATLISTV(CATMathVector)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATLISTV(CATMathVector)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATLISTV(CATMathVector)

//-----------------------------------------------------------------------------
// CATLISTV(CATMathPlane)
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATLISTV(CATMathPlane)& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATLISTV(CATMathPlane)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATLISTV(CATMathPlane)& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATLISTV(CATMathPlane)", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATLISTV(CATMathPlane)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATLISTV(CATMathPlane)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATLISTV(CATMathPlane)& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATLISTV(CATMathPlane)& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATLISTV(CATMathPlane)

//-----------------------------------------------------------------------------
// CATListOfCATUnicodeString
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATListOfCATUnicodeString& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATListOfCATUnicodeString", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATListOfCATUnicodeString& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATListOfCATUnicodeString", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATListOfCATUnicodeString& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATListOfCATUnicodeString& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATListOfCATUnicodeString& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATListOfCATUnicodeString& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATListOfCATUnicodeString

//-----------------------------------------------------------------------------
// CATListOfDouble
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATListOfDouble& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATListOfDouble", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATListOfDouble& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATListOfDouble", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATListOfDouble& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATListOfDouble& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATListOfDouble& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATListOfDouble& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
}
CATListOfDouble& TCAEUTLGo::getInOut(const int& i_rIdx)
{
  TCAIUTLDoItMember_var spOutputMember = this->getInOutMember(i_rIdx);
  return spOutputMember->getIOValue();
} // CATListOfDouble

//-----------------------------------------------------------------------------
// CATListOfInt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATListOfInt& o_rValue)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATListOfInt", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATListOfInt& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATListOfInt", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATListOfInt& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  o_rValue.RemoveAll();
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATListOfInt& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATListOfInt& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATListOfInt& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATListOfInt

//-----------------------------------------------------------------------------
// IID
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, IID& o_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("IID", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const IID& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("IID", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(IID& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const IID& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(IID& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const IID& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // IID

//-----------------------------------------------------------------------------
// CATDocument*
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATDocument*& o_rpValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rpValue);
  }
  else
  {
    this->needs("CATDocument*", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, CATDocument*& i_rpValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rpValue);
  }
  else
  {
    this->needs("CATDocument*", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATDocument*& o_rpValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rpValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(CATDocument*& i_rpValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rpValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATDocument*& o_rpValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rpValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(CATDocument*& i_rpValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rpValue);
  }
  return hr;
} // CATDocument*

//-----------------------------------------------------------------------------
// CATPathElement
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATPathElement& o_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATPathElement", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATPathElement& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATPathElement", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATPathElement& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATPathElement& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATPathElement& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATPathElement& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATPathElement

//-----------------------------------------------------------------------------
// CATMathPlane
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, CATMathPlane& o_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("CATMathPlane", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const CATMathPlane& i_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("CATMathPlane", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(CATMathPlane& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const CATMathPlane& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(CATMathPlane& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const CATMathPlane& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // CATMathPlane

//-----------------------------------------------------------------------------
// double
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo::getValue(const CATUnicodeString& i_rName, double& o_rValue)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->getMemberByName(i_rName);
  if( !!spMember )
  {
    hr = spMember->getValue(o_rValue);
  }
  else
  {
    this->needs("double", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::setValue(const CATUnicodeString& i_rName, const double& i_rValue)
{
  if( i_rValue != i_rValue )
  {
    cerr << __FUNCTION__ << " ERROR: \t" << i_rName << " == " << i_rValue << endl;
  }
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spMember = this->addMember(i_rName);
  if( !!spMember )
  {
    hr = spMember->setValue(i_rValue);
  }
  else
  {
    this->needs("double", i_rName);
  }
  return hr;
}
HRESULT TCAEUTLGo::getInput(double& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setInput(const double& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spInputMember = this->getInputMember(i_rIdx);
  if( !!spInputMember )
  {
    hr = spInputMember->setValue(i_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::getOutput(double& o_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->getValue(o_rValue);
  }
  return hr;
}
HRESULT TCAEUTLGo::setOutput(const double& i_rValue, const int& i_rIdx)
{
  HRESULT hr = E_FAIL;
  TCAIUTLDoItMember_var spOutputMember = this->getOutputMember(i_rIdx);
  if( !!spOutputMember )
  {
    hr = spOutputMember->setValue(i_rValue);
  }
  return hr;
} // double

