// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGo3DPlane.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGo3DPlane.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATAfrCommandHeaderServices.h"

TCA_UTL_COMPONENT_CPP(UTLGo3DPlane)

CATImplementClass(TCAEUTLGo3DPlane,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGo3DPlane);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGo3DPlane);

//-----------------------------------------------------------------------------
// TCAEUTLGo3DPlane : constructor
//-----------------------------------------------------------------------------
TCAEUTLGo3DPlane::TCAEUTLGo3DPlane() 
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
}

//-----------------------------------------------------------------------------
// TCAEUTLGo3DPlane : destructor
//-----------------------------------------------------------------------------
TCAEUTLGo3DPlane::~TCAEUTLGo3DPlane()
{ 
}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo3DPlane::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Creates new 3D Plane based on three 3D points, using the specified coordinates(x1, y1, z1) for the first point, (x2, y2, z2) for the second point and (x3, y3, z3) for the second point. ";
  o_rInfo = "Example request: 'new plane by 8.9 8 1.6  8;0.98;4.987 and 0.9;8;1'";
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo3DPlane::doIt(void)
{ 
  if( m_spThis == NULL_var || m_spSingleTon == NULL_var )
  {
    return E_FAIL;
  }
  CATListOfCATUnicodeString tokens;
  m_spThis->getInput(tokens);
  int cntTok = tokens.Size();
  CATUnicodeString x1("0,00");
  CATUnicodeString y1("0,00");
  CATUnicodeString z1("0,00"); 
  CATUnicodeString x2("10,00");
  CATUnicodeString y2("10,00");
  CATUnicodeString z2("10,00");
  CATUnicodeString x3("20,00");
  CATUnicodeString y3("30,00");
  CATUnicodeString z3("40,00");
  if( cntTok >= 9 )
  {
    x1 = tokens[1];
    y1 = tokens[2];
    z1 = tokens[3];
    x2 = tokens[4];
    y2 = tokens[5];
    z2 = tokens[6];
    x3 = tokens[7];
    y3 = tokens[8];
    z3 = tokens[9];
  } 
  if( _putenv_s("x1", x1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("y1", y1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("z1", z1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("x2", x2) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("y2", y2) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("z2", z2) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("x3", x3) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("y3", y3) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("z3", z3) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  CATString macroName("UTLGo3DPlane.CATScript");
  m_spSingleTon->setValue("macro_name", macroName);

  HRESULT hr = E_FAIL;
  CATCommand* pCmd = NULL;
  CATAfrStartCommand("TCAUTLMacro", pCmd);
  if( pCmd )
  {
    pCmd = NULL;
    hr = S_OK;
  }
  return hr;
} // doIt