// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGo3DLine.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGo3DLine.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATAfrCommandHeaderServices.h"

TCA_UTL_COMPONENT_CPP(UTLGo3DLine)

CATImplementClass(TCAEUTLGo3DLine,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGo3DLine);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGo3DLine);

//-----------------------------------------------------------------------------
// TCAEUTLGo3DLine : constructor
//-----------------------------------------------------------------------------
TCAEUTLGo3DLine::TCAEUTLGo3DLine() 
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
}

//-----------------------------------------------------------------------------
// TCAEUTLGo3DLine : destructor
//-----------------------------------------------------------------------------
TCAEUTLGo3DLine::~TCAEUTLGo3DLine()
{ 
}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo3DLine::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Creates new 3D line based on two 3D points, using the specified coordinates(x1, y1, z1) for the first point and (x2, y2, z2) for the second point. ";
  o_rInfo = "Example request: 'new line from 8.9 8 1.6 to 8;0.98;4.987'";
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo3DLine::doIt(void)
{ 

  if( m_spThis == NULL_var || m_spSingleTon == NULL_var )
  {
    return E_FAIL;
  }
  CATListOfCATUnicodeString tokens;
  m_spThis->getInput(tokens);
  int cntTok = tokens.Size();
  CATUnicodeString x1("0,00");
  CATUnicodeString y1("0,00");
  CATUnicodeString z1("0,00"); 
  CATUnicodeString x2("10,00");
  CATUnicodeString y2("10,00");
  CATUnicodeString z2("10,00");
  if( cntTok >= 6 )
  {
    x1 = tokens[1];
    y1 = tokens[2];
    z1 = tokens[3];
    x2 = tokens[4];
    y2 = tokens[5];
    z2 = tokens[6];
  } 
  if( _putenv_s("x1", x1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("y1", y1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("z1", z1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("x2", x2) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("y2", y2) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("z2", z2) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }

  CATString macroName("UTLGo3DLine.CATScript");
  m_spSingleTon->setValue("macro_name", macroName);

  HRESULT hr = E_FAIL;
  CATCommand* pCmd = NULL;
  CATAfrStartCommand("TCAUTLMacro", pCmd);
  if( pCmd )
  {
    pCmd = NULL;
    hr = S_OK;
  }
  return hr;
} // doIt