// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// TCAEUTLGo3DPoint.cpp
// Provide implementation to interface
//    TCAIUTLDoIt
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Sep 2018  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "CATIContainer.h"  
#include "TCAIUTLGo.h" 
#include "TCAEUTLGo3DPoint.h" 
#include "CATSessionServices.h"
#include "TCAIUTLDoItMember.h"
#include "CATLISTV_CATISpecAttrKey.h"
#include "CATScriptUtilities.h"
#include "CATAutoConversions.h"
#include "CATAfrCommandHeaderServices.h"
#include <stdlib.h>

TCA_UTL_COMPONENT_CPP(UTLGo3DPoint)

CATImplementClass(TCAEUTLGo3DPoint,
                  DataExtension,
                  CATBaseUnknown,
                  UTLGo3DPoint);

#include "TIE_TCAIUTLDoIt.h"
TIE_TCAIUTLDoIt(TCAEUTLGo3DPoint);

#include "TIE_CATIAlias.h"
TIE_CATIAlias(TCAEUTLGo3DPoint);

#include "TIE_CATINavigateObject.h"
TIE_CATINavigateObject(TCAEUTLGo3DPoint);

//-----------------------------------------------------------------------------
// TCAEUTLGo3DPoint : constructor
//-----------------------------------------------------------------------------
TCAEUTLGo3DPoint::TCAEUTLGo3DPoint()
{
  m_spThis = this;
  m_spSingleTon = TCAUTLSingleTon();
}

//-----------------------------------------------------------------------------
// TCAEUTLGo3DPoint : destructor
//-----------------------------------------------------------------------------
TCAEUTLGo3DPoint::~TCAEUTLGo3DPoint()
{}

//-----------------------------------------------------------------------------
// getInfo
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo3DPoint::getInfo(CATUnicodeString& o_rInfo)
{
  o_rInfo = "Creates a new 3D point using the specified coordinates x;y;z. ";
  o_rInfo += "Generates a point in 3D space at the given coordinates x;y;z. ";
  o_rInfo += "Inserts a 3D point at the specified location defined by Cartesian coordinates. ";
  o_rInfo += "Adds a spatial point using exact position values on X, Y, and Z axes. ";
  o_rInfo += "Constructs a point in the 3D environment at x;y;z. ";
  o_rInfo += "Defines a geometric point in 3D space using user-provided coordinates. ";
  o_rInfo += "Create point at coordinates x;y;z. ";
  o_rInfo += "Insert 3D point at location x;y;z. ";
  o_rInfo += "Place a new point in 3D space at x;y;z. ";
  o_rInfo += "Use coordinates to define a point in 3D geometry. ";
  o_rInfo += "Specify a 3D point location using numeric coordinates. ";
  o_rInfo += "Erstellt einen 3D-Punkt an den angegebenen Koordinaten x;y;z. ";
  o_rInfo += "Example request: 'new point in 8.9 8 1.6' or 'erzeuge punkt in 8,9;9.0;76.0'";
  return S_OK;
} // getInfo

//-----------------------------------------------------------------------------
// doIt
//-----------------------------------------------------------------------------
HRESULT TCAEUTLGo3DPoint::doIt(void)
{
  if( m_spThis == NULL_var || m_spSingleTon == NULL_var )
  {
    return E_FAIL;
  }
  CATListOfCATUnicodeString tokens;
  m_spThis->getInput(tokens);
  int cntTok = tokens.Size();
  CATUnicodeString x1("0,00");
  CATUnicodeString y1("0,00");
  CATUnicodeString z1("0,00");
  if( cntTok >= 3 )
  {
    x1 = tokens[1];
    y1 = tokens[2];
    z1 = tokens[3];
  }
  if( _putenv_s("x1", x1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("y1", y1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }
  if( _putenv_s("z1", z1) != 0 )
  {
    cerr << "Failed to set environment variable!" << endl;
  }

  CATString macroName("UTLGo3DPoint.CATScript");
  m_spSingleTon->setValue("macro_name", macroName);

  HRESULT hr = E_FAIL;
  CATCommand* pCmd = NULL;
  CATAfrStartCommand("TCAUTLMacro", pCmd);
  if( pCmd )
  {
    pCmd = NULL;
    hr = S_OK;
  }
  return hr;
} // doIt

//-----------------------------------------------------------------------------
// SetAlias
//-----------------------------------------------------------------------------
void TCAEUTLGo3DPoint::SetAlias(const CATUnicodeString& iName)
{
  cerr << __FUNCTION__ << endl;
  return;
} // SetAlias

//-----------------------------------------------------------------------------
// GetAlias
//-----------------------------------------------------------------------------
CATUnicodeString TCAEUTLGo3DPoint::GetAlias(void)
{
  cerr << __FUNCTION__ << endl;

  CATUnicodeString alias("blablabla");
  return alias;
} // GetAlias

//-----------------------------------------------------------------------------
// GetAlias
//-----------------------------------------------------------------------------
CATListValCATBaseUnknown_var* TCAEUTLGo3DPoint::GetChildren(void)
{
  return NULL;
}

//-----------------------------------------------------------------------------
// GetAlias
//-----------------------------------------------------------------------------
CATListValCATUnicodeString* TCAEUTLGo3DPoint::GetIdentificators(void)
{
  CATListValCATUnicodeString* pIdentificators = new CATListValCATUnicodeString;  
  pIdentificators->Append("blablabla_31*_999*");
  return pIdentificators;
}

//----------------------------------------------------------------------