# COPYRIGHT Dassault Systemes 2003
#======================================================================
# Imakefile for module TCAMTAInterfacesUUID.m
#======================================================================
#
#  Oct 2003  Creation: Code generated by the CAA wizard  wdyck
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
