//===================================================================
// COPYRIGHT  2023.03.20
//===================================================================
// TCADRTXmlMD.cpp
// Header definition of class TCADRTXmlMD
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023.03.20 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByTCADRTXmlMD_H
#define ExportedByTCADRTXmlMD_H
#if defined(__TCADRTXmlMD)
# define ExportedByTCADRTXmlMD   DSYExport
#else // __TCADRTXmlMD
# define ExportedByTCADRTXmlMD   DSYImport
#endif  // __TCADRTXmlMD
#include "DSYExport.h"
#endif //ExportedByTCADRTXmlMD_H

