//===================================================================
// COPYRIGHT  2023.03.20
//===================================================================
// TCAListSpecAttr.cpp
// Header definition of class TCAListSpecAttr
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2023.03.20 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByTCAListSpecAttr_H
#define ExportedByTCAListSpecAttr_H
#if defined(__TCAListSpecAttr)
# define ExportedByTCAListSpecAttr   DSYExport
#else // __TCAListSpecAttr
# define ExportedByTCAListSpecAttr   DSYImport
#endif  // __TCAListSpecAttr
#include "DSYExport.h"
#endif //ExportedByTCAListSpecAttr_H

