//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAUTLDoItMD.cpp
// Header definition of class TCAUTLDoItMD
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByTCAUTLDoItMD_H
#define ExportedByTCAUTLDoItMD_H
#if defined(__TCAUTLDoItMD)
# define ExportedByTCAUTLDoItMD   DSYExport
#else // __TCAUTLDoItMD
# define ExportedByTCAUTLDoItMD   DSYImport
#endif  // __TCAUTLDoItMD
#include "DSYExport.h"
#endif //ExportedByTCAUTLDoItMD_H

