// COPYRIGHT Dassault Systemes 2013
//===================================================================
//
// TCAUTLListAttrDlg.cpp
// The dialog : TCAUTLListAttrDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2013  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#include "TCAUTLListAttrDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef TCAUTLListAttrDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif 

//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TCAUTLListAttrDlg::TCAUTLListAttrDlg() :
CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
              //CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
              "TCAUTLListAttrDlg", CATDlgGridLayout
              //END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
              )
{

} // Constructor

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TCAUTLListAttrDlg::~TCAUTLListAttrDlg()
{
}  // Destructor

//-------------------------------------------------------------------------
// Build
//-------------------------------------------------------------------------
void TCAUTLListAttrDlg::Build( void )
{
 

  return;
} // Build

