// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TCAUTLListDocsFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Dec 2012  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("Dialog",Public);
// END WIZARD EDITION ZONE
AddPrereqComponent("TCAUTLInterfaces", Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("ProductStructure",Protected);
AddPrereqComponent("KnowledgeInterfaces",Protected);
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("GeometricObjects",Protected);
AddPrereqComponent("GMModelInterfaces",Protected);
AddPrereqComponent("MechanicalModeler",Protected);
AddPrereqComponent("DraftingInterfaces",Protected);
AddPrereqComponent("XMLParser",Protected);
AddPrereqComponent("Administration", Protected);
AddPrereqComponent("Mathematics", Protected);
AddPrereqComponent("AutomationInterfaces", Protected);
AddPrereqComponent("CATInstantCollabDesignCAAItf", Protected);
AddPrereqComponent("CATTPSInterfaces", Protected);
AddPrereqComponent("CATIAApplicationFrame", Protected);
AddPrereqComponent("CATAssemblyInterfaces", Protected);
AddPrereqComponent("MechanicalModelerUI", Protected);
AddPrereqComponent("ConstraintModeler", Protected);
AddPrereqComponent("ConstraintModelerInterfaces", Protected);
AddPrereqComponent("DialogEngine", Protected);
AddPrereqComponent("Visualization", Protected);
AddPrereqComponent("VisualizationBase", Protected);
AddPrereqComponent("InteractiveInterfaces", Protected);
AddPrereqComponent("ConstraintModelerUI", Protected);
AddPrereqComponent("MeasureGeometryInterfaces", Protected);
AddPrereqComponent("CATSketcherUseItf", Protected);
AddPrereqComponent("Tessellation", Protected);
AddPrereqComponent("GSMInterfaces", Protected);
AddPrereqComponent("Print", Protected);
AddPrereqComponent("PrintBase", Protected);