// COPYRIGHT Dassault Systemes 2012
//===================================================================
//
// TCAEUTLListDocsAddin.h
// Provide implementation to interface
//    CATIAfrGeneralWksAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	TCAUTLListDocsAddin
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIAfrGeneralWksAddin

//End CAA2 Wizard Generation Report
//
//  Dec 2012  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAEUTLListDocsAddin_H
#define TCAEUTLListDocsAddin_H

#include "CATBaseUnknown.h"
#include "CATCommandHeader.h"
#include "CATCmdContainer.h"
#include "CATCmdWorkbench.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIAfrGeneralWksAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TCAEUTLListDocsAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

    // Standard constructors and destructors for an implementation class
    // -----------------------------------------------------------------
    TCAEUTLListDocsAddin ();
    virtual ~TCAEUTLListDocsAddin ();

    void CreateCommands( void );
    CATCmdContainer* CreateToolbars( void );

  private:

    // The copy constructor and the equal operator must not be implemented
    // -------------------------------------------------------------------
    TCAEUTLListDocsAddin (TCAEUTLListDocsAddin &);
    TCAEUTLListDocsAddin& operator=(TCAEUTLListDocsAddin&);

};

//-----------------------------------------------------------------------

#endif
