// COPYRIGHT Dassault Systemes 2013
//===================================================================
//
// TCAUTLGPTCmd.h
// The dialog : TCAUTLGPTCmd
// It is a command.
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jan 2013  Creation: Code generated by the CAA wizard  wdyck
//===================================================================
#ifndef TCAUTLGPTCmd_H
#define TCAUTLGPTCmd_H

#include "CATDlgCombo.h"
#include "CATGeoFactory.h"
#include "CATListOfInt.h"
#include "CATDlgFrame.h"
#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATISpecObject.h"
#include "CATLISTV_CATISpecObject.h"
#include "CATUnicodeString.h"
//----------------------------------------------------------------------

/**
* Describe the purpose of your panel here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog framework.
* (consult base class description).
*/
class TCAUTLGPTCmd : public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource(TCAUTLGPTCmd, CATDlgDialog)


private:

  CATDlgEditor* m_pQuestionEditor;

  CATDocument* m_pCurrentDoc;

  CATBoolean m_OpenAI;

public:

  TCAUTLGPTCmd(CATISpecObject_var i_spSpec = NULL_var);
  virtual ~TCAUTLGPTCmd();

  void Build();


  /**
  * Overload this method: when your command gains focus
  * <p>
  * Activates a command.
  * @param iFromClient
  *   The command that requests to activate the current one.
  * @param iEvtDat
  *   The notification sent.
  */
  virtual CATStatusChangeRC Activate(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);

  /**
  *  Overload this method: when your command loses focus
  * <p>
  * Deactivates a command.
  * @param iFromClient
  *   The command that takes the current active place.
  * @param iEvtDat
  *   The notification sent.
  */
  virtual CATStatusChangeRC Desactivate(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);

  /**
  *  Overload this method: when your command is canceled
  * <p>
  * Cancels a command.
  * @param iFromClient
  *   The command that takes the current active place.
  * @param iEvtDat
  *   The notification sent.
  */
  virtual CATStatusChangeRC Cancel(
    CATCommand* iFromClient,
    CATNotification* iEvtDat);

  /**
* This method compares strings.
*/
//int stringCompare( CATUnicodeString* i_pParam1, CATUnicodeString* i_pParam2 );

protected:


private:


  void askAI(CATCommand*, CATNotification*, CATCommandClientData i_Data);

  CATBoolean GetSystemVariable(const CATUnicodeString& iSystemVariable, CATUnicodeString& oVarValue);

  CATUnicodeString getUTF8Str(const CATUnicodeString& i_rStr);
};

//----------------------------------------------------------------------

#endif
