//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAIUTLDoIt.cpp
// Header definition of class TCAIUTLDoIt
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef TCAIUTLDoIt_H
#define TCAIUTLDoIt_H

#include "TCAUTLItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"



extern ExportedByTCAUTLItfCPP  IID IID_TCAIUTLDoIt;
class ExportedByTCAUTLItfCPP TCAIUTLDoIt : public CATBaseUnknown
{
  CATDeclareInterface;

public:

  virtual HRESULT doIt(void) = 0;
  virtual HRESULT getInfo(CATUnicodeString& o_rInfo) = 0;
};

//-----------------------------------------------------------------------
CATDeclareHandler(TCAIUTLDoIt, CATBaseUnknown);

#endif
