//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAIUTLDoItMember.cpp
// Header definition of class TCAIUTLDoItMember
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef TCAIUTLDoItMember_H
#define TCAIUTLDoItMember_H

#include "TCAUTLItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATMathVector.h"
#include "CATMathPlane.h"
#include "CATPathElement.h"
#include "CATLISTV_CATBaseUnknown.h" 
#include "CATUnicodeString.h" 
#include "CATListOfInt.h"
#include "CATDocument.h" 
#include "CATDialog.h" 
#include "CATListOfDouble.h" 
#include "CATListOfCATCells.h"
#include "CATLISTV_CATMathPoint.h"
#include "CATLISTV_CATMathVector.h"
#include "CATLISTV_CATMathPlane.h"

 

extern ExportedByTCAUTLItfCPP  IID IID_TCAIUTLDoItMember;


class ExportedByTCAUTLItfCPP TCAIUTLDoItMember : public CATBaseUnknown
{
  CATDeclareInterface;

public:

  // dump
  virtual void dump(void) = 0;

  // copy all values from othe member
  virtual HRESULT copyValuesFrom(CATBaseUnknown_var i_spMemberFrom) = 0;

  // name
  virtual HRESULT setName(const CATUnicodeString& i_rName) = 0;
  virtual HRESULT getName(CATUnicodeString& o_rName) = 0;

  // trace
  virtual void trace(void) = 0;

  // Dlg
  virtual HRESULT setDlg(CATDialog* i_pValue) = 0;
  virtual CATDialog* getDlg(void) = 0;

  // CATBaseUnknown
  virtual HRESULT setUnknown(CATBaseUnknown_var i_spValue) = 0;
  virtual CATBaseUnknown_var getUnknown(void) = 0;

  // int
  virtual HRESULT setValue(const int& i_rValue) = 0;
  virtual HRESULT getValue(int& o_rValue) = 0;

  // double
  virtual HRESULT setValue(const double& i_rValue) = 0;
  virtual HRESULT getValue(double& o_rValue) = 0;

  // unsigned int 
  virtual HRESULT setValue(const unsigned int& i_rValue) = 0;
  virtual HRESULT getValue(unsigned int& o_rValue) = 0;

  // CATBoolean 
  virtual HRESULT setValue(const CATBoolean& i_rValue) = 0;
  virtual HRESULT getValue(CATBoolean& o_rValue) = 0;

  // CATString
  virtual HRESULT setValue(const CATString& i_rValue) = 0;
  virtual HRESULT getValue(CATString& o_rValue) = 0;

  // CATUnicodeString
  virtual HRESULT setValue(const CATUnicodeString& i_rValue) = 0;
  virtual HRESULT getValue(CATUnicodeString& o_rValue) = 0;

  // CATListValCATBaseUnknown_var 
  virtual HRESULT getValue(CATListValCATBaseUnknown_var& o_rListValue) = 0;
  virtual HRESULT setValue(const CATListValCATBaseUnknown_var& i_rListValue) = 0;

  // CATLISTP(CATCell) 
  virtual HRESULT getValue(CATLISTP(CATCell)& o_rListValue) = 0;
  virtual HRESULT setValue(const CATLISTP(CATCell)& i_rListValue) = 0;

  // CATMathPoint 
  virtual HRESULT getValue(CATMathPoint& o_rValue) = 0;
  virtual HRESULT setValue(const CATMathPoint& i_rValue) = 0;

  // CATMathVector 
  virtual HRESULT getValue(CATMathVector& o_rValue) = 0;
  virtual HRESULT setValue(const CATMathVector& i_rValue) = 0;

  // CATLISTV(CATMathPoint) 
  virtual HRESULT getValue(CATLISTV(CATMathPoint)& o_rListValue) = 0;
  virtual HRESULT setValue(const CATLISTV(CATMathPoint)& i_rListValue) = 0;

  // CATLISTV(CATMathVector) 
  virtual HRESULT getValue(CATLISTV(CATMathVector)& o_rListValue) = 0;
  virtual HRESULT setValue(const CATLISTV(CATMathVector)& i_rListValue) = 0;

  // CATLISTV(CATMathPlane) 
  virtual HRESULT getValue(CATLISTV(CATMathPlane)& o_rListValue) = 0;
  virtual HRESULT setValue(const CATLISTV(CATMathPlane)& i_rListValue) = 0;

  // CATListOfCATUnicodeString 
  virtual HRESULT getValue(CATListOfCATUnicodeString& o_rListValue) = 0;
  virtual HRESULT setValue(const CATListOfCATUnicodeString& i_rListValue) = 0;

  // CATListOfDouble 
  virtual HRESULT getValue(CATListOfDouble& o_rListValue) = 0;
  virtual HRESULT setValue(const CATListOfDouble& i_rListValue) = 0;

  virtual CATListOfDouble& getIOValue(void) = 0;

  // CATListOfInt 
  virtual HRESULT getValue(CATListOfInt& o_rListValue) = 0;
  virtual HRESULT setValue(const CATListOfInt& i_rListValue) = 0;

  // unsigned long
  virtual HRESULT getValue(unsigned long& o_rValue) = 0;
  virtual HRESULT setValue(const unsigned long& i_rValue) = 0;

  // IID 
  virtual HRESULT getValue(IID& o_rValue) = 0;
  virtual HRESULT setValue(const IID& i_rValue) = 0;

  // CATPathElement 
  virtual HRESULT getValue(CATPathElement& o_rValue) = 0;
  virtual HRESULT setValue(const CATPathElement& i_rValue) = 0;

  // CATMathPlane 
  virtual HRESULT getValue(CATMathPlane& o_rValue) = 0;
  virtual HRESULT setValue(const CATMathPlane& i_rValue) = 0;

  // CATDocument*
  virtual HRESULT getValue(CATDocument*& o_rpValue) = 0;
  virtual HRESULT setValue(CATDocument*& i_rpValue) = 0;

};

//-----------------------------------------------------------------------
CATDeclareHandler(TCAIUTLDoItMember, CATBaseUnknown);

#endif
