//===================================================================
// COPYRIGHT  2025.08.04
//===================================================================
// TCAUTL.cpp
// Header definition of class TCAUTL
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2025.08.04 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __TCAUTLItfCPP
#define ExportedByTCAUTLItfCPP     __declspec(dllexport)
#else
#define ExportedByTCAUTLItfCPP     __declspec(dllimport)
#endif
#else
#define ExportedByTCAUTLItfCPP
#endif

